// Generated by dotnet-bindgen - Architecture
// Namespace: System
// Assembly: System.ComponentModel, System.ComponentModel.TypeConverter, System.Configuration.ConfigurationManager, System.Console, System.Memory, System.Memory.Data, System.Private.CoreLib, System.Private.Uri

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { JsonTypeInfo_1 } from "@tsonic/dotnet/System.Text.Json.Serialization.Metadata/internal/index.js";
import type { JsonSerializerContext } from "@tsonic/dotnet/System.Text.Json.Serialization/internal/index.js";
import type { JsonSerializerOptions } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import type { Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, ReadOnlyMemory_1, String as ClrString, Type } from "@tsonic/dotnet/System/internal/index.js";

export enum UriIdnScope {
    None = 0,
    AllExceptIntranet = 1,
    All = 2
}


export interface BinaryData$instance {
    readonly __tsonic_type_System_BinaryData: never;

    readonly IsEmpty: boolean;
    readonly Length: int;
    readonly MediaType: string | null;
    Equals(obj: unknown | null): boolean;
    GetHashCode(): int;
    ToArray(): byte[];
    ToMemory(): ReadOnlyMemory_1<Byte>;
    ToObjectFromJson<T extends unknown>(options?: JsonSerializerOptions | null): T | null;
    ToObjectFromJson<T extends unknown>(jsonTypeInfo: JsonTypeInfo_1<T>): T | null;
    ToStream(): Stream;
    ToString(): string;
    WithMediaType(mediaType: string | null): BinaryData;
}


export const BinaryData: {
    new(data: byte[]): BinaryData;
    new(data: byte[], mediaType: string | null): BinaryData;
    new(jsonSerializable: unknown | null, options: JsonSerializerOptions | null, type: Type | null): BinaryData;
    new(jsonSerializable: unknown | null, context: JsonSerializerContext, type: Type | null): BinaryData;
    new(data: ReadOnlyMemory_1<Byte>): BinaryData;
    new(data: ReadOnlyMemory_1<Byte>, mediaType: string | null): BinaryData;
    new(data: string): BinaryData;
    new(data: string, mediaType: string | null): BinaryData;
    readonly Empty: BinaryData;
    FromBytes(data: byte[], mediaType: string | null): BinaryData;
    FromBytes(data: byte[]): BinaryData;
    FromBytes(data: ReadOnlyMemory_1<Byte>, mediaType: string | null): BinaryData;
    FromBytes(data: ReadOnlyMemory_1<Byte>): BinaryData;
    FromObjectAsJson<T extends unknown>(jsonSerializable: T, jsonTypeInfo: JsonTypeInfo_1<T>): BinaryData;
    FromObjectAsJson<T extends unknown>(jsonSerializable: T, options?: JsonSerializerOptions | null): BinaryData;
    FromStream(stream: Stream, mediaType: string | null): BinaryData;
    FromStream(stream: Stream): BinaryData;
    FromStreamAsync(stream: Stream, mediaType: string | null, cancellationToken?: CancellationToken): Task_1<BinaryData>;
    FromStreamAsync(stream: Stream, cancellationToken?: CancellationToken): Task_1<BinaryData>;
    FromString(data: string, mediaType: string | null): BinaryData;
    FromString(data: string): BinaryData;
};


export type BinaryData = BinaryData$instance;
