// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal
// Assembly: Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { ISqlServerSingletonOptions } from "../../Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal/internal/index.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { DbConnection, DbParameter, DbTransaction } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { DbType, SqlDbType } from "@tsonic/dotnet/System.Data/internal/index.js";
import type { MemoryStream } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text/internal/index.js";
import type { Task, Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Exception, Func_2, Func_3, Func_4, Guid, IAsyncDisposable, IDisposable, Int32, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Type, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { ValueComparer } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.ChangeTracking/internal/index.js";
import type { IDiagnosticsLogger_1 } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IInfrastructure_1, IResettableService } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { ValueConverter } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.ValueConversion/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { BoolTypeMapping, ByteArrayTypeMapping, ByteTypeMapping, CoreTypeMapping, DateOnlyTypeMapping, DateTimeOffsetTypeMapping, DateTimeTypeMapping, DecimalTypeMapping, DoubleTypeMapping, ExecutionResult_1, ExecutionStrategyDependencies, FloatTypeMapping, IDatabaseCreator, IDbContextTransaction, IDbContextTransactionManager, IExceptionDetector, IExecutionStrategy, IExecutionStrategyFactory, IRawSqlCommandBuilder, IRelationalConnection, IRelationalDatabaseCreator, IRelationalTransactionFactory, IRelationalTransactionManager, IRelationalTypeMappingSource, ISqlGenerationHelper, ITransactionEnlistmentManager, ITypeMappingSource, JsonTypeMapping, LongTypeMapping, RelationalConnection, RelationalConnectionDependencies, RelationalDatabaseCreator, RelationalDatabaseCreatorDependencies, RelationalExecutionStrategyFactory, RelationalSqlGenerationHelper, RelationalSqlGenerationHelperDependencies, RelationalTransaction, RelationalTransactionFactoryDependencies, RelationalTypeMapping, RelationalTypeMappingInfo, RelationalTypeMappingSource, RelationalTypeMappingSourceDependencies, ShortTypeMapping, StoreTypePostfix, StringTypeMapping, TimeOnlyTypeMapping, TimeSpanTypeMapping, TypeMappingSourceDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbContext, DbLoggerCategory$Database$Transaction } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";

export interface ISqlServerConnection$instance extends IRelationalConnection, IRelationalTransactionManager, IDbContextTransactionManager, IResettableService, IDisposable, IAsyncDisposable {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_ISqlServerConnection: never;

    readonly IsMultipleActiveResultSetsEnabled: boolean;
    CreateMasterConnection(): ISqlServerConnection;
}


export interface ISqlServerConnection$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IResettableService, Microsoft_EntityFrameworkCore_Storage_Internal.IDbContextTransactionManager, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalConnection, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalTransactionManager, System_Internal.IAsyncDisposable, System_Internal.IDisposable {}

export type ISqlServerConnection = ISqlServerConnection$instance;

export interface SqlServerBoolTypeMapping$instance extends BoolTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerBoolTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerBoolTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>): SqlServerBoolTypeMapping;
    readonly Default: SqlServerBoolTypeMapping;
};


export type SqlServerBoolTypeMapping = SqlServerBoolTypeMapping$instance;

export interface SqlServerByteArrayTypeMapping$instance extends ByteArrayTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerByteArrayTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerByteArrayTypeMapping: {
    new(storeType: string, size: Nullable_1<System_Internal.Int32>, fixedLength: boolean, comparer: ValueComparer, sqlDbType: Nullable_1<SqlDbType>, storeTypePostfix: Nullable_1<StoreTypePostfix>): SqlServerByteArrayTypeMapping;
    readonly Default: SqlServerByteArrayTypeMapping;
};


export type SqlServerByteArrayTypeMapping = SqlServerByteArrayTypeMapping$instance;

export interface SqlServerByteTypeMapping$instance extends ByteTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerByteTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerByteTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>): SqlServerByteTypeMapping;
    readonly Default: SqlServerByteTypeMapping;
};


export type SqlServerByteTypeMapping = SqlServerByteTypeMapping$instance;

export interface SqlServerConnection$instance extends RelationalConnection, ISqlServerConnection$instance, Microsoft_EntityFrameworkCore_Storage_Internal.ITransactionEnlistmentManager {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerConnection: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IResettableService: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_ISqlServerConnection: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDbContextTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalConnection: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITransactionEnlistmentManager: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    get ConnectionString(): string | undefined;
    set ConnectionString(value: string | undefined);
    readonly IsMultipleActiveResultSetsEnabled: boolean;
    readonly SupportsAmbientTransactions: boolean;
    CreateDbConnection(): DbConnection;
    CreateMasterConnection(): ISqlServerConnection;
    ModifyConnectionString(userProvidedConnectionString: string): string;
    OpenDbConnection(errorsExpected: boolean): void;
    OpenDbConnectionAsync(errorsExpected: boolean, cancellationToken: CancellationToken): Task;
}


export const SqlServerConnection: {
    new(dependencies: RelationalConnectionDependencies): SqlServerConnection;
};


export interface __SqlServerConnection$views {
    As_ISqlServerConnection(): ISqlServerConnection$instance;
}

export type SqlServerConnection = SqlServerConnection$instance & __SqlServerConnection$views;


export interface SqlServerDatabaseCreator$instance extends RelationalDatabaseCreator {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDatabaseCreator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDatabaseCreator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalDatabaseCreator: never;

    RetryDelay: TimeSpan;
    RetryTimeout: TimeSpan;
    Create(): void;
    CreateAsync(cancellationToken?: CancellationToken): Task;
    Delete(): void;
    DeleteAsync(cancellationToken?: CancellationToken): Task;
    Exists(): boolean;
    ExistsAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    HasTables(): boolean;
    HasTablesAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
}


export const SqlServerDatabaseCreator: {
    new(dependencies: RelationalDatabaseCreatorDependencies, connection: ISqlServerConnection, rawSqlCommandBuilder: IRawSqlCommandBuilder): SqlServerDatabaseCreator;
};


export type SqlServerDatabaseCreator = SqlServerDatabaseCreator$instance;

export interface SqlServerDateOnlyTypeMapping$instance extends DateOnlyTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDateOnlyTypeMapping: never;

    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
}


export const SqlServerDateOnlyTypeMapping: (abstract new(parameters: RelationalTypeMapping_RelationalTypeMappingParameters) => SqlServerDateOnlyTypeMapping) & {
    readonly Default: SqlServerDateOnlyTypeMapping;
};


export type SqlServerDateOnlyTypeMapping = SqlServerDateOnlyTypeMapping$instance;

export interface SqlServerDateTimeOffsetTypeMapping$instance extends DateTimeOffsetTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDateTimeOffsetTypeMapping: never;

    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
}


export const SqlServerDateTimeOffsetTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, storeTypePostfix: StoreTypePostfix): SqlServerDateTimeOffsetTypeMapping;
    readonly Default: SqlServerDateTimeOffsetTypeMapping;
};


export type SqlServerDateTimeOffsetTypeMapping = SqlServerDateTimeOffsetTypeMapping$instance;

export interface SqlServerDateTimeTypeMapping$instance extends DateTimeTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDateTimeTypeMapping: never;

    readonly SqlLiteralFormatString: string;
    readonly SqlType: Nullable_1<SqlDbType>;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
}


export const SqlServerDateTimeTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, sqlDbType: Nullable_1<SqlDbType>, storeTypePostfix: StoreTypePostfix): SqlServerDateTimeTypeMapping;
    readonly Default: SqlServerDateTimeTypeMapping;
};


export type SqlServerDateTimeTypeMapping = SqlServerDateTimeTypeMapping$instance;

export interface SqlServerDecimalTypeMapping$instance extends DecimalTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDecimalTypeMapping: never;

    readonly SqlType: Nullable_1<SqlDbType>;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
}


export const SqlServerDecimalTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, precision: Nullable_1<System_Internal.Int32>, scale: Nullable_1<System_Internal.Int32>, sqlDbType: Nullable_1<SqlDbType>, storeTypePostfix: StoreTypePostfix): SqlServerDecimalTypeMapping;
    readonly Default: SqlServerDecimalTypeMapping;
};


export type SqlServerDecimalTypeMapping = SqlServerDecimalTypeMapping$instance;

export interface SqlServerDoubleTypeMapping$instance extends DoubleTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerDoubleTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    CustomizeDataReaderExpression(expression: Expression): Expression;
    GenerateNonNullSqlLiteral(value: unknown): string;
    GetDataReaderMethod(): MethodInfo;
}


export const SqlServerDoubleTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, storeTypePostfix: StoreTypePostfix): SqlServerDoubleTypeMapping;
    readonly Default: SqlServerDoubleTypeMapping;
};


export type SqlServerDoubleTypeMapping = SqlServerDoubleTypeMapping$instance;

export interface SqlServerExceptionDetector$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerExceptionDetector: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExceptionDetector: never;

    IsCancellation(exception: Exception, cancellationToken?: CancellationToken): boolean;
}


export const SqlServerExceptionDetector: {
    new(): SqlServerExceptionDetector;
};


export type SqlServerExceptionDetector = SqlServerExceptionDetector$instance;

export interface SqlServerExecutionStrategy$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerExecutionStrategy: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExecutionStrategy: never;

    readonly Dependencies: ExecutionStrategyDependencies;
    readonly RetriesOnFailure: boolean;
    Execute<TState, TResult>(state: TState, operation: Func_3<DbContext, TState, TResult>, verifySucceeded: Func_3<DbContext, TState, ExecutionResult_1<TResult>>): TResult;
    ExecuteAsync<TState, TResult>(state: TState, operation: Func_4<DbContext, TState, CancellationToken, Task_1<TResult>>, verifySucceeded: Func_4<DbContext, TState, CancellationToken, Task_1<ExecutionResult_1<TResult>>>, cancellationToken: CancellationToken): Task_1<TResult>;
}


export const SqlServerExecutionStrategy: {
    new(dependencies: ExecutionStrategyDependencies): SqlServerExecutionStrategy;
};


export type SqlServerExecutionStrategy = SqlServerExecutionStrategy$instance;

export interface SqlServerExecutionStrategyFactory$instance extends RelationalExecutionStrategyFactory {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerExecutionStrategyFactory: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExecutionStrategyFactory: never;

    CreateDefaultStrategy(dependencies: ExecutionStrategyDependencies): IExecutionStrategy;
}


export const SqlServerExecutionStrategyFactory: {
    new(dependencies: ExecutionStrategyDependencies): SqlServerExecutionStrategyFactory;
};


export type SqlServerExecutionStrategyFactory = SqlServerExecutionStrategyFactory$instance;

export interface SqlServerFloatTypeMapping$instance extends FloatTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerFloatTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerFloatTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, storeTypePostfix: StoreTypePostfix): SqlServerFloatTypeMapping;
    readonly Default: SqlServerFloatTypeMapping;
};


export type SqlServerFloatTypeMapping = SqlServerFloatTypeMapping$instance;

export interface SqlServerLongTypeMapping$instance extends LongTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerLongTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerLongTypeMapping: {
    new(storeType: string, converter: ValueConverter, comparer: ValueComparer, providerValueComparer: ValueComparer, dbType: Nullable_1<DbType>): SqlServerLongTypeMapping;
    readonly Default: SqlServerLongTypeMapping;
};


export type SqlServerLongTypeMapping = SqlServerLongTypeMapping$instance;

export interface SqlServerShortTypeMapping$instance extends ShortTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerShortTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerShortTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>): SqlServerShortTypeMapping;
    readonly Default: SqlServerShortTypeMapping;
};


export type SqlServerShortTypeMapping = SqlServerShortTypeMapping$instance;

export interface SqlServerSqlGenerationHelper$instance extends RelationalSqlGenerationHelper {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerSqlGenerationHelper: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ISqlGenerationHelper: never;

    readonly BatchTerminator: string;
    readonly StartTransactionStatement: string;
    DelimitIdentifier(identifier: string): string;
    DelimitIdentifier(builder: StringBuilder, identifier: string): void;
    DelimitJsonPathElement(pathElement: string): string;
    EscapeIdentifier(identifier: string): string;
    EscapeIdentifier(builder: StringBuilder, identifier: string): void;
    GenerateCreateSavepointStatement(name: string): string;
    GenerateReleaseSavepointStatement(name: string): string;
    GenerateRollbackToSavepointStatement(name: string): string;
}


export const SqlServerSqlGenerationHelper: {
    new(dependencies: RelationalSqlGenerationHelperDependencies): SqlServerSqlGenerationHelper;
};


export type SqlServerSqlGenerationHelper = SqlServerSqlGenerationHelper$instance;

export interface SqlServerSqlVariantTypeMapping$instance extends RelationalTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerSqlVariantTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqlServerSqlVariantTypeMapping: {
    new(storeType: string): SqlServerSqlVariantTypeMapping;
    readonly Default: SqlServerSqlVariantTypeMapping;
};


export type SqlServerSqlVariantTypeMapping = SqlServerSqlVariantTypeMapping$instance;

export interface SqlServerStringTypeMapping$instance extends StringTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerStringTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerStringTypeMapping: {
    new(storeType: string, unicode: boolean, size: Nullable_1<System_Internal.Int32>, fixedLength: boolean, sqlDbType: Nullable_1<SqlDbType>, storeTypePostfix: Nullable_1<StoreTypePostfix>, useKeyComparison: boolean): SqlServerStringTypeMapping;
    readonly Default: SqlServerStringTypeMapping;
    readonly JsonTypeDefault: SqlServerStringTypeMapping;
    readonly UnicodeDefault: SqlServerStringTypeMapping;
};


export type SqlServerStringTypeMapping = SqlServerStringTypeMapping$instance;

export interface SqlServerStructuralJsonTypeMapping$instance extends JsonTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerStructuralJsonTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    CustomizeDataReaderExpression(expression: Expression): Expression;
    EscapeSqlLiteral(literal: string): string;
    GenerateNonNullSqlLiteral(value: unknown): string;
    GetDataReaderMethod(): MethodInfo;
}


export const SqlServerStructuralJsonTypeMapping: {
    new(storeType: string): SqlServerStructuralJsonTypeMapping;
    readonly Default: SqlServerStructuralJsonTypeMapping;
    readonly JsonTypeDefault: SqlServerStructuralJsonTypeMapping;
    readonly NvarcharMaxDefault: SqlServerStructuralJsonTypeMapping;
    CreateUtf8Stream(json: string): MemoryStream;
};


export type SqlServerStructuralJsonTypeMapping = SqlServerStructuralJsonTypeMapping$instance;

export interface SqlServerTimeOnlyTypeMapping$instance extends TimeOnlyTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerTimeOnlyTypeMapping: never;

    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerTimeOnlyTypeMapping: (abstract new(parameters: RelationalTypeMapping_RelationalTypeMappingParameters) => SqlServerTimeOnlyTypeMapping) & {
    readonly Default: SqlServerTimeOnlyTypeMapping;
};


export type SqlServerTimeOnlyTypeMapping = SqlServerTimeOnlyTypeMapping$instance;

export interface SqlServerTimeSpanTypeMapping$instance extends TimeSpanTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerTimeSpanTypeMapping: never;

    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerTimeSpanTypeMapping: {
    new(storeType: string, dbType: Nullable_1<DbType>, storeTypePostfix: StoreTypePostfix): SqlServerTimeSpanTypeMapping;
    readonly Default: SqlServerTimeSpanTypeMapping;
};


export type SqlServerTimeSpanTypeMapping = SqlServerTimeSpanTypeMapping$instance;

export interface SqlServerTransaction$instance extends RelationalTransaction {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerTransaction: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDbContextTransaction: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly SupportsSavepoints: boolean;
    ReleaseSavepoint(name: string): void;
    ReleaseSavepointAsync(name: string, cancellationToken?: CancellationToken): Task;
}


export const SqlServerTransaction: {
    new(connection: IRelationalConnection, transaction: DbTransaction, transactionId: Guid, logger: IDiagnosticsLogger_1<DbLoggerCategory$Database$Transaction>, transactionOwned: boolean, sqlGenerationHelper: ISqlGenerationHelper): SqlServerTransaction;
};


export type SqlServerTransaction = SqlServerTransaction$instance;

export interface SqlServerTransactionFactory$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerTransactionFactory: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTransactionFactory: never;

    readonly Dependencies: RelationalTransactionFactoryDependencies;
    Create(connection: IRelationalConnection, transaction: DbTransaction, transactionId: Guid, logger: IDiagnosticsLogger_1<DbLoggerCategory$Database$Transaction>, transactionOwned: boolean): RelationalTransaction;
}


export const SqlServerTransactionFactory: {
    new(dependencies: RelationalTransactionFactoryDependencies): SqlServerTransactionFactory;
};


export type SqlServerTransactionFactory = SqlServerTransactionFactory$instance;

export interface SqlServerTypeMappingSource$instance extends RelationalTypeMappingSource {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerTypeMappingSource: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTypeMappingSource: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITypeMappingSource: never;

    FindCollectionMapping(info: RelationalTypeMappingInfo, modelType: Type, providerType: Type, elementMapping: CoreTypeMapping): RelationalTypeMapping | undefined;
    FindMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    ParseStoreTypeName(storeTypeName: string, unicode: Nullable_1<System_Internal.Boolean>, size: Nullable_1<System_Internal.Int32>, precision: Nullable_1<System_Internal.Int32>, scale: Nullable_1<System_Internal.Int32>): string | undefined;
}


export const SqlServerTypeMappingSource: {
    new(dependencies: TypeMappingSourceDependencies, relationalDependencies: RelationalTypeMappingSourceDependencies, sqlServerSingletonOptions: ISqlServerSingletonOptions): SqlServerTypeMappingSource;
};


export type SqlServerTypeMappingSource = SqlServerTypeMappingSource$instance;

export interface SqlServerUdtTypeMapping$instance extends RelationalTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerUdtTypeMapping: never;

    readonly LiteralGenerator: Func_2<unknown, Expression>;
    readonly UdtTypeName: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    ConfigureParameter(parameter: DbParameter): void;
    GenerateCodeLiteral(value: unknown): Expression;
}


export const SqlServerUdtTypeMapping: {
    new(clrType: Type, storeType: string, literalGenerator: Func_2<unknown, Expression>, storeTypePostfix: StoreTypePostfix, udtTypeName: string, converter: ValueConverter, comparer: ValueComparer, keyComparer: ValueComparer, dbType: Nullable_1<DbType>, unicode: boolean, size: Nullable_1<System_Internal.Int32>, fixedLength: boolean, precision: Nullable_1<System_Internal.Int32>, scale: Nullable_1<System_Internal.Int32>): SqlServerUdtTypeMapping;
};


export type SqlServerUdtTypeMapping = SqlServerUdtTypeMapping$instance;

export interface SqlServerVectorTypeMapping$instance extends RelationalTypeMapping {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Storage_Internal_SqlServerVectorTypeMapping: never;

    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqlServerVectorTypeMapping: {
    new(dimensions: Nullable_1<System_Internal.Int32>): SqlServerVectorTypeMapping;
    readonly Default: SqlServerVectorTypeMapping;
};


export type SqlServerVectorTypeMapping = SqlServerVectorTypeMapping$instance;

export abstract class SqlServerTransientExceptionDetector$instance {
    static ShouldRetryOn(ex: Exception): boolean;
}


export type SqlServerTransientExceptionDetector = SqlServerTransientExceptionDetector$instance;

