// Generated by tsbindgen - Architecture
// Namespace: Azure.Core
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Azure.Core/internal/index.js';

// Cross-namespace type imports for constraints
import type { HttpPipelinePolicy, HttpPipelineTransport } from './Azure.Core.Pipeline/internal/index.js';
import type { DynamicData, JsonPropertyNames, ObjectSerializer } from './Azure.Core.Serialization/internal/index.js';
import type { ETag, Response, ResponseError, SyncAsyncEventArgs } from './Azure/internal/index.js';
import type { AuthenticationToken, GetTokenOptions, IJsonModel_1, IPersistableModel_1, ModelReaderWriterContext, ModelReaderWriterOptions, ModelReaderWriterTypeBuilder } from './System.ClientModel.Primitives/internal/index.js';
import type { AuthenticationTokenProvider } from './System.ClientModel/internal/index.js';
import type { BinaryData } from './System/internal/index.js';
import type { ReadOnlySequence } from '@tsonic/dotnet/System.Buffers.js';
import type { IDictionary, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, IList, IReadOnlyDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { AsyncCallback, Boolean as ClrBoolean, Byte, Char, DateTimeOffset, Enum, Exception, Func, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IEquatable, IFormattable, Int32, Int64, IntPtr, ISpanFormattable, MulticastDelegate, Nullable, Object as ClrObject, ReadOnlyMemory, ReadOnlySpan, String as ClrString, TimeSpan, Type, UInt16, Uri, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Assembly } from '@tsonic/dotnet/System.Reflection.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { Utf8JsonReader, Utf8JsonWriter } from '@tsonic/dotnet/System.Text.Json.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AccessToken as AccessToken } from './Azure.Core/internal/index.js';
export { AzureCoreContext as AzureCoreContext } from './Azure.Core/internal/index.js';
export { AzureLocation as AzureLocation } from './Azure.Core/internal/index.js';
export { ClientOptions as ClientOptions } from './Azure.Core/internal/index.js';
export { ContentType as ContentType } from './Azure.Core/internal/index.js';
export { DelayStrategy as DelayStrategy } from './Azure.Core/internal/index.js';
export { DelegatedTokenCredential$instance as DelegatedTokenCredential } from './Azure.Core/internal/index.js';
export { DiagnosticsOptions as DiagnosticsOptions } from './Azure.Core/internal/index.js';
export { HttpHeader as HttpHeader } from './Azure.Core/internal/index.js';
export { HttpMessage as HttpMessage } from './Azure.Core/internal/index.js';
export { HttpPipelinePosition as HttpPipelinePosition } from './Azure.Core/internal/index.js';
export { MessageProcessingContext as MessageProcessingContext } from './Azure.Core/internal/index.js';
export { MultipartResponse$instance as MultipartResponse } from './Azure.Core/internal/index.js';
export { RequestFailedDetailsParser as RequestFailedDetailsParser } from './Azure.Core/internal/index.js';
export { RehydrationToken as RehydrationToken } from './Azure.Core/internal/index.js';
export { Request as Request } from './Azure.Core/internal/index.js';
export { RequestContent as RequestContent } from './Azure.Core/internal/index.js';
export { RequestHeaders as RequestHeaders } from './Azure.Core/internal/index.js';
export { RequestMethod as RequestMethod } from './Azure.Core/internal/index.js';
export { RequestUriBuilder as RequestUriBuilder } from './Azure.Core/internal/index.js';
export { ResourceIdentifier as ResourceIdentifier } from './Azure.Core/internal/index.js';
export { ResourceType as ResourceType } from './Azure.Core/internal/index.js';
export { ResponseClassificationHandler as ResponseClassificationHandler } from './Azure.Core/internal/index.js';
export { ResponseClassifier as ResponseClassifier } from './Azure.Core/internal/index.js';
export { ResponseHeaders as ResponseHeaders } from './Azure.Core/internal/index.js';
export { RetryMode as RetryMode } from './Azure.Core/internal/index.js';
export { RetryOptions as RetryOptions } from './Azure.Core/internal/index.js';
export { StatusCodeClassifier as StatusCodeClassifier } from './Azure.Core/internal/index.js';
export type SyncAsyncEventHandler<T extends Internal.SyncAsyncEventArgs> = Internal.SyncAsyncEventHandler_1<T>;
export { TelemetryDetails as TelemetryDetails } from './Azure.Core/internal/index.js';
export { TokenCredential as TokenCredential } from './Azure.Core/internal/index.js';
export { TokenRequestContext as TokenRequestContext } from './Azure.Core/internal/index.js';
export { HttpHeader_Names$instance as HttpHeader_Names } from './Azure.Core/internal/index.js';
export { HttpHeader_Common$instance as HttpHeader_Common } from './Azure.Core/internal/index.js';
