// Generated by tsbindgen - Architecture
// Namespace: Azure.Core.Pipeline
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Azure.Core.Pipeline/internal/index.js';

// Cross-namespace type imports for constraints
import type { ClientOptions, DelayStrategy, HttpMessage, Request, RequestFailedDetailsParser, ResponseClassifier, TokenCredential } from './Azure.Core/internal/index.js';
import type { RequestContext, Response } from './Azure/internal/index.js';
import type { IDictionary, IEnumerable, IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Func, IDisposable, Int32, Object as ClrObject, ReadOnlyMemory, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { HttpClient, HttpMessageHandler } from '@tsonic/dotnet/System.Net.Http.js';
import type { SslPolicyErrors } from '@tsonic/dotnet/System.Net.Security.js';
import type { X509Certificate2, X509Chain } from '@tsonic/dotnet/System.Security.Cryptography.X509Certificates.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { BearerTokenAuthenticationPolicy as BearerTokenAuthenticationPolicy } from './Azure.Core.Pipeline/internal/index.js';
export { DisposableHttpPipeline as DisposableHttpPipeline } from './Azure.Core.Pipeline/internal/index.js';
export { HttpClientTransport as HttpClientTransport } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipeline as HttpPipeline } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelineBuilder$instance as HttpPipelineBuilder } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelineOptions as HttpPipelineOptions } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelinePolicy as HttpPipelinePolicy } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelineSynchronousPolicy as HttpPipelineSynchronousPolicy } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelineTransport as HttpPipelineTransport } from './Azure.Core.Pipeline/internal/index.js';
export { HttpPipelineTransportOptions as HttpPipelineTransportOptions } from './Azure.Core.Pipeline/internal/index.js';
export { RedirectPolicy as RedirectPolicy } from './Azure.Core.Pipeline/internal/index.js';
export { RetryPolicy as RetryPolicy } from './Azure.Core.Pipeline/internal/index.js';
export { ServerCertificateCustomValidationArgs as ServerCertificateCustomValidationArgs } from './Azure.Core.Pipeline/internal/index.js';
