// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Abstractions
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.IdentityModel.Abstractions/internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary, IReadOnlyDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, DateTime, Double, Enum, Guid, IComparable, IConvertible, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { EventLogLevel as EventLogLevel } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
export type IIdentityLogger = Internal.IIdentityLogger;
export type ITelemetryClient = Internal.ITelemetryClient;
export { LogEntry as LogEntry } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
export { NullIdentityModelLogger as NullIdentityModelLogger } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
export { NullTelemetryClient as NullTelemetryClient } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
export { ObservabilityConstants$instance as ObservabilityConstants } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
export { TelemetryEventDetails as TelemetryEventDetails } from './Microsoft.IdentityModel.Abstractions/internal/index.js';
