// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Identity.Client.AuthScheme
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Identity.Client.AuthScheme/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { AuthenticationResult } from './Microsoft.Identity.Client/internal/index.js';
import type { IReadOnlyDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Int32, String as ClrString, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type IAuthenticationOperation = Internal.IAuthenticationOperation;
