// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ISqlServerConnection } from './Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal/internal/index.js';
import type { ISqlServerUpdateSqlGenerator } from './Microsoft.EntityFrameworkCore.SqlServer.Update.Internal/internal/index.js';
import type { Boolean as ClrBoolean, IDisposable, Int64, Object as ClrObject, Type } from '@tsonic/dotnet/System.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { IRelationalCommandDiagnosticsLogger } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js';
import type { IProperty, ISequence, ITypeBase } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';
import type { IRawSqlCommandBuilder, IRelationalConnection } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js';
import type { HiLoValueGenerator, HiLoValueGeneratorState, IValueGeneratorCache, IValueGeneratorSelector, RelationalValueGeneratorSelector, ValueGenerator, ValueGeneratorCache, ValueGeneratorCacheDependencies, ValueGeneratorSelectorDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.ValueGeneration.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type ISqlServerSequenceValueGeneratorFactory = Internal.ISqlServerSequenceValueGeneratorFactory;
export type ISqlServerValueGeneratorCache = Internal.ISqlServerValueGeneratorCache;
export { SqlServerSequenceHiLoValueGenerator_1 as SqlServerSequenceHiLoValueGenerator } from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';
export { SqlServerSequenceValueGeneratorFactory as SqlServerSequenceValueGeneratorFactory } from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';
export { SqlServerSequenceValueGeneratorState as SqlServerSequenceValueGeneratorState } from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';
export { SqlServerValueGeneratorCache as SqlServerValueGeneratorCache } from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';
export { SqlServerValueGeneratorSelector as SqlServerValueGeneratorSelector } from './Microsoft.EntityFrameworkCore.SqlServer.ValueGeneration.Internal/internal/index.js';
