// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.Cache
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Identity.Client.Cache/internal/index.js';

// Cross-namespace type imports for constraints
import type { Byte, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CacheData as CacheData } from './Microsoft.Identity.Client.Cache/internal/index.js';
export { CacheLevel as CacheLevel } from './Microsoft.Identity.Client.Cache/internal/index.js';
