// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.ManagedIdentity
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Identity.Client.ManagedIdentity/internal/index.js';

// Cross-namespace type imports for constraints
import type { Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ManagedIdentitySource as ManagedIdentitySource } from './Microsoft.Identity.Client.ManagedIdentity/internal/index.js';
