// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.SqlClient.DataClassification
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';

// Cross-namespace type imports for constraints
import type { IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { ReadOnlyCollection } from '@tsonic/dotnet/System.Collections.ObjectModel.js';
import type { Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ColumnSensitivity as ColumnSensitivity } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
export { InformationType as InformationType } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
export { Label as Label } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
export { SensitivityClassification as SensitivityClassification } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
export { SensitivityProperty as SensitivityProperty } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
export { SensitivityRank as SensitivityRank } from './Microsoft.Data.SqlClient.DataClassification/internal/index.js';
