// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Diagnostics
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js';

// Cross-namespace type imports for constraints
import type { SqlServerValueGenerationStrategy } from './Microsoft.EntityFrameworkCore.Metadata/internal/index.js';
import type { Func, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { EventData, EventDefinitionBase } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js';
import type { IReadOnlyProperty } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';
import type { EventId } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ConflictingValueGenerationStrategiesEventData as ConflictingValueGenerationStrategiesEventData } from './Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js';
export { SqlServerEventId$instance as SqlServerEventId } from './Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js';
