// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.Sql
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Data.Sql/internal/index.js';

// Cross-namespace type imports for constraints
import type { DbDataSourceEnumerator } from '@tsonic/dotnet/System.Data.Common.js';
import type { DataTable } from '@tsonic/dotnet/System.Data.js';
import type { Int32, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlDataSourceEnumerator as SqlDataSourceEnumerator } from './Microsoft.Data.Sql/internal/index.js';
export { SqlNotificationRequest as SqlNotificationRequest } from './Microsoft.Data.Sql/internal/index.js';
