// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.Advanced
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Identity.Client.Advanced/internal/index.js';

// Cross-namespace type imports for constraints
import type { AbstractAcquireTokenParameterBuilder_1 } from './Microsoft.Identity.Client/internal/index.js';
import type { IDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AcquireTokenParameterBuilderExtensions$instance as AcquireTokenParameterBuilderExtensions } from './Microsoft.Identity.Client.Advanced/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_Identity_Client_Advanced as ExtensionMethods } from './__internal/extensions/index.js';

