// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { IAnnotation } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { IColumn, IRelationalAnnotationProvider, IRelationalModel, ITable, ITableIndex, IUniqueConstraint, RelationalAnnotationProvider, RelationalAnnotationProviderDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlServerAnnotationNames$instance as SqlServerAnnotationNames } from './Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal/internal/index.js';
export { SqlServerAnnotationProvider as SqlServerAnnotationProvider } from './Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal/internal/index.js';
