// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Tokens.Configuration
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.IdentityModel.Tokens.Configuration/internal/index.js';

// Cross-namespace type imports for constraints
import type { BaseConfiguration } from './Microsoft.IdentityModel.Tokens/internal/index.js';
import type { IEqualityComparer } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Int32, Object as ClrObject } from '@tsonic/dotnet/System.js';
import type { TaskCreationOptions } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { LKGConfigurationCacheOptions as LKGConfigurationCacheOptions } from './Microsoft.IdentityModel.Tokens.Configuration/internal/index.js';
