// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Migrations
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Migrations/internal/index.js';

// Cross-namespace type imports for constraints
import type { IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Object as ClrObject } from '@tsonic/dotnet/System.js';
import type { IModel } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';
import type { IMigrationsSqlGenerator, MigrationBuilder, MigrationCommand, MigrationsSqlGenerationOptions, MigrationsSqlGenerator, MigrationsSqlGeneratorDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js';
import type { MigrationOperation } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.Operations.js';
import type { ICommandBatchPreparer } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlServerMigrationBuilderExtensions$instance as SqlServerMigrationBuilderExtensions } from './Microsoft.EntityFrameworkCore.Migrations/internal/index.js';
export { SqlServerMigrationsSqlGenerator as SqlServerMigrationsSqlGenerator } from './Microsoft.EntityFrameworkCore.Migrations/internal/index.js';
