// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.DependencyInjection
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.DependencyInjection/internal/index.js';

// Cross-namespace type imports for constraints
import type { AzureSqlDbContextOptionsBuilder, AzureSynapseDbContextOptionsBuilder, SqlServerDbContextOptionsBuilder } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
import type { Action, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { DbContext, DbContextOptionsBuilder } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.js';
import type { IServiceCollection } from '@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlServerServiceCollectionExtensions$instance as SqlServerServiceCollectionExtensions } from './Microsoft.Extensions.DependencyInjection/internal/index.js';
