// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, IAsyncDisposable, IDisposable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { IAnnotation } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { IColumn, IRelationalModel, ITable } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';
import type { HistoryRepository, HistoryRepositoryDependencies, IHistoryRepository, IMigrationsAnnotationProvider, IMigrationsDatabaseLock, LockReleaseBehavior, MigrationsAnnotationProvider, MigrationsAnnotationProviderDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js';
import type { IRelationalCommand, RelationalCommandParameterObject } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlServerHistoryRepository as SqlServerHistoryRepository } from './Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal/internal/index.js';
export { SqlServerMigrationDatabaseLock as SqlServerMigrationDatabaseLock } from './Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal/internal/index.js';
export { SqlServerMigrationsAnnotationProvider as SqlServerMigrationsAnnotationProvider } from './Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal/internal/index.js';
