// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';

// Cross-namespace type imports for constraints
import type { AuthenticationProtocolMessage, IConfigurationRetriever_1, IDocumentRetriever } from './Microsoft.IdentityModel.Protocols/internal/index.js';
import type { BaseConfiguration, CryptoProviderFactory, JsonWebKeySet, SecurityKey } from './Microsoft.IdentityModel.Tokens/internal/index.js';
import type { JwtSecurityToken } from './System.IdentityModel.Tokens.Jwt/internal/index.js';
import type { ICollection, IDictionary, IEnumerable, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { NameValueCollection } from '@tsonic/dotnet/System.Collections.Specialized.js';
import type { AsyncCallback, Boolean as ClrBoolean, Enum, Exception, IAsyncResult, ICloneable, IComparable, IConvertible, IFormattable, Int32, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, String as ClrString, TimeSpan, Void } from '@tsonic/dotnet/System.js';
import type { HttpClient } from '@tsonic/dotnet/System.Net.Http.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { HashAlgorithm } from '@tsonic/dotnet/System.Security.Cryptography.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ActiveDirectoryOpenIdConnectEndpoints$instance as ActiveDirectoryOpenIdConnectEndpoints } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectConfiguration as OpenIdConnectConfiguration } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectConfigurationRetriever as OpenIdConnectConfigurationRetriever } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolException as OpenIdConnectProtocolException } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolInvalidAtHashException as OpenIdConnectProtocolInvalidAtHashException } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolInvalidCHashException as OpenIdConnectProtocolInvalidCHashException } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolInvalidNonceException as OpenIdConnectProtocolInvalidNonceException } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolInvalidStateException as OpenIdConnectProtocolInvalidStateException } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectGrantTypes$instance as OpenIdConnectGrantTypes } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectMessage as OpenIdConnectMessage } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectParameterNames$instance as OpenIdConnectParameterNames } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectPrompt$instance as OpenIdConnectPrompt } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectProtocolValidationContext as OpenIdConnectProtocolValidationContext } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export type IdTokenValidator = Internal.IdTokenValidator;
export { OpenIdConnectProtocolValidator as OpenIdConnectProtocolValidator } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectRequestType as OpenIdConnectRequestType } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectResponseMode$instance as OpenIdConnectResponseMode } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectResponseType$instance as OpenIdConnectResponseType } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectScope$instance as OpenIdConnectScope } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdConnectSessionProperties$instance as OpenIdConnectSessionProperties } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
export { OpenIdProviderMetadataNames$instance as OpenIdProviderMetadataNames } from './Microsoft.IdentityModel.Protocols.OpenIdConnect/internal/index.js';
