// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.Utils.Windows
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace Microsoft.Identity.Client.Utils.Windows in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
