// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Identity.Client.Utils
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Identity.Client.Utils/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { Boolean as ClrBoolean, Func, Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { MacMainThreadScheduler as MacMainThreadScheduler } from './Microsoft.Identity.Client.Utils/internal/index.js';
