// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Design.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.SqlServer.Design.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary, IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { CSharpRuntimeAnnotationCodeGeneratorDependencies, CSharpRuntimeAnnotationCodeGeneratorParameters, RelationalCSharpRuntimeAnnotationCodeGenerator, RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.Internal.js';
import type { AnnotationCodeGenerator, AnnotationCodeGeneratorDependencies, IAnnotationCodeGenerator, IDesignTimeServices, MethodCallCodeFragment } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.js';
import type { IAnnotation } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { IColumn, IEntityType, IIndex, IKey, IModel, IProperty, IRelationalModel, IRelationalPropertyOverrides, ITable, ITableIndex, IUniqueConstraint } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';
import type { IServiceCollection } from '@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqlServerAnnotationCodeGenerator as SqlServerAnnotationCodeGenerator } from './Microsoft.EntityFrameworkCore.SqlServer.Design.Internal/internal/index.js';
export { SqlServerCSharpRuntimeAnnotationCodeGenerator as SqlServerCSharpRuntimeAnnotationCodeGenerator } from './Microsoft.EntityFrameworkCore.SqlServer.Design.Internal/internal/index.js';
export { SqlServerDesignTimeServices as SqlServerDesignTimeServices } from './Microsoft.EntityFrameworkCore.SqlServer.Design.Internal/internal/index.js';
