// Generated by tsbindgen - Architecture
// Namespace: Microsoft.SqlServer.Server
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace Microsoft.SqlServer.Server in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
