// Generated by tsbindgen - Architecture
// Namespace: System
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System/internal/index.js';

// Cross-namespace type imports for constraints
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, Byte, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, ReadOnlyMemory, String as ClrString, Type } from '@tsonic/dotnet/System.js';
import type { JsonSerializerOptions } from '@tsonic/dotnet/System.Text.Json.js';
import type { JsonSerializerContext } from '@tsonic/dotnet/System.Text.Json.Serialization.js';
import type { JsonTypeInfo } from '@tsonic/dotnet/System.Text.Json.Serialization.Metadata.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { UriIdnScope as UriIdnScope } from './System/internal/index.js';
export { BinaryData as BinaryData } from './System/internal/index.js';

// Primitive $instance interfaces for global type augmentation (@tsonic/globals)
