// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { SqlVector_1 } from "../../Microsoft.Data.SqlTypes/internal/index.js";
import type { AzureSqlDbContextOptionsBuilder, AzureSynapseDbContextOptionsBuilder, SqlEngineDbContextOptionsBuilder, SqlServerDbContextOptionsBuilder } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { OwnedNavigationTemporalTableBuilder, OwnedNavigationTemporalTableBuilder_2, TemporalTableBuilder, TemporalTableBuilder_1 } from "../../Microsoft.EntityFrameworkCore.Metadata.Builders/internal/index.js";
import type { SqlServerValueGenerationStrategy } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IEnumerable, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, Byte, DateOnly, DateTime, DateTimeOffset, Decimal, Double, Enum, Exception, Func, Guid, IComparable, IConvertible, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable, Object as ClrObject, Single, String as ClrString, TimeOnly, TimeSpan, ValueType, Void } from "@tsonic/dotnet/System.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { IQueryable } from "@tsonic/dotnet/System.Linq.js";
import type { DatabaseFacade } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbContext, DbContextOptionsBuilder, DbFunctions, DbSet, ModelBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { ColumnBuilder, ComplexTypePrimitiveCollectionBuilder, ComplexTypePropertyBuilder, EntityTypeBuilder, IConventionEntityTypeBuilder, IConventionIndexBuilder, IConventionKeyBuilder, IConventionModelBuilder, IConventionPropertyBuilder, IConventionSequenceBuilder, IndexBuilder, KeyBuilder, OwnedNavigationBuilder, OwnedNavigationTableBuilder, PrimitiveCollectionBuilder, PropertyBuilder, SplitTableBuilder, TableBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Builders.js";
import type { ConfigurationSource, IConventionEntityType, IConventionEntityTypeMappingFragment, IConventionIndex, IConventionKey, IConventionModel, IConventionProperty, IConventionRelationalPropertyOverrides, IMutableEntityType, IMutableEntityTypeMappingFragment, IMutableIndex, IMutableKey, IMutableModel, IMutableProperty, IMutableRelationalPropertyOverrides, IProperty, IReadOnlyEntityType, IReadOnlyEntityTypeMappingFragment, IReadOnlyIndex, IReadOnlyKey, IReadOnlyModel, IReadOnlyProperty, IReadOnlyRelationalPropertyOverrides, IReadOnlySequence, ISequence, ITable, StoreObjectIdentifier } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import type { ExecutionStrategy, ExecutionStrategyDependencies, IExecutionStrategy } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export enum DataCompressionType {
    None = 0,
    Row = 1,
    Page = 2
}


export interface SqlServerRetryingExecutionStrategy$instance extends ExecutionStrategy {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExecutionStrategy: never;

    readonly AdditionalErrorNumbers: IEnumerable<System_Internal.Int32> | undefined;
    GetNextDelay(lastException: Exception): Nullable<TimeSpan>;
    ShouldRetryOn(exception: Exception): boolean;
}


export const SqlServerRetryingExecutionStrategy: {
    new(context: DbContext): SqlServerRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies): SqlServerRetryingExecutionStrategy;
    new(context: DbContext, maxRetryCount: int): SqlServerRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, maxRetryCount: int): SqlServerRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): SqlServerRetryingExecutionStrategy;
    new(context: DbContext, maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): SqlServerRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): SqlServerRetryingExecutionStrategy;
    readonly DefaultMinDelayThrottling: TimeSpan;
};


export type SqlServerRetryingExecutionStrategy = SqlServerRetryingExecutionStrategy$instance;

export abstract class SqlServerComplexTypePrimitiveCollectionBuilderExtensions$instance {
    static HasDefaultValue<TProperty>(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder<TProperty>, value: unknown, defaultConstraintName: string): ComplexTypePrimitiveCollectionBuilder<TProperty>;
    static HasDefaultValue(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder, value: unknown, defaultConstraintName: string): ComplexTypePrimitiveCollectionBuilder;
    static HasDefaultValueSql<TProperty>(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder<TProperty>, sql: string, defaultConstraintName: string): ComplexTypePrimitiveCollectionBuilder<TProperty>;
    static HasDefaultValueSql(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder, sql: string, defaultConstraintName: string): ComplexTypePrimitiveCollectionBuilder;
    static IsSparse<TProperty>(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder<TProperty>, sparse?: boolean): ComplexTypePrimitiveCollectionBuilder<TProperty>;
    static IsSparse(primitiveCollectionBuilder: ComplexTypePrimitiveCollectionBuilder, sparse?: boolean): ComplexTypePrimitiveCollectionBuilder;
}


export type SqlServerComplexTypePrimitiveCollectionBuilderExtensions = SqlServerComplexTypePrimitiveCollectionBuilderExtensions$instance;

export abstract class SqlServerComplexTypePropertyBuilderExtensions$instance {
    static HasDefaultValue<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, value: unknown, defaultConstraintName: string): ComplexTypePropertyBuilder<TProperty>;
    static HasDefaultValue(propertyBuilder: ComplexTypePropertyBuilder, value: unknown, defaultConstraintName: string): ComplexTypePropertyBuilder;
    static HasDefaultValueSql<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, sql: string, defaultConstraintName: string): ComplexTypePropertyBuilder<TProperty>;
    static HasDefaultValueSql(propertyBuilder: ComplexTypePropertyBuilder, sql: string, defaultConstraintName: string): ComplexTypePropertyBuilder;
    static IsSparse<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, sparse?: boolean): ComplexTypePropertyBuilder<TProperty>;
    static IsSparse(propertyBuilder: ComplexTypePropertyBuilder, sparse?: boolean): ComplexTypePropertyBuilder;
    static UseHiLo<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, name?: string, schema?: string): ComplexTypePropertyBuilder<TProperty>;
    static UseHiLo(propertyBuilder: ComplexTypePropertyBuilder, name?: string, schema?: string): ComplexTypePropertyBuilder;
    static UseIdentityColumn<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, seed: int, increment?: int): ComplexTypePropertyBuilder<TProperty>;
    static UseIdentityColumn<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, seed?: long, increment?: int): ComplexTypePropertyBuilder<TProperty>;
    static UseIdentityColumn(propertyBuilder: ComplexTypePropertyBuilder, seed: int, increment?: int): ComplexTypePropertyBuilder;
    static UseIdentityColumn(propertyBuilder: ComplexTypePropertyBuilder, seed?: long, increment?: int): ComplexTypePropertyBuilder;
    static UseSequence<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, name?: string, schema?: string): ComplexTypePropertyBuilder<TProperty>;
    static UseSequence(propertyBuilder: ComplexTypePropertyBuilder, name?: string, schema?: string): ComplexTypePropertyBuilder;
}


export type SqlServerComplexTypePropertyBuilderExtensions = SqlServerComplexTypePropertyBuilderExtensions$instance;

export abstract class SqlServerDatabaseFacadeExtensions$instance {
    static IsSqlServer(database: DatabaseFacade): boolean;
}


export type SqlServerDatabaseFacadeExtensions = SqlServerDatabaseFacadeExtensions$instance;

export abstract class SqlServerDbContextOptionsExtensions$instance {
    static ConfigureSqlEngine<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, sqlEngineOptionsAction?: Action<SqlEngineDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static ConfigureSqlEngine(optionsBuilder: DbContextOptionsBuilder, sqlEngineOptionsAction?: Action<SqlEngineDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSql<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSql<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSql<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, contextOwnsConnection: boolean, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSql<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connectionString: string, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSql(optionsBuilder: DbContextOptionsBuilder, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSql(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSql(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, contextOwnsConnection: boolean, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSql(optionsBuilder: DbContextOptionsBuilder, connectionString: string, azureSqlOptionsAction?: Action<AzureSqlDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSynapse<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSynapse<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSynapse<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, contextOwnsConnection: boolean, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSynapse<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connectionString: string, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseAzureSynapse(optionsBuilder: DbContextOptionsBuilder, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSynapse(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSynapse(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, contextOwnsConnection: boolean, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseAzureSynapse(optionsBuilder: DbContextOptionsBuilder, connectionString: string, azureSynapseOptionsAction?: Action<AzureSynapseDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseSqlServer<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseSqlServer<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseSqlServer<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, contextOwnsConnection: boolean, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseSqlServer<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connectionString: string, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static UseSqlServer(optionsBuilder: DbContextOptionsBuilder, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseSqlServer(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseSqlServer(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, contextOwnsConnection: boolean, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static UseSqlServer(optionsBuilder: DbContextOptionsBuilder, connectionString: string, sqlServerOptionsAction?: Action<SqlServerDbContextOptionsBuilder>): DbContextOptionsBuilder;
}


export type SqlServerDbContextOptionsExtensions = SqlServerDbContextOptionsExtensions$instance;

export abstract class SqlServerDbFunctionsExtensions$instance {
    static AtTimeZone(_: DbFunctions, dateTime: DateTime, timeZone: string): DateTimeOffset;
    static AtTimeZone(_: DbFunctions, dateTimeOffset: DateTimeOffset, timeZone: string): DateTimeOffset;
    static Contains(_: DbFunctions, propertyReference: unknown, searchCondition: string, languageTerm: int): boolean;
    static Contains(_: DbFunctions, propertyReference: unknown, searchCondition: string): boolean;
    static DataLength(_: DbFunctions, arg: byte[]): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<System_Internal.Boolean>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<System_Internal.Decimal>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<System_Internal.Double>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<Guid>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DataLength(_: DbFunctions, arg: string): Nullable<System_Internal.Int32>;
    static DateDiffDay(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffDay(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffDay(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffDay(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffDay(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffDay(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffHour(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffHour(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffHour(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffHour(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffHour(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffMicrosecond(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffMicrosecond(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffMicrosecond(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffMicrosecond(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMicrosecond(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffMicrosecond(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffMicrosecond(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMicrosecond(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffMicrosecond(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffMicrosecond(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffMillisecond(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffMillisecond(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffMillisecond(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffMillisecond(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMillisecond(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffMillisecond(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffMillisecond(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMillisecond(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffMillisecond(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffMillisecond(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffMinute(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffMinute(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffMinute(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffMinute(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMinute(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffMinute(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffMinute(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMinute(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffMinute(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffMinute(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffMonth(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffMonth(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffMonth(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffMonth(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffMonth(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffMonth(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffNanosecond(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffNanosecond(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffNanosecond(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffNanosecond(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffNanosecond(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffSecond(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffSecond(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffSecond(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffSecond(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffSecond(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffSecond(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffSecond(_: DbFunctions, startTime: Nullable<TimeOnly>, endTime: Nullable<TimeOnly>): Nullable<System_Internal.Int32>;
    static DateDiffSecond(_: DbFunctions, startTimeSpan: Nullable<TimeSpan>, endTimeSpan: Nullable<TimeSpan>): Nullable<System_Internal.Int32>;
    static DateDiffSecond(_: DbFunctions, startTime: TimeOnly, endTime: TimeOnly): int;
    static DateDiffSecond(_: DbFunctions, startTimeSpan: TimeSpan, endTimeSpan: TimeSpan): int;
    static DateDiffWeek(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffWeek(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffWeek(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffWeek(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffWeek(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffWeek(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateDiffYear(_: DbFunctions, startDate: DateOnly, endDate: DateOnly): int;
    static DateDiffYear(_: DbFunctions, startDate: DateTime, endDate: DateTime): int;
    static DateDiffYear(_: DbFunctions, startDate: DateTimeOffset, endDate: DateTimeOffset): int;
    static DateDiffYear(_: DbFunctions, startDate: Nullable<DateOnly>, endDate: Nullable<DateOnly>): Nullable<System_Internal.Int32>;
    static DateDiffYear(_: DbFunctions, startDate: Nullable<DateTime>, endDate: Nullable<DateTime>): Nullable<System_Internal.Int32>;
    static DateDiffYear(_: DbFunctions, startDate: Nullable<DateTimeOffset>, endDate: Nullable<DateTimeOffset>): Nullable<System_Internal.Int32>;
    static DateFromParts(_: DbFunctions, year: int, month: int, day: int): DateTime;
    static DateTime2FromParts(_: DbFunctions, year: int, month: int, day: int, hour: int, minute: int, second: int, fractions: int, precision: int): DateTime;
    static DateTimeFromParts(_: DbFunctions, year: int, month: int, day: int, hour: int, minute: int, second: int, millisecond: int): DateTime;
    static DateTimeOffsetFromParts(_: DbFunctions, year: int, month: int, day: int, hour: int, minute: int, second: int, fractions: int, hourOffset: int, minuteOffset: int, precision: int): DateTimeOffset;
    static FreeText(_: DbFunctions, propertyReference: unknown, freeText: string, languageTerm: int): boolean;
    static FreeText(_: DbFunctions, propertyReference: unknown, freeText: string): boolean;
    static IsDate(_: DbFunctions, expression: string): boolean;
    static IsNumeric(_: DbFunctions, expression: string): boolean;
    static PatIndex(_: DbFunctions, pattern: string, expression: string): long;
    static SmallDateTimeFromParts(_: DbFunctions, year: int, month: int, day: int, hour: int, minute: int): DateTime;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Byte>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Decimal>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Double>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int16>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int32>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int64>): Nullable<System_Internal.Double>;
    static StandardDeviationPopulation(_: DbFunctions, values: IEnumerable<System_Internal.Single>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Byte>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Decimal>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Double>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Int16>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Int32>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Int64>): Nullable<System_Internal.Double>;
    static StandardDeviationSample(_: DbFunctions, values: IEnumerable<System_Internal.Single>): Nullable<System_Internal.Double>;
    static TimeFromParts(_: DbFunctions, hour: int, minute: int, second: int, fractions: int, precision: int): TimeSpan;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Byte>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Decimal>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Double>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int16>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int32>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Int64>): Nullable<System_Internal.Double>;
    static VariancePopulation(_: DbFunctions, values: IEnumerable<System_Internal.Single>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Byte>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Decimal>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Double>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Int16>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Int32>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Int64>): Nullable<System_Internal.Double>;
    static VarianceSample(_: DbFunctions, values: IEnumerable<System_Internal.Single>): Nullable<System_Internal.Double>;
    static VectorDistance<T extends unknown>(_: DbFunctions, distanceMetric: string, vector1: SqlVector_1<T>, vector2: SqlVector_1<T>): double;
}


export type SqlServerDbFunctionsExtensions = SqlServerDbFunctionsExtensions$instance;

export abstract class SqlServerDbSetExtensions$instance {
    static TemporalAll<TEntity>(source: DbSet<TEntity>): IQueryable<TEntity>;
    static TemporalAsOf<TEntity>(source: DbSet<TEntity>, utcPointInTime: DateTime): IQueryable<TEntity>;
    static TemporalBetween<TEntity>(source: DbSet<TEntity>, utcFrom: DateTime, utcTo: DateTime): IQueryable<TEntity>;
    static TemporalContainedIn<TEntity>(source: DbSet<TEntity>, utcFrom: DateTime, utcTo: DateTime): IQueryable<TEntity>;
    static TemporalFromTo<TEntity>(source: DbSet<TEntity>, utcFrom: DateTime, utcTo: DateTime): IQueryable<TEntity>;
}


export type SqlServerDbSetExtensions = SqlServerDbSetExtensions$instance;

export abstract class SqlServerEntityTypeBuilderExtensions$instance {
    static CanSetHistoryTableName(entityTypeBuilder: IConventionEntityTypeBuilder, name: string, fromDataAnnotation?: boolean): boolean;
    static CanSetHistoryTableSchema(entityTypeBuilder: IConventionEntityTypeBuilder, schema: string, fromDataAnnotation?: boolean): boolean;
    static CanSetIsMemoryOptimized(entityTypeBuilder: IConventionEntityTypeBuilder, memoryOptimized: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static CanSetIsTemporal(entityTypeBuilder: IConventionEntityTypeBuilder, temporal?: boolean, fromDataAnnotation?: boolean): boolean;
    static CanSetPeriodEnd(entityTypeBuilder: IConventionEntityTypeBuilder, propertyName: string, fromDataAnnotation?: boolean): boolean;
    static CanSetPeriodStart(entityTypeBuilder: IConventionEntityTypeBuilder, propertyName: string, fromDataAnnotation?: boolean): boolean;
    static CanUseSqlOutputClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlOutputClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): boolean;
    static CanUseSqlOutputClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlOutputClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static HasPeriodEnd(entityTypeBuilder: IConventionEntityTypeBuilder, propertyName: string, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static HasPeriodStart(entityTypeBuilder: IConventionEntityTypeBuilder, propertyName: string, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static IsMemoryOptimized<TEntity>(entityTypeBuilder: EntityTypeBuilder<TEntity>, memoryOptimized?: boolean): EntityTypeBuilder<TEntity>;
    static IsMemoryOptimized(entityTypeBuilder: EntityTypeBuilder, memoryOptimized?: boolean): EntityTypeBuilder;
    static IsMemoryOptimized(entityTypeBuilder: IConventionEntityTypeBuilder, memoryOptimized: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static IsMemoryOptimized(collectionOwnershipBuilder: OwnedNavigationBuilder, memoryOptimized?: boolean): OwnedNavigationBuilder;
    static IsMemoryOptimized<TEntity, TRelatedEntity>(collectionOwnershipBuilder: OwnedNavigationBuilder<TEntity, TRelatedEntity>, memoryOptimized?: boolean): OwnedNavigationBuilder<TEntity, TRelatedEntity>;
    static IsTemporal(entityTypeBuilder: IConventionEntityTypeBuilder, temporal?: boolean, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static UseHistoryTableName(entityTypeBuilder: IConventionEntityTypeBuilder, name: string, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static UseHistoryTableSchema(entityTypeBuilder: IConventionEntityTypeBuilder, schema: string, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static UseSqlOutputClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlOutputClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static UseSqlOutputClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlOutputClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
}


export type SqlServerEntityTypeBuilderExtensions = SqlServerEntityTypeBuilderExtensions$instance;

export abstract class SqlServerEntityTypeExtensions$instance {
    static GetHistoryTableName(entityType: IReadOnlyEntityType): string | undefined;
    static GetHistoryTableNameConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetHistoryTableSchema(entityType: IReadOnlyEntityType): string | undefined;
    static GetHistoryTableSchemaConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetIsMemoryOptimizedConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetIsTemporalConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetPeriodEndPropertyName(entityType: IReadOnlyEntityType): string | undefined;
    static GetPeriodEndPropertyNameConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetPeriodStartPropertyName(entityType: IReadOnlyEntityType): string | undefined;
    static GetPeriodStartPropertyNameConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static GetSchemaQualifiedHistoryTableName(entityType: IReadOnlyEntityType): string | undefined;
    static GetUseSqlOutputClauseConfigurationSource(entityType: IConventionEntityType, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static GetUseSqlOutputClauseConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static IsMemoryOptimized(entityType: IReadOnlyEntityType): boolean;
    static IsSqlOutputClauseUsed(entityType: IReadOnlyEntityType, storeObject: StoreObjectIdentifier): boolean;
    static IsSqlOutputClauseUsed(entityType: IReadOnlyEntityType): boolean;
    static IsTemporal(entityType: IReadOnlyEntityType): boolean;
    static SetHistoryTableName(entityType: IConventionEntityType, historyTableName: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHistoryTableName(entityType: IMutableEntityType, historyTableName: string): void;
    static SetHistoryTableSchema(entityType: IConventionEntityType, historyTableSchema: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHistoryTableSchema(entityType: IMutableEntityType, historyTableSchema: string): void;
    static SetIsMemoryOptimized(entityType: IConventionEntityType, memoryOptimized: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsMemoryOptimized(entityType: IMutableEntityType, memoryOptimized: boolean): void;
    static SetIsTemporal(entityType: IConventionEntityType, temporal: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsTemporal(entityType: IMutableEntityType, temporal: boolean): void;
    static SetPeriodEndPropertyName(entityType: IConventionEntityType, periodEndPropertyName: string, fromDataAnnotation?: boolean): string | undefined;
    static SetPeriodEndPropertyName(entityType: IMutableEntityType, periodEndPropertyName: string): void;
    static SetPeriodStartPropertyName(entityType: IConventionEntityType, periodStartPropertyName: string, fromDataAnnotation?: boolean): string | undefined;
    static SetPeriodStartPropertyName(entityType: IMutableEntityType, periodStartPropertyName: string): void;
    static UseSqlOutputClause(entityType: IConventionEntityType, useSqlOutputClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static UseSqlOutputClause(entityType: IConventionEntityType, useSqlOutputClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static UseSqlOutputClause(entityType: IMutableEntityType, useSqlOutputClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier): void;
    static UseSqlOutputClause(entityType: IMutableEntityType, useSqlOutputClause: Nullable<System_Internal.Boolean>): void;
}


export type SqlServerEntityTypeExtensions = SqlServerEntityTypeExtensions$instance;

export abstract class SqlServerEntityTypeMappingFragmentExtensions$instance {
    static GetUseSqlOutputClauseConfigurationSource(fragment: IConventionEntityTypeMappingFragment): Nullable<ConfigurationSource>;
    static IsSqlOutputClauseUsed(fragment: IReadOnlyEntityTypeMappingFragment): boolean;
    static UseSqlOutputClause(fragment: IConventionEntityTypeMappingFragment, useSqlOutputClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static UseSqlOutputClause(fragment: IMutableEntityTypeMappingFragment, useSqlOutputClause: Nullable<System_Internal.Boolean>): void;
}


export type SqlServerEntityTypeMappingFragmentExtensions = SqlServerEntityTypeMappingFragmentExtensions$instance;

export abstract class SqlServerIndexBuilderExtensions$instance {
    static CanSetDataCompression(indexBuilder: IConventionIndexBuilder, dataCompressionType: Nullable<DataCompressionType>, fromDataAnnotation?: boolean): boolean;
    static CanSetFillFactor(indexBuilder: IConventionIndexBuilder, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): boolean;
    static CanSetIncludeProperties(indexBuilder: IConventionIndexBuilder, propertyNames: IReadOnlyList<System_Internal.String>, fromDataAnnotation?: boolean): boolean;
    static CanSetIsClustered(indexBuilder: IConventionIndexBuilder, clustered: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static CanSetIsCreatedOnline(indexBuilder: IConventionIndexBuilder, createdOnline: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static CanSetSortInTempDb(indexBuilder: IConventionIndexBuilder, sortInTempDb: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static HasFillFactor<TEntity>(indexBuilder: IndexBuilder<TEntity>, fillFactor: int): IndexBuilder<TEntity>;
    static HasFillFactor(indexBuilder: IConventionIndexBuilder, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static HasFillFactor(indexBuilder: IndexBuilder, fillFactor: int): IndexBuilder;
    static IncludeProperties<TEntity>(indexBuilder: IndexBuilder<TEntity>, includeExpression: Expression<Func<TEntity, unknown>>): IndexBuilder<TEntity>;
    static IncludeProperties<TEntity>(indexBuilder: IndexBuilder<TEntity>, ...propertyNames: string[]): IndexBuilder<TEntity>;
    static IncludeProperties(indexBuilder: IConventionIndexBuilder, propertyNames: IReadOnlyList<System_Internal.String>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static IncludeProperties(indexBuilder: IndexBuilder, ...propertyNames: string[]): IndexBuilder;
    static IsClustered<TEntity>(indexBuilder: IndexBuilder<TEntity>, clustered?: boolean): IndexBuilder<TEntity>;
    static IsClustered(indexBuilder: IConventionIndexBuilder, clustered: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static IsClustered(indexBuilder: IndexBuilder, clustered?: boolean): IndexBuilder;
    static IsCreatedOnline<TEntity>(indexBuilder: IndexBuilder<TEntity>, createdOnline?: boolean): IndexBuilder<TEntity>;
    static IsCreatedOnline(indexBuilder: IConventionIndexBuilder, createdOnline: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static IsCreatedOnline(indexBuilder: IndexBuilder, createdOnline?: boolean): IndexBuilder;
    static SortInTempDb<TEntity>(indexBuilder: IndexBuilder<TEntity>, sortInTempDb?: boolean): IndexBuilder<TEntity>;
    static SortInTempDb(indexBuilder: IConventionIndexBuilder, sortInTempDb: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static SortInTempDb(indexBuilder: IndexBuilder, sortInTempDb?: boolean): IndexBuilder;
    static UseDataCompression<TEntity>(indexBuilder: IndexBuilder<TEntity>, dataCompressionType: DataCompressionType): IndexBuilder<TEntity>;
    static UseDataCompression(indexBuilder: IConventionIndexBuilder, dataCompressionType: Nullable<DataCompressionType>, fromDataAnnotation?: boolean): IConventionIndexBuilder | undefined;
    static UseDataCompression(indexBuilder: IndexBuilder, dataCompressionType: DataCompressionType): IndexBuilder;
}


export type SqlServerIndexBuilderExtensions = SqlServerIndexBuilderExtensions$instance;

export abstract class SqlServerIndexExtensions$instance {
    static GetDataCompression(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): Nullable<DataCompressionType>;
    static GetDataCompression(index: IReadOnlyIndex): Nullable<DataCompressionType>;
    static GetDataCompressionConfigurationSource(index: IConventionIndex): Nullable<ConfigurationSource>;
    static GetFillFactor(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Int32>;
    static GetFillFactor(index: IReadOnlyIndex): Nullable<System_Internal.Int32>;
    static GetFillFactorConfigurationSource(index: IConventionIndex): Nullable<ConfigurationSource>;
    static GetIncludeProperties(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): IReadOnlyList<System_Internal.String> | undefined;
    static GetIncludeProperties(index: IReadOnlyIndex): IReadOnlyList<System_Internal.String> | undefined;
    static GetIncludePropertiesConfigurationSource(index: IConventionIndex): Nullable<ConfigurationSource>;
    static GetIsClusteredConfigurationSource(property: IConventionIndex): Nullable<ConfigurationSource>;
    static GetIsCreatedOnlineConfigurationSource(index: IConventionIndex): Nullable<ConfigurationSource>;
    static GetSortInTempDb(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Boolean>;
    static GetSortInTempDb(index: IReadOnlyIndex): Nullable<System_Internal.Boolean>;
    static GetSortInTempDbConfigurationSource(index: IConventionIndex): Nullable<ConfigurationSource>;
    static IsClustered(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Boolean>;
    static IsClustered(index: IReadOnlyIndex): Nullable<System_Internal.Boolean>;
    static IsCreatedOnline(index: IReadOnlyIndex, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Boolean>;
    static IsCreatedOnline(index: IReadOnlyIndex): Nullable<System_Internal.Boolean>;
    static SetDataCompression(index: IConventionIndex, dataCompression: Nullable<DataCompressionType>, fromDataAnnotation?: boolean): Nullable<DataCompressionType>;
    static SetDataCompression(index: IMutableIndex, dataCompression: Nullable<DataCompressionType>): void;
    static SetFillFactor(index: IConventionIndex, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetFillFactor(index: IMutableIndex, fillFactor: Nullable<System_Internal.Int32>): void;
    static SetIncludeProperties(index: IConventionIndex, properties: IReadOnlyList<System_Internal.String>, fromDataAnnotation?: boolean): IReadOnlyList<System_Internal.String> | undefined;
    static SetIncludeProperties(index: IMutableIndex, properties: IReadOnlyList<System_Internal.String>): void;
    static SetIsClustered(index: IConventionIndex, value: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsClustered(index: IMutableIndex, value: Nullable<System_Internal.Boolean>): void;
    static SetIsCreatedOnline(index: IConventionIndex, createdOnline: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsCreatedOnline(index: IMutableIndex, createdOnline: Nullable<System_Internal.Boolean>): void;
    static SetSortInTempDb(index: IConventionIndex, sortInTempDb: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetSortInTempDb(index: IMutableIndex, sortInTempDb: Nullable<System_Internal.Boolean>): void;
}


export type SqlServerIndexExtensions = SqlServerIndexExtensions$instance;

export abstract class SqlServerKeyBuilderExtensions$instance {
    static CanSetFillFactor(keyBuilder: IConventionKeyBuilder, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): boolean;
    static CanSetIsClustered(keyBuilder: IConventionKeyBuilder, clustered: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static HasFillFactor<TEntity>(keyBuilder: KeyBuilder<TEntity>, fillFactor: int): KeyBuilder<TEntity>;
    static HasFillFactor(keyBuilder: IConventionKeyBuilder, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): IConventionKeyBuilder | undefined;
    static HasFillFactor(keyBuilder: KeyBuilder, fillFactor: int): KeyBuilder;
    static IsClustered<TEntity>(keyBuilder: KeyBuilder<TEntity>, clustered?: boolean): KeyBuilder<TEntity>;
    static IsClustered(keyBuilder: IConventionKeyBuilder, clustered: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionKeyBuilder | undefined;
    static IsClustered(keyBuilder: KeyBuilder, clustered?: boolean): KeyBuilder;
}


export type SqlServerKeyBuilderExtensions = SqlServerKeyBuilderExtensions$instance;

export abstract class SqlServerKeyExtensions$instance {
    static GetFillFactor(key: IReadOnlyKey, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Int32>;
    static GetFillFactor(key: IReadOnlyKey): Nullable<System_Internal.Int32>;
    static GetFillFactorConfigurationSource(key: IConventionKey): Nullable<ConfigurationSource>;
    static GetIsClusteredConfigurationSource(key: IConventionKey): Nullable<ConfigurationSource>;
    static IsClustered(key: IReadOnlyKey, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Boolean>;
    static IsClustered(key: IReadOnlyKey): Nullable<System_Internal.Boolean>;
    static SetFillFactor(key: IConventionKey, fillFactor: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetFillFactor(key: IMutableKey, fillFactor: Nullable<System_Internal.Int32>): void;
    static SetIsClustered(key: IConventionKey, clustered: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsClustered(key: IMutableKey, clustered: Nullable<System_Internal.Boolean>): void;
}


export type SqlServerKeyExtensions = SqlServerKeyExtensions$instance;

export abstract class SqlServerModelBuilderExtensions$instance {
    static CanSetDatabaseMaxSize(modelBuilder: IConventionModelBuilder, maxSize: string, fromDataAnnotation?: boolean): boolean;
    static CanSetHiLoSequence(modelBuilder: IConventionModelBuilder, name: string, schema: string, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnIncrement(modelBuilder: IConventionModelBuilder, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnSeed(modelBuilder: IConventionModelBuilder, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): boolean;
    static CanSetPerformanceLevelSql(modelBuilder: IConventionModelBuilder, performanceLevel: string, fromDataAnnotation?: boolean): boolean;
    static CanSetServiceTierSql(modelBuilder: IConventionModelBuilder, serviceTier: string, fromDataAnnotation?: boolean): boolean;
    static CanSetValueGenerationStrategy(modelBuilder: IConventionModelBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): boolean;
    static CanUseNamedDefaultConstraints(modelBuilder: IConventionModelBuilder, value: boolean, fromDataAnnotation?: boolean): boolean;
    static HasDatabaseMaxSize(modelBuilder: IConventionModelBuilder, maxSize: string, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static HasDatabaseMaxSize(modelBuilder: ModelBuilder, maxSize: string): ModelBuilder;
    static HasHiLoSequence(modelBuilder: IConventionModelBuilder, name: string, schema: string, fromDataAnnotation?: boolean): IConventionSequenceBuilder | undefined;
    static HasIdentityColumnIncrement(modelBuilder: IConventionModelBuilder, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static HasIdentityColumnSeed(modelBuilder: IConventionModelBuilder, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static HasPerformanceLevel(modelBuilder: ModelBuilder, performanceLevel: string): ModelBuilder;
    static HasPerformanceLevelSql(modelBuilder: IConventionModelBuilder, performanceLevel: string, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static HasPerformanceLevelSql(modelBuilder: ModelBuilder, performanceLevel: string): ModelBuilder;
    static HasServiceTier(modelBuilder: ModelBuilder, serviceTier: string): ModelBuilder;
    static HasServiceTierSql(modelBuilder: IConventionModelBuilder, serviceTier: string, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static HasServiceTierSql(modelBuilder: ModelBuilder, serviceTier: string): ModelBuilder;
    static HasValueGenerationStrategy(modelBuilder: IConventionModelBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static UseHiLo(modelBuilder: ModelBuilder, name?: string, schema?: string): ModelBuilder;
    static UseIdentityColumns(modelBuilder: ModelBuilder, seed: int, increment?: int): ModelBuilder;
    static UseIdentityColumns(modelBuilder: ModelBuilder, seed?: long, increment?: int): ModelBuilder;
    static UseKeySequences(modelBuilder: ModelBuilder, nameSuffix?: string, schema?: string): ModelBuilder;
    static UseNamedDefaultConstraints(modelBuilder: IConventionModelBuilder, value: boolean, fromDataAnnotation?: boolean): IConventionModelBuilder | undefined;
    static UseNamedDefaultConstraints(modelBuilder: ModelBuilder, value?: boolean): ModelBuilder;
}


export type SqlServerModelBuilderExtensions = SqlServerModelBuilderExtensions$instance;

export abstract class SqlServerModelExtensions$instance {
    static readonly DefaultHiLoSequenceName: string;
    static readonly DefaultSequenceNameSuffix: string;
    static GetDatabaseMaxSize(model: IReadOnlyModel): string | undefined;
    static GetDatabaseMaxSizeConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetHiLoSequenceName(model: IReadOnlyModel): string;
    static GetHiLoSequenceNameConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetHiLoSequenceSchema(model: IReadOnlyModel): string | undefined;
    static GetHiLoSequenceSchemaConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetIdentityIncrement(model: IReadOnlyModel): int;
    static GetIdentityIncrementConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetIdentitySeed(model: IReadOnlyModel): long;
    static GetIdentitySeedConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetPerformanceLevelSql(model: IReadOnlyModel): string | undefined;
    static GetPerformanceLevelSqlConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetSequenceNameSuffix(model: IReadOnlyModel): string;
    static GetSequenceNameSuffixConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetSequenceSchema(model: IReadOnlyModel): string | undefined;
    static GetSequenceSchemaConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetServiceTierSql(model: IReadOnlyModel): string | undefined;
    static GetServiceTierSqlConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static GetValueGenerationStrategy(model: IReadOnlyModel): Nullable<SqlServerValueGenerationStrategy>;
    static GetValueGenerationStrategyConfigurationSource(model: IConventionModel): Nullable<ConfigurationSource>;
    static SetDatabaseMaxSize(model: IConventionModel, value: string, fromDataAnnotation?: boolean): string | undefined;
    static SetDatabaseMaxSize(model: IMutableModel, value: string): void;
    static SetHiLoSequenceName(model: IConventionModel, name: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHiLoSequenceName(model: IMutableModel, name: string): void;
    static SetHiLoSequenceSchema(model: IConventionModel, value: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHiLoSequenceSchema(model: IMutableModel, value: string): void;
    static SetIdentityIncrement(model: IConventionModel, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetIdentityIncrement(model: IMutableModel, increment: Nullable<System_Internal.Int32>): void;
    static SetIdentitySeed(model: IConventionModel, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int64>;
    static SetIdentitySeed(model: IMutableModel, seed: Nullable<System_Internal.Int64>): void;
    static SetPerformanceLevelSql(model: IConventionModel, value: string, fromDataAnnotation?: boolean): string | undefined;
    static SetPerformanceLevelSql(model: IMutableModel, value: string): void;
    static SetSequenceNameSuffix(model: IConventionModel, name: string, fromDataAnnotation?: boolean): string | undefined;
    static SetSequenceNameSuffix(model: IMutableModel, name: string): void;
    static SetSequenceSchema(model: IConventionModel, value: string, fromDataAnnotation?: boolean): string | undefined;
    static SetSequenceSchema(model: IMutableModel, value: string): void;
    static SetServiceTierSql(model: IConventionModel, value: string, fromDataAnnotation?: boolean): string | undefined;
    static SetServiceTierSql(model: IMutableModel, value: string): void;
    static SetValueGenerationStrategy(model: IConventionModel, value: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): Nullable<SqlServerValueGenerationStrategy>;
    static SetValueGenerationStrategy(model: IMutableModel, value: Nullable<SqlServerValueGenerationStrategy>): void;
}


export type SqlServerModelExtensions = SqlServerModelExtensions$instance;

export abstract class SqlServerPrimitiveCollectionBuilderExtensions$instance {
    static HasDefaultValue(primitiveCollectionBuilder: PrimitiveCollectionBuilder, value: unknown, defaultConstraintName: string): PrimitiveCollectionBuilder;
    static HasDefaultValue<TProperty>(primitiveCollectionBuilder: PrimitiveCollectionBuilder<TProperty>, value: unknown, defaultConstraintName: string): PrimitiveCollectionBuilder<TProperty>;
    static HasDefaultValueSql(primitiveCollectionBuilder: PrimitiveCollectionBuilder, sql: string, defaultConstraintName: string): PrimitiveCollectionBuilder;
    static HasDefaultValueSql<TProperty>(primitiveCollectionBuilder: PrimitiveCollectionBuilder<TProperty>, sql: string, defaultConstraintName: string): PrimitiveCollectionBuilder<TProperty>;
    static IsSparse(primitiveCollectionBuilder: PrimitiveCollectionBuilder, sparse?: boolean): PrimitiveCollectionBuilder;
    static IsSparse<TProperty>(primitiveCollectionBuilder: PrimitiveCollectionBuilder<TProperty>, sparse?: boolean): PrimitiveCollectionBuilder<TProperty>;
}


export type SqlServerPrimitiveCollectionBuilderExtensions = SqlServerPrimitiveCollectionBuilderExtensions$instance;

export abstract class SqlServerPropertyBuilderExtensions$instance {
    static CanSetDefaultValue(propertyBuilder: IConventionPropertyBuilder, value: unknown, defaultConstraintName: string, fromDataAnnotation?: boolean): boolean;
    static CanSetDefaultValueSql(propertyBuilder: IConventionPropertyBuilder, sql: string, defaultConstraintName: string, fromDataAnnotation?: boolean): boolean;
    static CanSetHiLoSequence(propertyBuilder: IConventionPropertyBuilder, name: string, schema: string, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnIncrement(propertyBuilder: IConventionPropertyBuilder, increment: Nullable<System_Internal.Int32>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnIncrement(propertyBuilder: IConventionPropertyBuilder, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnSeed(propertyBuilder: IConventionPropertyBuilder, seed: Nullable<System_Internal.Int64>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): boolean;
    static CanSetIdentityColumnSeed(propertyBuilder: IConventionPropertyBuilder, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): boolean;
    static CanSetIsSparse(property: IConventionPropertyBuilder, sparse: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static CanSetSequence(propertyBuilder: IConventionPropertyBuilder, name: string, schema: string, fromDataAnnotation?: boolean): boolean;
    static CanSetValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): boolean;
    static CanSetValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): boolean;
    static HasDefaultValue(propertyBuilder: IConventionPropertyBuilder, value: unknown, defaultConstraintName: string, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasDefaultValue(propertyBuilder: PropertyBuilder, value: unknown, defaultConstraintName: string): PropertyBuilder;
    static HasDefaultValue<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, value: unknown, defaultConstraintName: string): PropertyBuilder<TProperty>;
    static HasDefaultValueSql(propertyBuilder: IConventionPropertyBuilder, sql: string, defaultConstraintName: string, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasDefaultValueSql(propertyBuilder: PropertyBuilder, sql: string, defaultConstraintName: string): PropertyBuilder;
    static HasDefaultValueSql<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, sql: string, defaultConstraintName: string): PropertyBuilder<TProperty>;
    static HasHiLoSequence(propertyBuilder: IConventionPropertyBuilder, name: string, schema: string, fromDataAnnotation?: boolean): IConventionSequenceBuilder | undefined;
    static HasIdentityColumnIncrement(propertyBuilder: IConventionPropertyBuilder, increment: Nullable<System_Internal.Int32>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasIdentityColumnIncrement(propertyBuilder: IConventionPropertyBuilder, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasIdentityColumnSeed(propertyBuilder: IConventionPropertyBuilder, seed: Nullable<System_Internal.Int64>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasIdentityColumnSeed(propertyBuilder: IConventionPropertyBuilder, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasSequence(propertyBuilder: IConventionPropertyBuilder, name: string, schema: string, fromDataAnnotation?: boolean): IConventionSequenceBuilder | undefined;
    static HasValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static HasValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, valueGenerationStrategy: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static IsSparse(propertyBuilder: IConventionPropertyBuilder, sparse: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static IsSparse(propertyBuilder: PropertyBuilder, sparse?: boolean): PropertyBuilder;
    static IsSparse<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, sparse?: boolean): PropertyBuilder<TProperty>;
    static UseHiLo(propertyBuilder: PropertyBuilder, name?: string, schema?: string): PropertyBuilder;
    static UseHiLo<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, name?: string, schema?: string): PropertyBuilder<TProperty>;
    static UseIdentityColumn<TProperty>(columnBuilder: ColumnBuilder<TProperty>, seed?: long, increment?: int): ColumnBuilder<TProperty>;
    static UseIdentityColumn(columnBuilder: ColumnBuilder, seed?: long, increment?: int): ColumnBuilder;
    static UseIdentityColumn(propertyBuilder: PropertyBuilder, seed: int, increment?: int): PropertyBuilder;
    static UseIdentityColumn(propertyBuilder: PropertyBuilder, seed?: long, increment?: int): PropertyBuilder;
    static UseIdentityColumn<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, seed: int, increment?: int): PropertyBuilder<TProperty>;
    static UseIdentityColumn<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, seed?: long, increment?: int): PropertyBuilder<TProperty>;
    static UseSequence(propertyBuilder: PropertyBuilder, name?: string, schema?: string): PropertyBuilder;
    static UseSequence<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, name?: string, schema?: string): PropertyBuilder<TProperty>;
}


export type SqlServerPropertyBuilderExtensions = SqlServerPropertyBuilderExtensions$instance;

export abstract class SqlServerPropertyExtensions$instance {
    static FindHiLoSequence(property: IProperty, storeObject: StoreObjectIdentifier): ISequence | undefined;
    static FindHiLoSequence(property: IProperty): ISequence | undefined;
    static FindHiLoSequence(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): IReadOnlySequence | undefined;
    static FindHiLoSequence(property: IReadOnlyProperty): IReadOnlySequence | undefined;
    static FindSequence(property: IProperty, storeObject: StoreObjectIdentifier): ISequence | undefined;
    static FindSequence(property: IProperty): ISequence | undefined;
    static FindSequence(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): IReadOnlySequence | undefined;
    static FindSequence(property: IReadOnlyProperty): IReadOnlySequence | undefined;
    static GetHiLoSequenceName(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): string | undefined;
    static GetHiLoSequenceName(property: IReadOnlyProperty): string | undefined;
    static GetHiLoSequenceNameConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetHiLoSequenceSchema(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): string | undefined;
    static GetHiLoSequenceSchema(property: IReadOnlyProperty): string | undefined;
    static GetHiLoSequenceSchemaConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetIdentityIncrement(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Int32>;
    static GetIdentityIncrement(property: IReadOnlyProperty): Nullable<System_Internal.Int32>;
    static GetIdentityIncrement(overrides: IReadOnlyRelationalPropertyOverrides): Nullable<System_Internal.Int32>;
    static GetIdentityIncrementConfigurationSource(property: IConventionProperty, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static GetIdentityIncrementConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetIdentityIncrementConfigurationSource(overrides: IConventionRelationalPropertyOverrides): Nullable<ConfigurationSource>;
    static GetIdentitySeed(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Int64>;
    static GetIdentitySeed(property: IReadOnlyProperty): Nullable<System_Internal.Int64>;
    static GetIdentitySeed(overrides: IReadOnlyRelationalPropertyOverrides): Nullable<System_Internal.Int64>;
    static GetIdentitySeedConfigurationSource(property: IConventionProperty, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static GetIdentitySeedConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetIdentitySeedConfigurationSource(overrides: IConventionRelationalPropertyOverrides): Nullable<ConfigurationSource>;
    static GetIsSparseConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetSequenceName(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): string | undefined;
    static GetSequenceName(property: IReadOnlyProperty): string | undefined;
    static GetSequenceNameConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetSequenceSchema(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): string | undefined;
    static GetSequenceSchema(property: IReadOnlyProperty): string | undefined;
    static GetSequenceSchemaConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetValueGenerationStrategy(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): SqlServerValueGenerationStrategy;
    static GetValueGenerationStrategy(property: IReadOnlyProperty): SqlServerValueGenerationStrategy;
    static GetValueGenerationStrategy(overrides: IReadOnlyRelationalPropertyOverrides): Nullable<SqlServerValueGenerationStrategy>;
    static GetValueGenerationStrategyConfigurationSource(property: IConventionProperty, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static GetValueGenerationStrategyConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static GetValueGenerationStrategyConfigurationSource(overrides: IConventionRelationalPropertyOverrides): Nullable<ConfigurationSource>;
    static IsCompatibleWithValueGeneration(property: IReadOnlyProperty): boolean;
    static IsSparse(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Boolean>;
    static IsSparse(property: IReadOnlyProperty): Nullable<System_Internal.Boolean>;
    static SetHiLoSequenceName(property: IConventionProperty, name: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHiLoSequenceName(property: IMutableProperty, name: string): void;
    static SetHiLoSequenceSchema(property: IConventionProperty, schema: string, fromDataAnnotation?: boolean): string | undefined;
    static SetHiLoSequenceSchema(property: IMutableProperty, schema: string): void;
    static SetIdentityIncrement(property: IConventionProperty, increment: Nullable<System_Internal.Int32>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetIdentityIncrement(property: IConventionProperty, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetIdentityIncrement(overrides: IConventionRelationalPropertyOverrides, increment: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static SetIdentityIncrement(property: IMutableProperty, increment: Nullable<System_Internal.Int32>, storeObject: StoreObjectIdentifier): void;
    static SetIdentityIncrement(property: IMutableProperty, increment: Nullable<System_Internal.Int32>): void;
    static SetIdentityIncrement(overrides: IMutableRelationalPropertyOverrides, increment: Nullable<System_Internal.Int32>): void;
    static SetIdentitySeed(property: IConventionProperty, seed: Nullable<System_Internal.Int64>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<System_Internal.Int64>;
    static SetIdentitySeed(property: IConventionProperty, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int64>;
    static SetIdentitySeed(overrides: IConventionRelationalPropertyOverrides, seed: Nullable<System_Internal.Int64>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int64>;
    static SetIdentitySeed(property: IMutableProperty, seed: Nullable<System_Internal.Int64>, storeObject: StoreObjectIdentifier): void;
    static SetIdentitySeed(property: IMutableProperty, seed: Nullable<System_Internal.Int64>): void;
    static SetIdentitySeed(overrides: IMutableRelationalPropertyOverrides, seed: Nullable<System_Internal.Int64>): void;
    static SetIsSparse(property: IConventionProperty, sparse: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static SetIsSparse(property: IMutableProperty, sparse: Nullable<System_Internal.Boolean>): void;
    static SetSequenceName(property: IConventionProperty, name: string, fromDataAnnotation?: boolean): string | undefined;
    static SetSequenceName(property: IMutableProperty, name: string): void;
    static SetSequenceSchema(property: IConventionProperty, schema: string, fromDataAnnotation?: boolean): string | undefined;
    static SetSequenceSchema(property: IMutableProperty, schema: string): void;
    static SetValueGenerationStrategy(property: IConventionProperty, value: Nullable<SqlServerValueGenerationStrategy>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<SqlServerValueGenerationStrategy>;
    static SetValueGenerationStrategy(property: IConventionProperty, value: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): Nullable<SqlServerValueGenerationStrategy>;
    static SetValueGenerationStrategy(overrides: IConventionRelationalPropertyOverrides, value: Nullable<SqlServerValueGenerationStrategy>, fromDataAnnotation?: boolean): Nullable<SqlServerValueGenerationStrategy>;
    static SetValueGenerationStrategy(property: IMutableProperty, value: Nullable<SqlServerValueGenerationStrategy>, storeObject: StoreObjectIdentifier): void;
    static SetValueGenerationStrategy(property: IMutableProperty, value: Nullable<SqlServerValueGenerationStrategy>): void;
    static SetValueGenerationStrategy(overrides: IMutableRelationalPropertyOverrides, value: Nullable<SqlServerValueGenerationStrategy>): void;
}


export type SqlServerPropertyExtensions = SqlServerPropertyExtensions$instance;

export abstract class SqlServerTableBuilderExtensions$instance {
    static IsMemoryOptimized(tableBuilder: OwnedNavigationTableBuilder, memoryOptimized?: boolean): OwnedNavigationTableBuilder;
    static IsMemoryOptimized(tableBuilder: TableBuilder, memoryOptimized?: boolean): TableBuilder;
    static IsMemoryOptimized<TOwnerEntity, TDependentEntity>(tableBuilder: OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>, memoryOptimized?: boolean): OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>;
    static IsMemoryOptimized<TEntity>(tableBuilder: TableBuilder<TEntity>, memoryOptimized?: boolean): TableBuilder<TEntity>;
    static IsTemporal(tableBuilder: OwnedNavigationTableBuilder, buildAction: Action<OwnedNavigationTemporalTableBuilder>): OwnedNavigationTableBuilder;
    static IsTemporal(tableBuilder: OwnedNavigationTableBuilder, temporal?: boolean): OwnedNavigationTemporalTableBuilder;
    static IsTemporal(tableBuilder: TableBuilder, buildAction: Action<TemporalTableBuilder>): TableBuilder;
    static IsTemporal(tableBuilder: TableBuilder, temporal?: boolean): TemporalTableBuilder;
    static IsTemporal<TOwnerEntity, TDependentEntity>(tableBuilder: OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>, buildAction: Action<OwnedNavigationTemporalTableBuilder_2<TOwnerEntity, TDependentEntity>>): OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>;
    static IsTemporal<TOwnerEntity, TDependentEntity>(tableBuilder: OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>, temporal?: boolean): OwnedNavigationTemporalTableBuilder_2<TOwnerEntity, TDependentEntity>;
    static IsTemporal<TEntity>(tableBuilder: TableBuilder<TEntity>, buildAction: Action<TemporalTableBuilder_1<TEntity>>): TableBuilder<TEntity>;
    static IsTemporal<TEntity>(tableBuilder: TableBuilder<TEntity>, temporal?: boolean): TemporalTableBuilder_1<TEntity>;
    static UseSqlOutputClause(tableBuilder: OwnedNavigationTableBuilder, useSqlOutputClause?: boolean): OwnedNavigationTableBuilder;
    static UseSqlOutputClause(tableBuilder: SplitTableBuilder, useSqlOutputClause?: boolean): SplitTableBuilder;
    static UseSqlOutputClause(tableBuilder: TableBuilder, useSqlOutputClause?: boolean): TableBuilder;
    static UseSqlOutputClause<TOwnerEntity, TDependentEntity>(tableBuilder: OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>, useSqlOutputClause?: boolean): OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>;
    static UseSqlOutputClause<TEntity>(tableBuilder: SplitTableBuilder<TEntity>, useSqlOutputClause?: boolean): SplitTableBuilder<TEntity>;
    static UseSqlOutputClause<TEntity>(tableBuilder: TableBuilder<TEntity>, useSqlOutputClause?: boolean): TableBuilder<TEntity>;
}


export type SqlServerTableBuilderExtensions = SqlServerTableBuilderExtensions$instance;

export abstract class SqlServerTableExtensions$instance {
    static IsSqlOutputClauseUsed(table: ITable): boolean;
}


export type SqlServerTableExtensions = SqlServerTableExtensions$instance;

