// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Identity.Client.Cache
// Assembly: Microsoft.Identity.Client

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Byte, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject } from "@tsonic/dotnet/System/internal/index.js";

export enum CacheLevel {
    None = 0,
    Unknown = 1,
    L1Cache = 2,
    L2Cache = 3
}


export interface CacheData$instance {
    readonly __tsonic_type_Microsoft_Identity_Client_Cache_CacheData: never;

    AdalV3State: byte[];
    UnifiedState: byte[];
}


export const CacheData: {
    new(): CacheData;
};


export type CacheData = CacheData$instance;

