// Generated by tsbindgen - Architecture
// Namespace: Azure
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { HttpPipeline, HttpPipelinePolicy } from "../../Azure.Core.Pipeline/internal/index.js";
import type { JsonPropertyNames, ObjectSerializer } from "../../Azure.Core.Serialization/internal/index.js";
import type { ClientOptions, DelayStrategy, HttpHeader, HttpPipelinePosition, RehydrationToken, RequestFailedDetailsParser, ResponseClassificationHandler, ResponseHeaders } from "../../Azure.Core/internal/index.js";
import * as System_ClientModel_Primitives_Internal from "../../System.ClientModel.Primitives/internal/index.js";
import type { IJsonModel_1, IPersistableModel_1, ModelReaderWriterOptions } from "../../System.ClientModel.Primitives/internal/index.js";
import * as System_ClientModel_Internal from "../../System.ClientModel/internal/index.js";
import type { ApiKeyCredential } from "../../System.ClientModel/internal/index.js";
import type { BinaryData } from "../../System/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IAsyncEnumerable_1, IAsyncEnumerator_1, IEnumerable_1, IEnumerator_1, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { Utf8JsonReader, Utf8JsonWriter } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import type { Task_1, ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Lib from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, DateTimeOffset, Enum, EventArgs, Exception, IComparable, IConvertible, IDisposable, IEquatable_1, IFormattable, Int32, Int64, ISpanFormattable, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, String as ClrString, TimeSpan, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export enum ErrorOptions {
    Default = 0,
    NoThrow = 1
}


export enum WaitUntil {
    Completed = 0,
    Started = 1
}


export interface ETag$instance {
    readonly __tsonic_type_Azure_ETag: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    Equals(other: ETag): boolean;
    Equals(other: string): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    ToString(): string;
    ToString(format: string): string;
}


export const ETag: {
    new(etag: string): ETag;
    readonly All: ETag;
};


export type ETag = ETag$instance;

export interface HttpRange$instance {
    readonly __tsonic_type_Azure_HttpRange: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Length: Nullable_1<System_Internal.Int64>;
    readonly Offset: long;
    Equals(other: HttpRange): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const HttpRange: {
    new(offset: long, length: Nullable_1<System_Internal.Int64>): HttpRange;
};


export type HttpRange = HttpRange$instance;

export interface AsyncPageable_1$instance<T> {
    readonly __tsonic_type_Azure_AsyncPageable_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IAsyncEnumerable_1: never;

    readonly CancellationToken: CancellationToken;
    AsPages(continuationToken?: string, pageSizeHint?: Nullable_1<System_Internal.Int32>): IAsyncEnumerable_1<Page_1<T>>;
    Equals(obj: unknown): boolean;
    GetAsyncEnumerator(cancellationToken?: CancellationToken): IAsyncEnumerator_1<T>;
    GetHashCode(): int;
    ToString(): string | undefined;
}


export const AsyncPageable_1: (abstract new<T>() => AsyncPageable_1<T>) & (abstract new<T>(cancellationToken: CancellationToken) => AsyncPageable_1<T>) & {
    FromPages<T>(pages: IEnumerable_1<Page_1<T>>): AsyncPageable_1<T>;
};


export type AsyncPageable_1<T> = AsyncPageable_1$instance<T>;

export interface AzureKeyCredential$instance extends ApiKeyCredential {
    readonly __tsonic_type_Azure_AzureKeyCredential: never;

    Key: string;
}


export const AzureKeyCredential: {
    new(key: string): AzureKeyCredential;
};


export type AzureKeyCredential = AzureKeyCredential$instance;

export interface AzureNamedKeyCredential$instance {
    readonly __tsonic_type_Azure_AzureNamedKeyCredential: never;

    readonly Name: string;
    Deconstruct(name: string, key: string): void;
    Update(name: string, key: string): void;
}


export const AzureNamedKeyCredential: {
    new(name: string, key: string): AzureNamedKeyCredential;
};


export type AzureNamedKeyCredential = AzureNamedKeyCredential$instance;

export interface AzureSasCredential$instance {
    readonly __tsonic_type_Azure_AzureSasCredential: never;

    Signature: string;
    Update(signature: string): void;
}


export const AzureSasCredential: {
    new(signature: string): AzureSasCredential;
};


export type AzureSasCredential = AzureSasCredential$instance;

export interface HttpAuthorization$instance {
    readonly __tsonic_type_Azure_HttpAuthorization: never;

    readonly Parameter: string;
    readonly Scheme: string;
    ToString(): string;
}


export const HttpAuthorization: {
    new(scheme: string, parameter: string): HttpAuthorization;
};


export type HttpAuthorization = HttpAuthorization$instance;

export interface JsonPatchDocument$instance {
    readonly __tsonic_type_Azure_JsonPatchDocument: never;

    AppendAdd<T>(path: string, value: T): void;
    AppendAddRaw(path: string, rawJsonValue: string): void;
    AppendCopy(from: string, path: string): void;
    AppendMove(from: string, path: string): void;
    AppendRemove(path: string): void;
    AppendReplace<T>(path: string, value: T): void;
    AppendReplaceRaw(path: string, rawJsonValue: string): void;
    AppendTest<T>(path: string, value: T): void;
    AppendTestRaw(path: string, rawJsonValue: string): void;
    ToBytes(): ReadOnlyMemory_1<System_Internal.Byte>;
    ToString(): string;
}


export const JsonPatchDocument: {
    new(): JsonPatchDocument;
    new(serializer: ObjectSerializer): JsonPatchDocument;
    new(rawDocument: ReadOnlyMemory_1<System_Internal.Byte>): JsonPatchDocument;
    new(rawDocument: ReadOnlyMemory_1<System_Internal.Byte>, serializer: ObjectSerializer): JsonPatchDocument;
};


export type JsonPatchDocument = JsonPatchDocument$instance;

export interface MatchConditions$instance {
    readonly __tsonic_type_Azure_MatchConditions: never;

    IfMatch: Nullable_1<ETag>;
    IfNoneMatch: Nullable_1<ETag>;
}


export const MatchConditions: {
    new(): MatchConditions;
};


export type MatchConditions = MatchConditions$instance;

export interface NullableResponse_1$instance<T> {
    readonly __tsonic_type_Azure_NullableResponse_1: never;

    readonly HasValue: boolean;
    readonly Value: T | undefined;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    GetRawResponse(): Response;
    ToString(): string;
}


export const NullableResponse_1: (abstract new<T>() => NullableResponse_1<T>) & {
};


export type NullableResponse_1<T> = NullableResponse_1$instance<T>;

export interface Operation$instance {
    readonly __tsonic_type_Azure_Operation: never;

    readonly HasCompleted: boolean;
    readonly Id: string;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    GetRawResponse(): Response;
    GetRehydrationToken(): Nullable_1<RehydrationToken>;
    ToString(): string | undefined;
    UpdateStatus(cancellationToken?: CancellationToken): Response;
    UpdateStatusAsync(cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponse(cancellationToken?: CancellationToken): Response;
    WaitForCompletionResponse(pollingInterval: TimeSpan, cancellationToken?: CancellationToken): Response;
    WaitForCompletionResponse(delayStrategy: DelayStrategy, cancellationToken?: CancellationToken): Response;
    WaitForCompletionResponseAsync(cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(pollingInterval: TimeSpan, cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(delayStrategy: DelayStrategy, cancellationToken?: CancellationToken): ValueTask_1<Response>;
}


export const Operation: (abstract new() => Operation) & {
    Rehydrate(pipeline: HttpPipeline, rehydrationToken: RehydrationToken, options?: ClientOptions): Operation;
    Rehydrate<T extends IPersistableModel_1<T>>(pipeline: HttpPipeline, rehydrationToken: RehydrationToken, options?: ClientOptions): Operation_1<T>;
    RehydrateAsync(pipeline: HttpPipeline, rehydrationToken: RehydrationToken, options?: ClientOptions): Task_1<Operation>;
    RehydrateAsync<T extends IPersistableModel_1<T>>(pipeline: HttpPipeline, rehydrationToken: RehydrationToken, options?: ClientOptions): Task_1<Operation_1<T>>;
};


export type Operation = Operation$instance;

export interface Operation_1$instance<T> extends Operation {
    readonly __tsonic_type_Azure_Operation_1: never;

    readonly HasValue: boolean;
    readonly Value: T;
    WaitForCompletion(cancellationToken?: CancellationToken): Response_1<T>;
    WaitForCompletion(pollingInterval: TimeSpan, cancellationToken: CancellationToken): Response_1<T>;
    WaitForCompletion(delayStrategy: DelayStrategy, cancellationToken: CancellationToken): Response_1<T>;
    WaitForCompletionAsync(cancellationToken?: CancellationToken): ValueTask_1<Response_1<T>>;
    WaitForCompletionAsync(pollingInterval: TimeSpan, cancellationToken: CancellationToken): ValueTask_1<Response_1<T>>;
    WaitForCompletionAsync(delayStrategy: DelayStrategy, cancellationToken: CancellationToken): ValueTask_1<Response_1<T>>;
    WaitForCompletionResponseAsync(cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(pollingInterval: TimeSpan, cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(pollingInterval: TimeSpan, cancellationToken?: CancellationToken): ValueTask_1<Response>;
    WaitForCompletionResponseAsync(delayStrategy: DelayStrategy, cancellationToken?: CancellationToken): ValueTask_1<Response>;
}


export const Operation_1: (abstract new<T>() => Operation_1<T>) & {
};


export type Operation_1<T> = Operation_1$instance<T>;

export interface Page_1$instance<T> {
    readonly __tsonic_type_Azure_Page_1: never;

    readonly ContinuationToken: string | undefined;
    readonly Values: IReadOnlyList_1<T>;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    GetRawResponse(): Response;
    ToString(): string | undefined;
}


export const Page_1: (abstract new<T>() => Page_1<T>) & {
    FromValues<T>(values: IReadOnlyList_1<T>, continuationToken: string, response: Response): Page_1<T>;
};


export type Page_1<T> = Page_1$instance<T>;

export interface Pageable_1$instance<T> {
    readonly __tsonic_type_Azure_Pageable_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly CancellationToken: CancellationToken;
    AsPages(continuationToken?: string, pageSizeHint?: Nullable_1<System_Internal.Int32>): IEnumerable_1<Page_1<T>>;
    Equals(obj: unknown): boolean;
    GetEnumerator(): IEnumerator_1<T>;
    GetHashCode(): int;
    ToString(): string | undefined;
}


export const Pageable_1: (abstract new<T>() => Pageable_1<T>) & (abstract new<T>(cancellationToken: CancellationToken) => Pageable_1<T>) & {
    FromPages<T>(pages: IEnumerable_1<Page_1<T>>): Pageable_1<T>;
};


export type Pageable_1<T> = Pageable_1$instance<T>;

export interface PageableOperation_1$instance<T> extends Operation_1<AsyncPageable_1<T>> {
    readonly __tsonic_type_Azure_PageableOperation_1: never;

    readonly Value: AsyncPageable_1<T>;
    GetValues(cancellationToken?: CancellationToken): Pageable_1<T>;
    GetValuesAsync(cancellationToken?: CancellationToken): AsyncPageable_1<T>;
}


export const PageableOperation_1: (abstract new<T>() => PageableOperation_1<T>) & {
};


export type PageableOperation_1<T> = PageableOperation_1$instance<T>;

export interface RequestConditions$instance extends MatchConditions {
    readonly __tsonic_type_Azure_RequestConditions: never;

    IfModifiedSince: Nullable_1<DateTimeOffset>;
    IfUnmodifiedSince: Nullable_1<DateTimeOffset>;
}


export const RequestConditions: {
    new(): RequestConditions;
};


export type RequestConditions = RequestConditions$instance;

export interface RequestContext$instance {
    readonly __tsonic_type_Azure_RequestContext: never;

    CancellationToken: CancellationToken;
    ErrorOptions: ErrorOptions;
    AddClassifier(statusCode: int, isError: boolean): void;
    AddClassifier(classifier: ResponseClassificationHandler): void;
    AddPolicy(policy: HttpPipelinePolicy, position: HttpPipelinePosition): void;
}


export const RequestContext: {
    new(): RequestContext;
};


export type RequestContext = RequestContext$instance;

export interface RequestFailedException$instance extends Exception {
    readonly __tsonic_type_Azure_RequestFailedException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly ErrorCode: string | undefined;
    readonly Status: int;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    GetRawResponse(): Response | undefined;
}


export const RequestFailedException: {
    new(message: string): RequestFailedException;
    new(message: string, innerException: Exception): RequestFailedException;
    new(status: int, message: string): RequestFailedException;
    new(status: int, message: string, innerException: Exception): RequestFailedException;
    new(status: int, message: string, errorCode: string, innerException: Exception): RequestFailedException;
    new(response: Response): RequestFailedException;
    new(response: Response, innerException: Exception): RequestFailedException;
    new(response: Response, innerException: Exception, detailsParser: RequestFailedDetailsParser): RequestFailedException;
};


export type RequestFailedException = RequestFailedException$instance;

export interface Response$instance {
    readonly __tsonic_type_Azure_Response: never;

    readonly __tsonic_iface_System_IDisposable: never;

    ClientRequestId: string;
    readonly Content: BinaryData;
    get ContentStream(): Stream | undefined;
    set ContentStream(value: Stream | undefined);
    readonly Headers: ResponseHeaders;
    IsError: boolean;
    readonly ReasonPhrase: string;
    readonly Status: int;
    ContainsHeader(name: string): boolean;
    Dispose(): void;
    EnumerateHeaders(): IEnumerable_1<HttpHeader>;
    ToString(): string;
    TryGetHeader(name: string, value: string): boolean;
    TryGetHeaderValues(name: string, values: IEnumerable_1<System_Internal.String>): boolean;
}


export const Response: (abstract new() => Response) & {
    FromValue<T>(value: T, response: Response): Response_1<T>;
};


export type Response = Response$instance;

export interface Response_1$instance<T> extends NullableResponse_1<T> {
    readonly __tsonic_type_Azure_Response_1: never;

    readonly HasValue: boolean;
    readonly Value: T;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
}


export const Response_1: (abstract new<T>() => Response_1<T>) & {
};


export type Response_1<T> = Response_1$instance<T>;

export interface ResponseError$instance extends System_ClientModel_Primitives_Internal.IJsonModel_1$instance<ResponseError> {
    readonly __tsonic_type_Azure_ResponseError: never;

    readonly __tsonic_iface_System_ClientModel_Primitives_IJsonModel_1: never;
    readonly __tsonic_iface_System_ClientModel_Primitives_IPersistableModel_1: never;

    readonly Code: string | undefined;
    readonly Message: string | undefined;
    ToString(): string;
}


export const ResponseError: {
    new(): ResponseError;
    new(code: string, message: string): ResponseError;
};


export interface __ResponseError$views {
    As_IJsonModel_1(): System_ClientModel_Primitives_Internal.IJsonModel_1$instance<ResponseError>;
    As_IPersistableModel_1(): System_ClientModel_Primitives_Internal.IPersistableModel_1$instance<ResponseError>;
}

export type ResponseError = ResponseError$instance & __ResponseError$views;


export interface SyncAsyncEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Azure_SyncAsyncEventArgs: never;

    readonly CancellationToken: CancellationToken;
    readonly IsRunningSynchronously: boolean;
}


export const SyncAsyncEventArgs: {
    new(isRunningSynchronously: boolean, cancellationToken: CancellationToken): SyncAsyncEventArgs;
};


export type SyncAsyncEventArgs = SyncAsyncEventArgs$instance;

export abstract class AzureCoreExtensions$instance {
    static ToDynamicFromJson(utf8Json: BinaryData, propertyNameFormat: JsonPropertyNames, dateTimeFormat?: string): unknown;
    static ToDynamicFromJson(utf8Json: BinaryData): unknown;
    static ToObject<T>(data: BinaryData, serializer: ObjectSerializer, cancellationToken?: CancellationToken): T | undefined;
    static ToObjectAsync<T>(data: BinaryData, serializer: ObjectSerializer, cancellationToken?: CancellationToken): ValueTask_1<T>;
    static ToObjectFromJson(data: BinaryData): unknown | undefined;
}


export type AzureCoreExtensions = AzureCoreExtensions$instance;

