// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Infrastructure
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_SqlServer_Infrastructure_Internal_Internal from "../../Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal/internal/index.js";
import type { SqlServerOptionsExtension } from "../../Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal/internal/index.js";
import type { ICollection, IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Boolean as ClrBoolean, Int32, TimeSpan } from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IRelationalDbContextOptionsBuilderInfrastructure, RelationalDbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";

export interface AzureSqlDbContextOptionsBuilder$instance extends SqlEngineDbContextOptionsBuilderBase_1<AzureSqlDbContextOptionsBuilder> {
    EnableRetryOnFailure(): AzureSqlDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int): AzureSqlDbContextOptionsBuilder;
    EnableRetryOnFailure(errorNumbersToAdd: ICollection<System_Internal.Int32>): AzureSqlDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): AzureSqlDbContextOptionsBuilder;
    UseCompatibilityLevel(compatibilityLevel: int): AzureSqlDbContextOptionsBuilder;
}


export const AzureSqlDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): AzureSqlDbContextOptionsBuilder;
};


export type AzureSqlDbContextOptionsBuilder = AzureSqlDbContextOptionsBuilder$instance;

export interface AzureSynapseDbContextOptionsBuilder$instance extends SqlEngineDbContextOptionsBuilderBase_1<AzureSynapseDbContextOptionsBuilder> {
    EnableRetryOnFailure(): AzureSynapseDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int): AzureSynapseDbContextOptionsBuilder;
    EnableRetryOnFailure(errorNumbersToAdd: ICollection<System_Internal.Int32>): AzureSynapseDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): AzureSynapseDbContextOptionsBuilder;
    UseCompatibilityLevel(compatibilityLevel: int): AzureSynapseDbContextOptionsBuilder;
}


export const AzureSynapseDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): AzureSynapseDbContextOptionsBuilder;
};


export type AzureSynapseDbContextOptionsBuilder = AzureSynapseDbContextOptionsBuilder$instance;

export interface SqlEngineDbContextOptionsBuilder$instance extends SqlEngineDbContextOptionsBuilderBase_1<SqlEngineDbContextOptionsBuilder> {
    EnableRetryOnFailure(): SqlEngineDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int): SqlEngineDbContextOptionsBuilder;
    EnableRetryOnFailure(errorNumbersToAdd: ICollection<System_Internal.Int32>): SqlEngineDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): SqlEngineDbContextOptionsBuilder;
    EnableRetryOnFailureByDefault(): SqlEngineDbContextOptionsBuilder;
}


export const SqlEngineDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): SqlEngineDbContextOptionsBuilder;
};


export type SqlEngineDbContextOptionsBuilder = SqlEngineDbContextOptionsBuilder$instance;

export interface SqlEngineDbContextOptionsBuilderBase_1$instance<TSelf extends SqlEngineDbContextOptionsBuilderBase_1<TSelf>> extends RelationalDbContextOptionsBuilder<TSelf, SqlServerOptionsExtension> {
}


export const SqlEngineDbContextOptionsBuilderBase_1: {
    new<TSelf extends SqlEngineDbContextOptionsBuilderBase_1<TSelf>>(optionsBuilder: DbContextOptionsBuilder): SqlEngineDbContextOptionsBuilderBase_1<TSelf>;
};


export type SqlEngineDbContextOptionsBuilderBase_1<TSelf extends SqlEngineDbContextOptionsBuilderBase_1<TSelf>> = SqlEngineDbContextOptionsBuilderBase_1$instance<TSelf>;

export interface SqlServerDbContextOptionsBuilder$instance extends SqlEngineDbContextOptionsBuilderBase_1<SqlServerDbContextOptionsBuilder> {
    EnableRetryOnFailure(): SqlServerDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int): SqlServerDbContextOptionsBuilder;
    EnableRetryOnFailure(errorNumbersToAdd: ICollection<System_Internal.Int32>): SqlServerDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int, maxRetryDelay: TimeSpan, errorNumbersToAdd: IEnumerable<System_Internal.Int32>): SqlServerDbContextOptionsBuilder;
    UseAzureSqlDefaults(enable?: boolean): SqlServerDbContextOptionsBuilder;
    UseCompatibilityLevel(compatibilityLevel: int): SqlServerDbContextOptionsBuilder;
}


export const SqlServerDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): SqlServerDbContextOptionsBuilder;
};


export type SqlServerDbContextOptionsBuilder = SqlServerDbContextOptionsBuilder$instance;

