// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Abstractions
// Assembly: Microsoft.IdentityModel.Abstractions

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IDictionary, IReadOnlyDictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, DateTime, Double, Enum, Guid, IComparable, IConvertible, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export enum EventLogLevel {
    logAlways = 0,
    critical = 1,
    error = 2,
    warning = 3,
    informational = 4,
    verbose = 5
}


export interface IIdentityLogger$instance {
    isEnabled(eventLogLevel: EventLogLevel): boolean;
    log(entry: LogEntry): void;
}


export type IIdentityLogger = IIdentityLogger$instance;

export interface ITelemetryClient$instance {
    clientId: string;
    initialize(): void;
    isEnabled(): boolean;
    isEnabled(eventName: string): boolean;
    trackEvent(eventDetails: TelemetryEventDetails): void;
    trackEvent(eventName: string, stringProperties?: IDictionary<System_Internal.String, System_Internal.String>, longProperties?: IDictionary<System_Internal.String, System_Internal.Int64>, boolProperties?: IDictionary<System_Internal.String, System_Internal.Boolean>, dateTimeProperties?: IDictionary<System_Internal.String, DateTime>, doubleProperties?: IDictionary<System_Internal.String, System_Internal.Double>, guidProperties?: IDictionary<System_Internal.String, Guid>): void;
}


export type ITelemetryClient = ITelemetryClient$instance;

export interface LogEntry$instance {
    get correlationId(): string | undefined;
    set correlationId(value: string);
    eventLogLevel: EventLogLevel;
    get message(): string | undefined;
    set message(value: string);
}


export const LogEntry: {
    new(): LogEntry;
};


export type LogEntry = LogEntry$instance;

export interface NullIdentityModelLogger$instance {
    isEnabled(eventLogLevel: EventLogLevel): boolean;
    log(entry: LogEntry): void;
}


export const NullIdentityModelLogger: {
    new(): NullIdentityModelLogger;
    readonly instance: NullIdentityModelLogger;
};


export interface __NullIdentityModelLogger$views {
    As_IIdentityLogger(): IIdentityLogger$instance;
}

export interface NullIdentityModelLogger$instance extends IIdentityLogger$instance {}

export type NullIdentityModelLogger = NullIdentityModelLogger$instance & __NullIdentityModelLogger$views;


export interface NullTelemetryClient$instance {
    clientId: string;
    initialize(): void;
    isEnabled(): boolean;
    isEnabled(eventName: string): boolean;
    trackEvent(eventDetails: TelemetryEventDetails): void;
    trackEvent(eventName: string, stringProperties?: IDictionary<System_Internal.String, System_Internal.String>, longProperties?: IDictionary<System_Internal.String, System_Internal.Int64>, boolProperties?: IDictionary<System_Internal.String, System_Internal.Boolean>, dateTimeProperties?: IDictionary<System_Internal.String, DateTime>, doubleProperties?: IDictionary<System_Internal.String, System_Internal.Double>, guidProperties?: IDictionary<System_Internal.String, Guid>): void;
}


export const NullTelemetryClient: {
    new(): NullTelemetryClient;
    readonly instance: NullTelemetryClient;
};


export interface __NullTelemetryClient$views {
    As_ITelemetryClient(): ITelemetryClient$instance;
}

export interface NullTelemetryClient$instance extends ITelemetryClient$instance {}

export type NullTelemetryClient = NullTelemetryClient$instance & __NullTelemetryClient$views;


export interface TelemetryEventDetails$instance {
    name: string;
    readonly properties: IReadOnlyDictionary<System_Internal.String, unknown>;
    setProperty(key: string, value: string): void;
    setProperty(key: string, value: long): void;
    setProperty(key: string, value: boolean): void;
    setProperty(key: string, value: DateTime): void;
    setProperty(key: string, value: double): void;
    setProperty(key: string, value: Guid): void;
}


export const TelemetryEventDetails: {
};


export type TelemetryEventDetails = TelemetryEventDetails$instance;

export abstract class ObservabilityConstants$instance {
    static readonly succeeded: string;
    static readonly duration: string;
    static readonly activityId: string;
    static readonly clientId: string;
}


export type ObservabilityConstants = ObservabilityConstants$instance;

