// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.AuthScheme.PoP
// Assembly: Microsoft.Identity.Client

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Byte, String as ClrString } from "@tsonic/dotnet/System.js";

export interface IPoPCryptoProvider$instance {
    readonly __tsonic_iface_Microsoft_Identity_Client_AuthScheme_PoP_IPoPCryptoProvider: never;

    readonly CannonicalPublicKeyJwk: string;
    readonly CryptographicAlgorithm: string;
    Sign(data: byte[]): byte[];
}


export type IPoPCryptoProvider = IPoPCryptoProvider$instance;

