// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.SqlClient.DataClassification
// Assembly: Microsoft.Data.SqlClient

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ReadOnlyCollection_1 } from "@tsonic/dotnet/System.Collections.ObjectModel/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export enum SensitivityRank {
    NOT_DEFINED = -1,
    NONE = 0,
    LOW = 10,
    MEDIUM = 20,
    HIGH = 30,
    CRITICAL = 40
}


export interface ColumnSensitivity$instance {
    readonly SensitivityProperties: ReadOnlyCollection_1<SensitivityProperty>;
}


export const ColumnSensitivity: {
    new(sensitivityProperties: IList_1<SensitivityProperty>): ColumnSensitivity;
};


export type ColumnSensitivity = ColumnSensitivity$instance;

export interface InformationType$instance {
    readonly Id: string;
    readonly Name: string;
}


export const InformationType: {
    new(name: string, id: string): InformationType;
};


export type InformationType = InformationType$instance;

export interface Label$instance {
    readonly Id: string;
    readonly Name: string;
}


export const Label: {
    new(name: string, id: string): Label;
};


export type Label = Label$instance;

export interface SensitivityClassification$instance {
    readonly ColumnSensitivities: ReadOnlyCollection_1<ColumnSensitivity>;
    readonly InformationTypes: ReadOnlyCollection_1<InformationType>;
    readonly Labels: ReadOnlyCollection_1<Label>;
    readonly SensitivityRank: SensitivityRank;
}


export const SensitivityClassification: {
    new(labels: IList_1<Label>, informationTypes: IList_1<InformationType>, columnSensitivity: IList_1<ColumnSensitivity>, sensitivityRank: SensitivityRank): SensitivityClassification;
};


export type SensitivityClassification = SensitivityClassification$instance;

export interface SensitivityProperty$instance {
    readonly InformationType: InformationType;
    readonly Label: Label;
    readonly SensitivityRank: SensitivityRank;
}


export const SensitivityProperty: {
    new(label: Label, informationType: InformationType, sensitivityRank: SensitivityRank): SensitivityProperty;
};


export type SensitivityProperty = SensitivityProperty$instance;

