// Generated by tsbindgen - Extension Method Buckets
// This file contains bucket interfaces for C# extension methods.
// Buckets are scoped by declaring namespace (C# using semantics).
// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.

// Import namespace modules for cross-namespace type references
import * as Azure_Core_Serialization from "../../Azure.Core.Serialization/internal/index.js";
import * as Microsoft_Identity_Client from "../../Microsoft.Identity.Client/internal/index.js";
import * as Microsoft_Identity_Client_Extensibility from "../../Microsoft.Identity.Client.Extensibility/internal/index.js";
import * as System from "../../System/internal/index.js";

// Import primitive type aliases
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import CLR type aliases for generic type arguments
import * as System_Internal from "../../System/internal/index.js";

// Import unsafe type markers
import type { ptr } from '@tsonic/core/types.js';

export interface __Ext_Azure_BinaryData {
  toObject<T>(serializer: Azure_Core_Serialization.ObjectSerializer, cancellationToken: CancellationToken): ExtensionMethods_Azure<T | undefined>;
  toObjectAsync<T>(serializer: Azure_Core_Serialization.ObjectSerializer, cancellationToken: CancellationToken): ExtensionMethods_Azure<ValueTask_1<T>>;
  toObjectFromJson(): ExtensionMethods_Azure<unknown | undefined>;
  toDynamicFromJson(): ExtensionMethods_Azure<unknown>;
  toDynamicFromJson(propertyNameFormat: Azure_Core_Serialization.JsonPropertyNames, dateTimeFormat: string): ExtensionMethods_Azure<unknown>;
}

export interface __Ext_Microsoft_Identity_Client_IAccount {
  getTenantProfiles(): ExtensionMethods_Microsoft_Identity_Client<IEnumerable_1<Microsoft_Identity_Client.TenantProfile>>;
}

export interface __Ext_Microsoft_Identity_Client_IConfidentialClientApplication {
  getCertificate(): ExtensionMethods_Microsoft_Identity_Client<X509Certificate2>;
}

export interface __Ext_Microsoft_Identity_Client_IPublicClientApplication {
  isProofOfPossessionSupportedByClient(): ExtensionMethods_Microsoft_Identity_Client<boolean>;
  isSystemWebViewAvailable(): ExtensionMethods_Microsoft_Identity_Client<boolean>;
  isEmbeddedWebViewAvailable(): ExtensionMethods_Microsoft_Identity_Client<boolean>;
  isUserInteractive(): ExtensionMethods_Microsoft_Identity_Client<boolean>;
}

export interface __Ext_Microsoft_Identity_Client_ITokenCache {
  setCacheOptions(options: Microsoft_Identity_Client.CacheOptions): ExtensionMethods_Microsoft_Identity_Client<void>;
}

export interface __Ext_Microsoft_Identity_Client_Advanced_AbstractAcquireTokenParameterBuilder_1<T> {
  withExtraHttpHeaders(extraHttpHeaders: IDictionary_2<System_Internal.String, System_Internal.String>): ExtensionMethods_Microsoft_Identity_Client_Advanced<T>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_AbstractAcquireTokenParameterBuilder_1<T> {
  onBeforeTokenRequest(onBeforeTokenRequestHandler: Func_2<Microsoft_Identity_Client_Extensibility.OnBeforeTokenRequestData, Task>): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<T>>;
  withProofOfPosessionKeyId(keyId: string, expectedTokenTypeFromAad: string): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<T>>;
  withAuthenticationExtension(authenticationExtension: Microsoft_Identity_Client_Extensibility.MsalAuthenticationExtension): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<T>>;
  withAdditionalCacheParameters(cacheParameters: IEnumerable_1<System_Internal.String>): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<T>>;
  withFmiPathForClientAssertion(fmiPath: string): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<T>>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenForClientParameterBuilder {
  withProofOfPosessionKeyId(keyId: string, expectedTokenTypeFromAad: string): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AcquireTokenForClientParameterBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenInteractiveParameterBuilder {
  withCustomWebUi(customWebUi: Microsoft_Identity_Client_Extensibility.ICustomWebUi): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AcquireTokenInteractiveParameterBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenOnBehalfOfParameterBuilder {
  withSearchInCacheForLongRunningProcess(searchInCache: boolean): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.AcquireTokenOnBehalfOfParameterBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_ConfidentialClientApplicationBuilder {
  withAppTokenProvider(appTokenProvider: Func_2<Microsoft_Identity_Client_Extensibility.AppTokenProviderParameters, Task_1<Microsoft_Identity_Client_Extensibility.AppTokenProviderResult>>): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Microsoft_Identity_Client.ConfidentialClientApplicationBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_Extensibility_ILongRunningWebApi {
  stopLongRunningProcessInWebApiAsync(longRunningProcessSessionKey: string, cancellationToken: CancellationToken): ExtensionMethods_Microsoft_Identity_Client_Extensibility<Task_1<System_Internal.Boolean>>;
}

export interface __Ext_Microsoft_Identity_Client_RP_AcquireTokenForClientParameterBuilder {
  withAccessTokenSha256ToRefresh(hash: string): ExtensionMethods_Microsoft_Identity_Client_RP<Microsoft_Identity_Client.AcquireTokenForClientParameterBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_RP_ConfidentialClientApplicationBuilder {
  withCertificate(certificate: X509Certificate2, sendX5C: boolean, associateTokensWithCertificateSerialNumber: boolean): ExtensionMethods_Microsoft_Identity_Client_RP<Microsoft_Identity_Client.ConfidentialClientApplicationBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_SSHCertificates_AcquireTokenInteractiveParameterBuilder {
  withSSHCertificateAuthenticationScheme(publicKeyJwk: string, keyId: string): ExtensionMethods_Microsoft_Identity_Client_SSHCertificates<Microsoft_Identity_Client.AcquireTokenInteractiveParameterBuilder>;
}

export interface __Ext_Microsoft_Identity_Client_SSHCertificates_AcquireTokenSilentParameterBuilder {
  withSSHCertificateAuthenticationScheme(publicKeyJwk: string, keyId: string): ExtensionMethods_Microsoft_Identity_Client_SSHCertificates<Microsoft_Identity_Client.AcquireTokenSilentParameterBuilder>;
}

// Generic helper type for extension methods in namespace: Azure
export type ExtensionMethods_Azure<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends System.BinaryData ? __Ext_Azure_BinaryData : {})
  );

// Generic helper type for extension methods in namespace: Microsoft.Identity.Client
export type ExtensionMethods_Microsoft_Identity_Client<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends Microsoft_Identity_Client.IAccount ? __Ext_Microsoft_Identity_Client_IAccount : {}) &
    (TShape extends Microsoft_Identity_Client.IConfidentialClientApplication ? __Ext_Microsoft_Identity_Client_IConfidentialClientApplication : {}) &
    (TShape extends Microsoft_Identity_Client.IPublicClientApplication ? __Ext_Microsoft_Identity_Client_IPublicClientApplication : {}) &
    (TShape extends Microsoft_Identity_Client.ITokenCache ? __Ext_Microsoft_Identity_Client_ITokenCache : {})
  );

// Generic helper type for extension methods in namespace: Microsoft.Identity.Client.Advanced
export type ExtensionMethods_Microsoft_Identity_Client_Advanced<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<infer T0> ? __Ext_Microsoft_Identity_Client_Advanced_AbstractAcquireTokenParameterBuilder_1<T0> : {})
  );

// Generic helper type for extension methods in namespace: Microsoft.Identity.Client.Extensibility
export type ExtensionMethods_Microsoft_Identity_Client_Extensibility<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends Microsoft_Identity_Client.AbstractAcquireTokenParameterBuilder_1<infer T0> ? __Ext_Microsoft_Identity_Client_Extensibility_AbstractAcquireTokenParameterBuilder_1<T0> : {}) &
    (TShape extends Microsoft_Identity_Client.AcquireTokenForClientParameterBuilder ? __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenForClientParameterBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.AcquireTokenInteractiveParameterBuilder ? __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenInteractiveParameterBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.AcquireTokenOnBehalfOfParameterBuilder ? __Ext_Microsoft_Identity_Client_Extensibility_AcquireTokenOnBehalfOfParameterBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.ConfidentialClientApplicationBuilder ? __Ext_Microsoft_Identity_Client_Extensibility_ConfidentialClientApplicationBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.ILongRunningWebApi ? __Ext_Microsoft_Identity_Client_Extensibility_ILongRunningWebApi : {})
  );

// Generic helper type for extension methods in namespace: Microsoft.Identity.Client.RP
export type ExtensionMethods_Microsoft_Identity_Client_RP<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends Microsoft_Identity_Client.AcquireTokenForClientParameterBuilder ? __Ext_Microsoft_Identity_Client_RP_AcquireTokenForClientParameterBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.ConfidentialClientApplicationBuilder ? __Ext_Microsoft_Identity_Client_RP_ConfidentialClientApplicationBuilder : {})
  );

// Generic helper type for extension methods in namespace: Microsoft.Identity.Client.SSHCertificates
export type ExtensionMethods_Microsoft_Identity_Client_SSHCertificates<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends Microsoft_Identity_Client.AcquireTokenInteractiveParameterBuilder ? __Ext_Microsoft_Identity_Client_SSHCertificates_AcquireTokenInteractiveParameterBuilder : {}) &
    (TShape extends Microsoft_Identity_Client.AcquireTokenSilentParameterBuilder ? __Ext_Microsoft_Identity_Client_SSHCertificates_AcquireTokenSilentParameterBuilder : {})
  );

