// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal
// Assembly: Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { IAsyncDisposable, IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { IAnnotation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IColumn, IRelationalModel, ITable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { HistoryRepository, HistoryRepositoryDependencies, IHistoryRepository, IMigrationsAnnotationProvider, IMigrationsDatabaseLock, LockReleaseBehavior, MigrationsAnnotationProvider, MigrationsAnnotationProviderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { IRelationalCommand, RelationalCommandParameterObject } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface SqlServerHistoryRepository$instance extends HistoryRepository {
    readonly lockReleaseBehavior: LockReleaseBehavior;
    acquireDatabaseLock(): IMigrationsDatabaseLock;
    acquireDatabaseLockAsync(cancellationToken?: CancellationToken): Task<IMigrationsDatabaseLock>;
    getBeginIfExistsScript(migrationId: string): string;
    getBeginIfNotExistsScript(migrationId: string): string;
    getCreateIfNotExistsScript(): string;
    getEndIfScript(): string;
}


export const SqlServerHistoryRepository: {
    new(dependencies: HistoryRepositoryDependencies): SqlServerHistoryRepository;
};


export type SqlServerHistoryRepository = SqlServerHistoryRepository$instance;

export interface SqlServerMigrationDatabaseLock$instance {
    readonly historyRepository: IHistoryRepository;
    dispose(): void;
    disposeAsync(): ValueTask;
}


export const SqlServerMigrationDatabaseLock: {
    new(releaseLockCommand: IRelationalCommand, relationalCommandParameters: RelationalCommandParameterObject, historyRepository: IHistoryRepository, cancellationToken: CancellationToken): SqlServerMigrationDatabaseLock;
};


export type SqlServerMigrationDatabaseLock = SqlServerMigrationDatabaseLock$instance;

export interface SqlServerMigrationsAnnotationProvider$instance extends MigrationsAnnotationProvider {
    forRemove(model: IRelationalModel): IEnumerable<IAnnotation>;
    forRemove(table: ITable): IEnumerable<IAnnotation>;
    forRemove(column: IColumn): IEnumerable<IAnnotation>;
    forRename(table: ITable): IEnumerable<IAnnotation>;
    forRename(column: IColumn): IEnumerable<IAnnotation>;
}


export const SqlServerMigrationsAnnotationProvider: {
    new(dependencies: MigrationsAnnotationProviderDependencies): SqlServerMigrationsAnnotationProvider;
};


export type SqlServerMigrationsAnnotationProvider = SqlServerMigrationsAnnotationProvider$instance;

