// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal
// Assembly: Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, IAsyncDisposable, IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { IAnnotation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IColumn, IRelationalModel, ITable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { HistoryRepository, HistoryRepositoryDependencies, IHistoryRepository, IMigrationsAnnotationProvider, IMigrationsDatabaseLock, LockReleaseBehavior, MigrationsAnnotationProvider, MigrationsAnnotationProviderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { IRelationalCommand, RelationalCommandParameterObject } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface SqlServerHistoryRepository$instance extends HistoryRepository {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IHistoryRepository: never;

    readonly ExistsSql: string;
    readonly LockReleaseBehavior: LockReleaseBehavior;
    AcquireDatabaseLock(): IMigrationsDatabaseLock;
    AcquireDatabaseLockAsync(cancellationToken?: CancellationToken): Task<IMigrationsDatabaseLock>;
    GetBeginIfExistsScript(migrationId: string): string;
    GetBeginIfNotExistsScript(migrationId: string): string;
    GetCreateIfNotExistsScript(): string;
    GetEndIfScript(): string;
    InterpretExistsResult(value: unknown): boolean;
}


export const SqlServerHistoryRepository: {
    new(dependencies: HistoryRepositoryDependencies): SqlServerHistoryRepository;
};


export type SqlServerHistoryRepository = SqlServerHistoryRepository$instance;

export interface SqlServerMigrationDatabaseLock$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsDatabaseLock: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly HistoryRepository: IHistoryRepository;
    Dispose(): void;
    DisposeAsync(): ValueTask;
}


export const SqlServerMigrationDatabaseLock: {
    new(releaseLockCommand: IRelationalCommand, relationalCommandParameters: RelationalCommandParameterObject, historyRepository: IHistoryRepository, cancellationToken: CancellationToken): SqlServerMigrationDatabaseLock;
};


export type SqlServerMigrationDatabaseLock = SqlServerMigrationDatabaseLock$instance;

export interface SqlServerMigrationsAnnotationProvider$instance extends MigrationsAnnotationProvider {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsAnnotationProvider: never;

    ForRemove(model: IRelationalModel): IEnumerable<IAnnotation>;
    ForRemove(table: ITable): IEnumerable<IAnnotation>;
    ForRemove(column: IColumn): IEnumerable<IAnnotation>;
    ForRename(table: ITable): IEnumerable<IAnnotation>;
    ForRename(column: IColumn): IEnumerable<IAnnotation>;
}


export const SqlServerMigrationsAnnotationProvider: {
    new(dependencies: MigrationsAnnotationProviderDependencies): SqlServerMigrationsAnnotationProvider;
};


export type SqlServerMigrationsAnnotationProvider = SqlServerMigrationsAnnotationProvider$instance;

