// Generated by dotnet-bindgen - Architecture
// Namespace: System.Configuration.Internal
// Assembly: System.Configuration.ConfigurationManager

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { Configuration, ConfigurationAllowDefinition, ConfigurationAllowExeDefinition, ProtectedConfigurationProvider, ProtectedConfigurationSection } from "../../System.Configuration/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { PermissionSet } from "@tsonic/dotnet/System.Security/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { AsyncCallback, Boolean as ClrBoolean, EventArgs, IAsyncResult, ICloneable, IDisposable, Int32, IntPtr, MulticastDelegate, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System/internal/index.js";

export type InternalConfigEventHandler = (sender: unknown, e: InternalConfigEventArgs) => void;


export type StreamChangeCallback = (streamName: string) => void;


export interface IConfigErrorInfo$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IConfigErrorInfo: never;

    readonly Filename: string;
    readonly LineNumber: int;
}


export type IConfigErrorInfo = IConfigErrorInfo$instance;

export interface IConfigSystem$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IConfigSystem: never;

    readonly Host: IInternalConfigHost;
    readonly Root: IInternalConfigRoot;
    Init(typeConfigHost: Type, ...hostInitParams: unknown[]): void;
}


export type IConfigSystem = IConfigSystem$instance;

export interface IConfigurationManagerHelper$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IConfigurationManagerHelper: never;

    EnsureNetConfigLoaded(): void;
}


export type IConfigurationManagerHelper = IConfigurationManagerHelper$instance;

export interface IConfigurationManagerInternal$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IConfigurationManagerInternal: never;

    readonly SupportsUserConfig: boolean;
    readonly SetConfigurationSystemInProgress: boolean;
    readonly MachineConfigPath: string;
    readonly ApplicationConfigUri: string;
    readonly ExeProductName: string;
    readonly ExeProductVersion: string;
    readonly ExeRoamingConfigDirectory: string;
    readonly ExeRoamingConfigPath: string;
    readonly ExeLocalConfigDirectory: string;
    readonly ExeLocalConfigPath: string;
    readonly UserConfigFilename: string;
}


export type IConfigurationManagerInternal = IConfigurationManagerInternal$instance;

export interface IInternalConfigClientHost$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigClientHost: never;

    GetExeConfigPath(): string;
    IsExeConfig(configPath: string): boolean;
}


export type IInternalConfigClientHost = IInternalConfigClientHost$instance;

export interface IInternalConfigConfigurationFactory$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigConfigurationFactory: never;

    Create(typeConfigHost: Type, ...hostInitConfigurationParams: unknown[]): Configuration;
    NormalizeLocationSubPath(subPath: string, errorInfo: IConfigErrorInfo): string;
}


export type IInternalConfigConfigurationFactory = IInternalConfigConfigurationFactory$instance;

export interface IInternalConfigHost$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigHost: never;

    readonly SupportsChangeNotifications: boolean;
    readonly SupportsRefresh: boolean;
    readonly SupportsPath: boolean;
    readonly SupportsLocation: boolean;
    readonly IsRemote: boolean;
    CreateConfigurationContext(configPath: string, locationSubPath: string): unknown;
    DecryptSection(encryptedXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    DeleteStream(streamName: string): void;
    GetConfigType(typeName: string, throwOnError: boolean): Type;
    GetConfigTypeName(t: Type): string;
    GetRestrictedPermissions(configRecord: IInternalConfigRecord, permissionSet: PermissionSet, isHostReady: boolean): void;
    GetStreamName(configPath: string): string;
    GetStreamNameForConfigSource(streamName: string, configSource: string): string;
    GetStreamVersion(streamName: string): unknown;
    Impersonate(): IDisposable;
    Init(configRoot: IInternalConfigRoot, ...hostInitParams: unknown[]): void;
    InitForConfiguration(locationSubPath: string, configPath: string, locationConfigPath: string, configRoot: IInternalConfigRoot, ...hostInitConfigurationParams: unknown[]): void;
    IsConfigRecordRequired(configPath: string): boolean;
    IsDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition): boolean;
    IsInitDelayed(configRecord: IInternalConfigRecord): boolean;
    OpenStreamForRead(streamName: string, assertPermissions: boolean): Stream;
    OpenStreamForRead(streamName: string): Stream;
    OpenStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown, assertPermissions: boolean): Stream;
    OpenStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown): Stream;
    PrefetchAll(configPath: string, streamName: string): boolean;
    RequireCompleteInit(configRecord: IInternalConfigRecord): void;
    StartMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): unknown;
    StopMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): void;
    VerifyDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition, errorInfo: IConfigErrorInfo): void;
    WriteCompleted(streamName: string, success: boolean, writeContext: unknown, assertPermissions: boolean): void;
    WriteCompleted(streamName: string, success: boolean, writeContext: unknown): void;
}


export type IInternalConfigHost = IInternalConfigHost$instance;

export interface IInternalConfigRecord$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigRecord: never;

    readonly ConfigPath: string;
    readonly StreamName: string;
    readonly HasInitErrors: boolean;
    GetSection(configKey: string): unknown;
    RefreshSection(configKey: string): void;
    ThrowIfInitErrors(): void;
}


export type IInternalConfigRecord = IInternalConfigRecord$instance;

export interface IInternalConfigRoot$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigRoot: never;

    readonly IsDesignTime: boolean;
    GetSection(section: string, configPath: string): unknown;
    GetUniqueConfigPath(configPath: string): string;
    GetUniqueConfigRecord(configPath: string): IInternalConfigRecord;
    Init(host: IInternalConfigHost, isDesignTime: boolean): void;
    RemoveConfig(configPath: string): void;
}


export type IInternalConfigRoot = IInternalConfigRoot$instance;

export interface IInternalConfigSettingsFactory$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigSettingsFactory: never;

    CompleteInit(): void;
    SetConfigurationSystem(internalConfigSystem: IInternalConfigSystem, initComplete: boolean): void;
}


export type IInternalConfigSettingsFactory = IInternalConfigSettingsFactory$instance;

export interface IInternalConfigSystem$instance {
    readonly __tsonic_iface_System_Configuration_Internal_IInternalConfigSystem: never;

    readonly SupportsUserConfig: boolean;
    GetSection(configKey: string): unknown;
    RefreshConfig(sectionName: string): void;
}


export type IInternalConfigSystem = IInternalConfigSystem$instance;

export interface DelegatingConfigHost$instance {
    readonly __tsonic_type_System_Configuration_Internal_DelegatingConfigHost: never;

    readonly HasLocalConfig: boolean;
    readonly HasRoamingConfig: boolean;
    readonly IsAppConfigHttp: boolean;
    readonly IsRemote: boolean;
    readonly SupportsChangeNotifications: boolean;
    readonly SupportsLocation: boolean;
    readonly SupportsPath: boolean;
    readonly SupportsRefresh: boolean;
    CreateConfigurationContext(configPath: string, locationSubPath: string): unknown;
    CreateDeprecatedConfigContext(configPath: string): unknown;
    DecryptSection(encryptedXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    DeleteStream(streamName: string): void;
    EncryptSection(clearTextXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    GetConfigPathFromLocationSubPath(configPath: string, locationSubPath: string): string;
    GetConfigType(typeName: string, throwOnError: boolean): Type;
    GetConfigTypeName(t: Type): string;
    GetRestrictedPermissions(configRecord: IInternalConfigRecord, permissionSet: PermissionSet, isHostReady: boolean): void;
    GetStreamName(configPath: string): string;
    GetStreamNameForConfigSource(streamName: string, configSource: string): string;
    GetStreamVersion(streamName: string): unknown;
    Impersonate(): IDisposable;
    Init(configRoot: IInternalConfigRoot, ...hostInitParams: unknown[]): void;
    InitForConfiguration(locationSubPath: string, configPath: string, locationConfigPath: string, configRoot: IInternalConfigRoot, ...hostInitConfigurationParams: unknown[]): void;
    IsAboveApplication(configPath: string): boolean;
    IsConfigRecordRequired(configPath: string): boolean;
    IsDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition): boolean;
    IsFile(streamName: string): boolean;
    IsFullTrustSectionWithoutAptcaAllowed(configRecord: IInternalConfigRecord): boolean;
    IsInitDelayed(configRecord: IInternalConfigRecord): boolean;
    IsLocationApplicable(configPath: string): boolean;
    IsSecondaryRoot(configPath: string): boolean;
    IsTrustedConfigPath(configPath: string): boolean;
    OpenStreamForRead(streamName: string): Stream;
    OpenStreamForRead(streamName: string, assertPermissions: boolean): Stream;
    OpenStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown): Stream;
    OpenStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown, assertPermissions: boolean): Stream;
    PrefetchAll(configPath: string, streamName: string): boolean;
    PrefetchSection(sectionGroupName: string, sectionName: string): boolean;
    RefreshConfigPaths(): void;
    RequireCompleteInit(configRecord: IInternalConfigRecord): void;
    StartMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): unknown;
    StopMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): void;
    VerifyDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition, errorInfo: IConfigErrorInfo): void;
    WriteCompleted(streamName: string, success: boolean, writeContext: unknown): void;
    WriteCompleted(streamName: string, success: boolean, writeContext: unknown, assertPermissions: boolean): void;
}


export const DelegatingConfigHost: (abstract new() => DelegatingConfigHost) & {
};


export type DelegatingConfigHost = DelegatingConfigHost$instance;

export interface InternalConfigEventArgs$instance extends EventArgs {
    readonly __tsonic_type_System_Configuration_Internal_InternalConfigEventArgs: never;

    ConfigPath: string;
}


export const InternalConfigEventArgs: {
    new(configPath: string): InternalConfigEventArgs;
};


export type InternalConfigEventArgs = InternalConfigEventArgs$instance;

