// Generated by tsbindgen - Architecture
// Namespace: System.Configuration.Internal
// Assembly: System.Configuration.ConfigurationManager

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { Configuration, ConfigurationAllowDefinition, ConfigurationAllowExeDefinition, ProtectedConfigurationProvider, ProtectedConfigurationSection } from "../../System.Configuration/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { AsyncCallback, Boolean as ClrBoolean, EventArgs, IAsyncResult, ICloneable, IDisposable, Int32, IntPtr, MulticastDelegate, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { PermissionSet } from "@tsonic/dotnet/System.Security.js";

export type InternalConfigEventHandler = (sender: unknown, e: InternalConfigEventArgs) => void;


export type StreamChangeCallback = (streamName: string) => void;


export interface IConfigErrorInfo$instance {
    readonly filename: string;
    readonly lineNumber: int;
}


export type IConfigErrorInfo = IConfigErrorInfo$instance;

export interface IConfigSystem$instance {
    readonly host: IInternalConfigHost;
    readonly root: IInternalConfigRoot;
    init(typeConfigHost: Type, ...hostInitParams: unknown[]): void;
}


export type IConfigSystem = IConfigSystem$instance;

export interface IConfigurationManagerHelper$instance {
    ensureNetConfigLoaded(): void;
}


export type IConfigurationManagerHelper = IConfigurationManagerHelper$instance;

export interface IConfigurationManagerInternal$instance {
    readonly supportsUserConfig: boolean;
    readonly setConfigurationSystemInProgress: boolean;
    readonly machineConfigPath: string;
    readonly applicationConfigUri: string;
    readonly exeProductName: string;
    readonly exeProductVersion: string;
    readonly exeRoamingConfigDirectory: string;
    readonly exeRoamingConfigPath: string;
    readonly exeLocalConfigDirectory: string;
    readonly exeLocalConfigPath: string;
    readonly userConfigFilename: string;
}


export type IConfigurationManagerInternal = IConfigurationManagerInternal$instance;

export interface IInternalConfigClientHost$instance {
    getExeConfigPath(): string;
    isExeConfig(configPath: string): boolean;
}


export type IInternalConfigClientHost = IInternalConfigClientHost$instance;

export interface IInternalConfigConfigurationFactory$instance {
    create(typeConfigHost: Type, ...hostInitConfigurationParams: unknown[]): Configuration;
    normalizeLocationSubPath(subPath: string, errorInfo: IConfigErrorInfo): string;
}


export type IInternalConfigConfigurationFactory = IInternalConfigConfigurationFactory$instance;

export interface IInternalConfigHost$instance {
    readonly supportsChangeNotifications: boolean;
    readonly supportsRefresh: boolean;
    readonly supportsPath: boolean;
    readonly supportsLocation: boolean;
    readonly isRemote: boolean;
    createConfigurationContext(configPath: string, locationSubPath: string): unknown;
    decryptSection(encryptedXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    deleteStream(streamName: string): void;
    getConfigType(typeName: string, throwOnError: boolean): Type;
    getConfigTypeName(t: Type): string;
    getRestrictedPermissions(configRecord: IInternalConfigRecord, permissionSet: PermissionSet, isHostReady: boolean): void;
    getStreamName(configPath: string): string;
    getStreamNameForConfigSource(streamName: string, configSource: string): string;
    getStreamVersion(streamName: string): unknown;
    impersonate(): IDisposable;
    init(configRoot: IInternalConfigRoot, ...hostInitParams: unknown[]): void;
    initForConfiguration(locationSubPath: string, configPath: string, locationConfigPath: string, configRoot: IInternalConfigRoot, ...hostInitConfigurationParams: unknown[]): void;
    isConfigRecordRequired(configPath: string): boolean;
    isDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition): boolean;
    isInitDelayed(configRecord: IInternalConfigRecord): boolean;
    openStreamForRead(streamName: string, assertPermissions: boolean): Stream;
    openStreamForRead(streamName: string): Stream;
    openStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown, assertPermissions: boolean): Stream;
    openStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown): Stream;
    prefetchAll(configPath: string, streamName: string): boolean;
    requireCompleteInit(configRecord: IInternalConfigRecord): void;
    startMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): unknown;
    stopMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): void;
    verifyDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition, errorInfo: IConfigErrorInfo): void;
    writeCompleted(streamName: string, success: boolean, writeContext: unknown, assertPermissions: boolean): void;
    writeCompleted(streamName: string, success: boolean, writeContext: unknown): void;
}


export type IInternalConfigHost = IInternalConfigHost$instance;

export interface IInternalConfigRecord$instance {
    readonly configPath: string;
    readonly streamName: string;
    readonly hasInitErrors: boolean;
    getSection(configKey: string): unknown;
    refreshSection(configKey: string): void;
    throwIfInitErrors(): void;
}


export type IInternalConfigRecord = IInternalConfigRecord$instance;

export interface IInternalConfigRoot$instance {
    readonly isDesignTime: boolean;
    getSection(section: string, configPath: string): unknown;
    getUniqueConfigPath(configPath: string): string;
    getUniqueConfigRecord(configPath: string): IInternalConfigRecord;
    init(host: IInternalConfigHost, isDesignTime: boolean): void;
    removeConfig(configPath: string): void;
}


export type IInternalConfigRoot = IInternalConfigRoot$instance;

export interface IInternalConfigSettingsFactory$instance {
    completeInit(): void;
    setConfigurationSystem(internalConfigSystem: IInternalConfigSystem, initComplete: boolean): void;
}


export type IInternalConfigSettingsFactory = IInternalConfigSettingsFactory$instance;

export interface IInternalConfigSystem$instance {
    readonly supportsUserConfig: boolean;
    getSection(configKey: string): unknown;
    refreshConfig(sectionName: string): void;
}


export type IInternalConfigSystem = IInternalConfigSystem$instance;

export interface DelegatingConfigHost$instance {
    readonly hasLocalConfig: boolean;
    readonly hasRoamingConfig: boolean;
    readonly isAppConfigHttp: boolean;
    readonly isRemote: boolean;
    readonly supportsChangeNotifications: boolean;
    readonly supportsLocation: boolean;
    readonly supportsPath: boolean;
    readonly supportsRefresh: boolean;
    createConfigurationContext(configPath: string, locationSubPath: string): unknown;
    createDeprecatedConfigContext(configPath: string): unknown;
    decryptSection(encryptedXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    deleteStream(streamName: string): void;
    encryptSection(clearTextXml: string, protectionProvider: ProtectedConfigurationProvider, protectedConfigSection: ProtectedConfigurationSection): string;
    getConfigPathFromLocationSubPath(configPath: string, locationSubPath: string): string;
    getConfigType(typeName: string, throwOnError: boolean): Type;
    getConfigTypeName(t: Type): string;
    getRestrictedPermissions(configRecord: IInternalConfigRecord, permissionSet: PermissionSet, isHostReady: boolean): void;
    getStreamName(configPath: string): string;
    getStreamNameForConfigSource(streamName: string, configSource: string): string;
    getStreamVersion(streamName: string): unknown;
    impersonate(): IDisposable;
    init(configRoot: IInternalConfigRoot, ...hostInitParams: unknown[]): void;
    initForConfiguration(locationSubPath: string, configPath: string, locationConfigPath: string, configRoot: IInternalConfigRoot, ...hostInitConfigurationParams: unknown[]): void;
    isAboveApplication(configPath: string): boolean;
    isConfigRecordRequired(configPath: string): boolean;
    isDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition): boolean;
    isFile(streamName: string): boolean;
    isFullTrustSectionWithoutAptcaAllowed(configRecord: IInternalConfigRecord): boolean;
    isInitDelayed(configRecord: IInternalConfigRecord): boolean;
    isLocationApplicable(configPath: string): boolean;
    isSecondaryRoot(configPath: string): boolean;
    isTrustedConfigPath(configPath: string): boolean;
    openStreamForRead(streamName: string): Stream;
    openStreamForRead(streamName: string, assertPermissions: boolean): Stream;
    openStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown): Stream;
    openStreamForWrite(streamName: string, templateStreamName: string, writeContext: unknown, assertPermissions: boolean): Stream;
    prefetchAll(configPath: string, streamName: string): boolean;
    prefetchSection(sectionGroupName: string, sectionName: string): boolean;
    refreshConfigPaths(): void;
    requireCompleteInit(configRecord: IInternalConfigRecord): void;
    startMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): unknown;
    stopMonitoringStreamForChanges(streamName: string, callback: StreamChangeCallback): void;
    verifyDefinitionAllowed(configPath: string, allowDefinition: ConfigurationAllowDefinition, allowExeDefinition: ConfigurationAllowExeDefinition, errorInfo: IConfigErrorInfo): void;
    writeCompleted(streamName: string, success: boolean, writeContext: unknown): void;
    writeCompleted(streamName: string, success: boolean, writeContext: unknown, assertPermissions: boolean): void;
}


export const DelegatingConfigHost: {
    new(): DelegatingConfigHost;
};


export type DelegatingConfigHost = DelegatingConfigHost$instance;

export interface InternalConfigEventArgs$instance extends EventArgs {
    configPath: string;
}


export const InternalConfigEventArgs: {
    new(configPath: string): InternalConfigEventArgs;
};


export type InternalConfigEventArgs = InternalConfigEventArgs$instance;

