// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Diagnostics.Internal
// Assembly: Microsoft.EntityFrameworkCore.SqlServer

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Diagnostics_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { EventDefinitionBase, RelationalLoggingDefinitions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";

export interface SqlServerLoggingDefinitions$instance extends RelationalLoggingDefinitions {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_SqlServer_Diagnostics_Internal_SqlServerLoggingDefinitions: never;

    LogDecimalTypeKey: EventDefinitionBase | null;
    LogDefaultDecimalTypeColumn: EventDefinitionBase | null;
    LogByteIdentityColumn: EventDefinitionBase | null;
    LogColumnWithoutType: EventDefinitionBase | null;
    LogFoundDefaultSchema: EventDefinitionBase | null;
    LogFoundTypeAlias: EventDefinitionBase | null;
    LogFoundColumn: EventDefinitionBase | null;
    LogFoundForeignKey: EventDefinitionBase | null;
    LogPrincipalTableNotInSelectionSet: EventDefinitionBase | null;
    LogMissingSchema: EventDefinitionBase | null;
    LogMissingTable: EventDefinitionBase | null;
    LogFoundSequence: EventDefinitionBase | null;
    LogFoundTable: EventDefinitionBase | null;
    LogFoundIndex: EventDefinitionBase | null;
    LogFoundPrimaryKey: EventDefinitionBase | null;
    LogFoundUniqueConstraint: EventDefinitionBase | null;
    LogPrincipalColumnNotFound: EventDefinitionBase | null;
    LogReflexiveConstraintIgnored: EventDefinitionBase | null;
    LogDuplicateForeignKeyConstraintIgnored: EventDefinitionBase | null;
    LogPrincipalTableInformationNotFound: EventDefinitionBase | null;
    LogSavepointsDisabledBecauseOfMARS: EventDefinitionBase | null;
    LogConflictingValueGenerationStrategies: EventDefinitionBase | null;
    LogMissingViewDefinitionRights: EventDefinitionBase | null;
}


export const SqlServerLoggingDefinitions: {
    new(): SqlServerLoggingDefinitions;
};


export type SqlServerLoggingDefinitions = SqlServerLoggingDefinitions$instance;

