// Generated by tsbindgen - Architecture
// Namespace: Azure.Core.Pipeline
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { ClientOptions, DelayStrategy, HttpMessage, Request, RequestFailedDetailsParser, ResponseClassifier, TokenCredential, TokenRequestContext } from "../../Azure.Core/internal/index.js";
import type { RequestContext, Response } from "../../Azure/internal/index.js";
import type { IDictionary_2, IEnumerable_1, IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { HttpClient, HttpMessageHandler } from "@tsonic/dotnet/System.Net.Http/internal/index.js";
import type { SslPolicyErrors } from "@tsonic/dotnet/System.Net.Security/internal/index.js";
import type { X509Certificate2, X509Chain } from "@tsonic/dotnet/System.Security.Cryptography.X509Certificates/internal/index.js";
import type { ValueTask, ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Exception, Func_2, IDisposable, Int32, Object as ClrObject, ReadOnlyMemory_1, String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface BearerTokenAuthenticationPolicy$instance extends HttpPipelinePolicy {
    readonly __tsonic_type_Azure_Core_Pipeline_BearerTokenAuthenticationPolicy: never;

    AuthorizeRequest(message: HttpMessage): void;
    AuthorizeRequestAsync(message: HttpMessage): ValueTask;
    AuthorizeRequestOnChallenge(message: HttpMessage): boolean;
    AuthorizeRequestOnChallengeAsync(message: HttpMessage): ValueTask_1<System_Internal.Boolean>;
    Process(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
}


export const BearerTokenAuthenticationPolicy: {
    new(credential: TokenCredential, scope: string): BearerTokenAuthenticationPolicy;
    new(credential: TokenCredential, scopes: IEnumerable_1<System_Internal.String>): BearerTokenAuthenticationPolicy;
};


export type BearerTokenAuthenticationPolicy = BearerTokenAuthenticationPolicy$instance;

export interface DisposableHttpPipeline$instance extends HttpPipeline {
    readonly __tsonic_type_Azure_Core_Pipeline_DisposableHttpPipeline: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Dispose(): void;
}


export const DisposableHttpPipeline: {
};


export type DisposableHttpPipeline = DisposableHttpPipeline$instance;

export interface HttpClientTransport$instance extends HttpPipelineTransport {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpClientTransport: never;

    readonly __tsonic_iface_System_IDisposable: never;

    CreateRequest(): Request;
    Dispose(): void;
    Process(message: HttpMessage): void;
    ProcessAsync(message: HttpMessage): ValueTask;
}


export const HttpClientTransport: {
    new(): HttpClientTransport;
    new(messageHandler: HttpMessageHandler): HttpClientTransport;
    new(client: HttpClient): HttpClientTransport;
    readonly Shared: HttpClientTransport;
};


export type HttpClientTransport = HttpClientTransport$instance;

export interface HttpPipeline$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipeline: never;

    readonly ResponseClassifier: ResponseClassifier;
    CreateMessage(): HttpMessage;
    CreateMessage(context: RequestContext): HttpMessage;
    CreateMessage(context: RequestContext, classifier?: ResponseClassifier): HttpMessage;
    CreateRequest(): Request;
    Send(message: HttpMessage, cancellationToken: CancellationToken): void;
    SendAsync(message: HttpMessage, cancellationToken: CancellationToken): ValueTask;
    SendRequest(request: Request, cancellationToken: CancellationToken): Response;
    SendRequestAsync(request: Request, cancellationToken: CancellationToken): ValueTask_1<Response>;
}


export const HttpPipeline: {
    new(transport: HttpPipelineTransport, policies: HttpPipelinePolicy[], responseClassifier: ResponseClassifier): HttpPipeline;
    CreateClientRequestIdScope(clientRequestId: string): IDisposable;
    CreateHttpMessagePropertiesScope(messageProperties: IDictionary_2<System_Internal.String, unknown>): IDisposable;
};


export type HttpPipeline = HttpPipeline$instance;

export interface HttpPipelineOptions$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipelineOptions: never;

    readonly ClientOptions: ClientOptions;
    readonly PerCallPolicies: IList_1<HttpPipelinePolicy>;
    readonly PerRetryPolicies: IList_1<HttpPipelinePolicy>;
    RequestFailedDetailsParser: RequestFailedDetailsParser;
    get ResponseClassifier(): ResponseClassifier | undefined;
    set ResponseClassifier(value: ResponseClassifier | undefined);
}


export const HttpPipelineOptions: {
    new(options: ClientOptions): HttpPipelineOptions;
};


export type HttpPipelineOptions = HttpPipelineOptions$instance;

export interface HttpPipelinePolicy$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipelinePolicy: never;

    Process(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
}


export const HttpPipelinePolicy: (abstract new() => HttpPipelinePolicy) & {
    ProcessNext(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessNextAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
};


export type HttpPipelinePolicy = HttpPipelinePolicy$instance;

export interface HttpPipelineSynchronousPolicy$instance extends HttpPipelinePolicy {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipelineSynchronousPolicy: never;

    OnReceivedResponse(message: HttpMessage): void;
    OnSendingRequest(message: HttpMessage): void;
    Process(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
}


export const HttpPipelineSynchronousPolicy: (abstract new() => HttpPipelineSynchronousPolicy) & {
};


export type HttpPipelineSynchronousPolicy = HttpPipelineSynchronousPolicy$instance;

export interface HttpPipelineTransport$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipelineTransport: never;

    CreateRequest(): Request;
    Process(message: HttpMessage): void;
    ProcessAsync(message: HttpMessage): ValueTask;
}


export const HttpPipelineTransport: (abstract new() => HttpPipelineTransport) & {
};


export type HttpPipelineTransport = HttpPipelineTransport$instance;

export interface HttpPipelineTransportOptions$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_HttpPipelineTransportOptions: never;

    readonly ClientCertificates: IList_1<X509Certificate2>;
    IsClientRedirectEnabled: boolean;
    get ServerCertificateCustomValidationCallback(): Func_2<ServerCertificateCustomValidationArgs, System_Internal.Boolean> | undefined;
    set ServerCertificateCustomValidationCallback(value: Func_2<ServerCertificateCustomValidationArgs, System_Internal.Boolean> | undefined);
}


export const HttpPipelineTransportOptions: {
    new(): HttpPipelineTransportOptions;
};


export type HttpPipelineTransportOptions = HttpPipelineTransportOptions$instance;

export interface RedirectPolicy$instance extends HttpPipelinePolicy {
    readonly __tsonic_type_Azure_Core_Pipeline_RedirectPolicy: never;

    Process(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
}


export const RedirectPolicy: {
    SetAllowAutoRedirect(message: HttpMessage, allowAutoRedirect: boolean): void;
};


export type RedirectPolicy = RedirectPolicy$instance;

export interface RetryPolicy$instance extends HttpPipelinePolicy {
    readonly __tsonic_type_Azure_Core_Pipeline_RetryPolicy: never;

    OnRequestSent(message: HttpMessage): void;
    OnRequestSentAsync(message: HttpMessage): ValueTask;
    OnSendingRequest(message: HttpMessage): void;
    OnSendingRequestAsync(message: HttpMessage): ValueTask;
    Process(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): void;
    ProcessAsync(message: HttpMessage, pipeline: ReadOnlyMemory_1<HttpPipelinePolicy>): ValueTask;
    ShouldRetry(message: HttpMessage, exception: Exception): boolean;
    ShouldRetryAsync(message: HttpMessage, exception: Exception): ValueTask_1<System_Internal.Boolean>;
}


export const RetryPolicy: {
    new(maxRetries: int, delayStrategy: DelayStrategy): RetryPolicy;
};


export type RetryPolicy = RetryPolicy$instance;

export interface ServerCertificateCustomValidationArgs$instance {
    readonly __tsonic_type_Azure_Core_Pipeline_ServerCertificateCustomValidationArgs: never;

    readonly Certificate: X509Certificate2 | undefined;
    readonly CertificateAuthorityChain: X509Chain | undefined;
    readonly SslPolicyErrors: SslPolicyErrors;
}


export const ServerCertificateCustomValidationArgs: {
    new(certificate: X509Certificate2, certificateAuthorityChain: X509Chain, sslPolicyErrors: SslPolicyErrors): ServerCertificateCustomValidationArgs;
};


export type ServerCertificateCustomValidationArgs = ServerCertificateCustomValidationArgs$instance;

export abstract class HttpPipelineBuilder$instance {
    static Build(options: ClientOptions, perCallPolicies: HttpPipelinePolicy[], perRetryPolicies: HttpPipelinePolicy[], transportOptions: HttpPipelineTransportOptions, responseClassifier: ResponseClassifier): DisposableHttpPipeline;
    static Build(options: ClientOptions, perCallPolicies: HttpPipelinePolicy[], perRetryPolicies: HttpPipelinePolicy[], responseClassifier: ResponseClassifier): HttpPipeline;
    static Build(options: ClientOptions, ...perRetryPolicies: HttpPipelinePolicy[]): HttpPipeline;
    static Build(options: HttpPipelineOptions, transportOptions: HttpPipelineTransportOptions): DisposableHttpPipeline;
    static Build(options: HttpPipelineOptions): HttpPipeline;
}


export type HttpPipelineBuilder = HttpPipelineBuilder$instance;

