// Generated by tsbindgen - Architecture
// Namespace: Azure.Messaging
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { ContentType } from "../../Azure.Core/internal/index.js";
import type { BinaryData } from "../../System/internal/index.js";
import type { IDictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Lib from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, DateTimeOffset, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type } from "@tsonic/dotnet/System.js";

export enum CloudEventDataFormat {
    Binary = 0,
    Json = 1
}


export interface CloudEvent$instance {
    get Data(): BinaryData | undefined;
    set Data(value: BinaryData);
    get DataContentType(): string | undefined;
    set DataContentType(value: string);
    get DataSchema(): string | undefined;
    set DataSchema(value: string);
    readonly ExtensionAttributes: IDictionary<System_Internal.String, unknown>;
    Id: string;
    Source: string;
    get Subject(): string | undefined;
    set Subject(value: string);
    Time: Nullable<DateTimeOffset>;
    Type: string;
}


export const CloudEvent: {
    new(source: string, type: string, jsonSerializableData: unknown, dataSerializationType: Type): CloudEvent;
    new(source: string, type: string, data: BinaryData, dataContentType: string, dataFormat: CloudEventDataFormat): CloudEvent;
    Parse(json: BinaryData, skipValidation?: boolean): CloudEvent | undefined;
    ParseMany(json: BinaryData, skipValidation?: boolean): CloudEvent[];
};


export type CloudEvent = CloudEvent$instance;

export abstract class MessageContent$protected {
    protected ContentTypeCore: Nullable<ContentType>;
}


export interface MessageContent$instance extends MessageContent$protected {
    ContentType: Nullable<ContentType>;
    get Data(): BinaryData | undefined;
    set Data(value: BinaryData);
    readonly IsReadOnly: boolean;
}


export const MessageContent: {
    new(): MessageContent;
};


export type MessageContent = MessageContent$instance;

