// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Logging
// Assembly: Microsoft.IdentityModel.Logging

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { EventLogLevel, IIdentityLogger } from "../../Microsoft.IdentityModel.Abstractions/internal/index.js";
import type { ICollection, IDictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Diagnostics_Tracing_Internal from "@tsonic/dotnet/System.Diagnostics.Tracing.js";
import type { EventLevel, EventListener, EventSource } from "@tsonic/dotnet/System.Diagnostics.Tracing.js";
import type { StreamWriter } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { ArgumentException, ArgumentNullException, Boolean as ClrBoolean, Exception, Func, Guid, IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export interface ISafeLogSecurityArtifact$instance {
    unsafeToString(): string;
}


export type ISafeLogSecurityArtifact = ISafeLogSecurityArtifact$instance;

export interface IdentityModelEventSource$instance extends EventSource {
    logLevel: EventLevel;
    write(level: EventLevel, innerException: Exception, message: string): void;
    write(level: EventLevel, innerException: Exception, message: string, ...args: unknown[]): void;
    writeAlways(message: string): void;
    writeAlways(message: string, ...args: unknown[]): void;
    writeCritical(message: string): void;
    writeCritical(message: string, ...args: unknown[]): void;
    writeError(message: string): void;
    writeError(message: string, ...args: unknown[]): void;
    writeInformation(message: string): void;
    writeInformation(message: string, ...args: unknown[]): void;
    writeVerbose(message: string): void;
    writeVerbose(message: string, ...args: unknown[]): void;
    writeWarning(message: string): void;
    writeWarning(message: string, ...args: unknown[]): void;
}


export const IdentityModelEventSource: {
    new(): IdentityModelEventSource;
    readonly logger: IdentityModelEventSource;
    showPII: boolean;
    logCompleteSecurityArtifact: boolean;
    readonly hiddenPIIString: string;
    readonly hiddenSecurityArtifactString: string;
    headerWritten: boolean;
};


export type IdentityModelEventSource = IdentityModelEventSource$instance;

export interface LoggerContext$instance {
    activityId: Guid;
    captureLogs: boolean;
    debugId: string;
    readonly logs: ICollection<System_Internal.String>;
    propertyBag: IDictionary<System_Internal.String, unknown>;
}


export const LoggerContext: {
    new(): LoggerContext;
    new(activityId: Guid): LoggerContext;
};


export type LoggerContext = LoggerContext$instance;

export interface LogHelper$instance {
}


export const LogHelper: {
    new(): LogHelper;
    logger: IIdentityLogger;
    formatInvariant(format: string, ...args: unknown[]): string;
    isEnabled(level: EventLogLevel): boolean;
    logArgumentException<T extends ArgumentException>(eventLevel: EventLevel, argumentName: string, innerException: Exception, format: string, ...args: unknown[]): T;
    logArgumentException<T extends ArgumentException>(eventLevel: EventLevel, argumentName: string, innerException: Exception, message: string): T;
    logArgumentException<T extends ArgumentException>(eventLevel: EventLevel, argumentName: string, format: string, ...args: unknown[]): T;
    logArgumentException<T extends ArgumentException>(eventLevel: EventLevel, argumentName: string, message: string): T;
    logArgumentException<T extends ArgumentException>(argumentName: string, innerException: Exception, format: string, ...args: unknown[]): T;
    logArgumentException<T extends ArgumentException>(argumentName: string, innerException: Exception, message: string): T;
    logArgumentException<T extends ArgumentException>(argumentName: string, format: string, ...args: unknown[]): T;
    logArgumentException<T extends ArgumentException>(argumentName: string, message: string): T;
    logArgumentNullException(argument: string): ArgumentNullException;
    logException<T extends Exception>(eventLevel: EventLevel, innerException: Exception, format: string, ...args: unknown[]): T;
    logException<T extends Exception>(eventLevel: EventLevel, innerException: Exception, message: string): T;
    logException<T extends Exception>(eventLevel: EventLevel, format: string, ...args: unknown[]): T;
    logException<T extends Exception>(eventLevel: EventLevel, message: string): T;
    logException<T extends Exception>(innerException: Exception, format: string, ...args: unknown[]): T;
    logException<T extends Exception>(innerException: Exception, message: string): T;
    logException<T extends Exception>(format: string, ...args: unknown[]): T;
    logException<T extends Exception>(message: string): T;
    logExceptionMessage(eventLevel: EventLevel, exception: Exception): Exception;
    logExceptionMessage(exception: Exception): Exception;
    logInformation(message: string, ...args: unknown[]): void;
    logVerbose(message: string, ...args: unknown[]): void;
    logWarning(message: string, ...args: unknown[]): void;
    markAsNonPII(arg: unknown): unknown;
    markAsSecurityArtifact(arg: unknown, callback: Func<unknown, System_Internal.String>, callbackUnsafe: Func<unknown, System_Internal.String>): unknown;
    markAsSecurityArtifact(arg: unknown, callback: Func<unknown, System_Internal.String>): unknown;
    markAsUnsafeSecurityArtifact(arg: unknown, callbackUnsafe: Func<unknown, System_Internal.String>): unknown;
};


export type LogHelper = LogHelper$instance;

export interface TextWriterEventListener$instance extends EventListener {
    dispose(): void;
}


export const TextWriterEventListener: {
    new(): TextWriterEventListener;
    new(filePath: string): TextWriterEventListener;
    new(streamWriter: StreamWriter): TextWriterEventListener;
    readonly defaultLogFileName: string;
};


export type TextWriterEventListener = TextWriterEventListener$instance;

export abstract class IdentityModelTelemetryUtil$instance {
    static readonly clientSku: string;
    static readonly clientVer: string;
    static addTelemetryData(key: string, value: string): boolean;
    static removeTelemetryData(key: string): boolean;
}


export type IdentityModelTelemetryUtil = IdentityModelTelemetryUtil$instance;

