// Generated by tsbindgen - Architecture
// Namespace: Azure.Core.Extensions
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { TokenCredential } from "../../Azure.Core/internal/index.js";
import type { Boolean as ClrBoolean, Func_2, Func_3 } from "@tsonic/dotnet/System/internal/index.js";

export interface IAzureClientBuilder_2$instance<TClient, TOptions> {
    readonly __tsonic_iface_Azure_Core_Extensions_IAzureClientBuilder_2: never;

}


export type IAzureClientBuilder_2<TClient, TOptions> = IAzureClientBuilder_2$instance<TClient, TOptions>;

export interface IAzureClientFactoryBuilder$instance {
    readonly __tsonic_iface_Azure_Core_Extensions_IAzureClientFactoryBuilder: never;

    RegisterClientFactory<TClient, TOptions>(clientFactory: Func_2<TOptions, TClient>): IAzureClientBuilder_2<TClient, TOptions>;
}


export type IAzureClientFactoryBuilder = IAzureClientFactoryBuilder$instance;

export interface IAzureClientFactoryBuilderWithConfiguration_1$instance<TConfiguration> extends IAzureClientFactoryBuilder {
    readonly __tsonic_iface_Azure_Core_Extensions_IAzureClientFactoryBuilderWithConfiguration_1: never;

    RegisterClientFactory<TClient, TOptions>(clientFactory: Func_2<TOptions, TClient>): IAzureClientBuilder_2<TClient, TOptions>;
    RegisterClientFactory<TClient, TOptions>(configuration: TConfiguration): IAzureClientBuilder_2<TClient, TOptions>;
}


export interface IAzureClientFactoryBuilderWithConfiguration_1$instance<TConfiguration> extends IAzureClientFactoryBuilder$instance {}

export type IAzureClientFactoryBuilderWithConfiguration_1<TConfiguration> = IAzureClientFactoryBuilderWithConfiguration_1$instance<TConfiguration>;

export interface IAzureClientFactoryBuilderWithCredential$instance {
    readonly __tsonic_iface_Azure_Core_Extensions_IAzureClientFactoryBuilderWithCredential: never;

    RegisterClientFactory<TClient, TOptions>(clientFactory: Func_3<TOptions, TokenCredential, TClient>, requiresCredential?: boolean): IAzureClientBuilder_2<TClient, TOptions>;
}


export type IAzureClientFactoryBuilderWithCredential = IAzureClientFactoryBuilderWithCredential$instance;

