// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.AppConfig
// Assembly: Microsoft.Identity.Client

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IPoPCryptoProvider } from "../../Microsoft.Identity.Client.AuthScheme.PoP/internal/index.js";
import type { HttpMethod, HttpRequestMessage } from "@tsonic/dotnet/System.Net.Http/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Uri } from "@tsonic/dotnet/System/internal/index.js";

export interface ManagedIdentityId$instance {
}


export const ManagedIdentityId: {
    readonly SystemAssigned: ManagedIdentityId;
    WithUserAssignedClientId(clientId: string): ManagedIdentityId;
    WithUserAssignedObjectId(objectId: string): ManagedIdentityId;
    WithUserAssignedResourceId(resourceId: string): ManagedIdentityId;
};


export type ManagedIdentityId = ManagedIdentityId$instance;

export interface PoPAuthenticationConfiguration$instance {
    HttpHost: string;
    HttpMethod: HttpMethod;
    HttpPath: string;
    Nonce: string;
    PopCryptoProvider: IPoPCryptoProvider;
    SignHttpRequest: boolean;
}


export const PoPAuthenticationConfiguration: {
    new(): PoPAuthenticationConfiguration;
    new(httpRequestMessage: HttpRequestMessage): PoPAuthenticationConfiguration;
    new(requestUri: Uri): PoPAuthenticationConfiguration;
};


export type PoPAuthenticationConfiguration = PoPAuthenticationConfiguration$instance;

