// Generated by tsbindgen - Architecture
// Namespace: Azure.Core.Cryptography
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Byte, ReadOnlyMemory, String as ClrString } from "@tsonic/dotnet/System.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface IKeyEncryptionKey$instance {
    readonly keyId: string;
    wrapKey(algorithm: string, key: ReadOnlyMemory<System_Internal.Byte>, cancellationToken?: CancellationToken): byte[];
    wrapKeyAsync(algorithm: string, key: ReadOnlyMemory<System_Internal.Byte>, cancellationToken?: CancellationToken): Task<byte[]>;
}


export type IKeyEncryptionKey = IKeyEncryptionKey$instance;

export interface IKeyEncryptionKeyResolver$instance {
    resolve(keyId: string, cancellationToken?: CancellationToken): IKeyEncryptionKey;
    resolveAsync(keyId: string, cancellationToken?: CancellationToken): Task<IKeyEncryptionKey>;
}


export type IKeyEncryptionKeyResolver = IKeyEncryptionKeyResolver$instance;

