// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.Identity.Client.Utils
// Assembly: Microsoft.Identity.Client

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Func_1, Object as ClrObject, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface MacMainThreadScheduler$instance {
    readonly __tsonic_type_Microsoft_Identity_Client_Utils_MacMainThreadScheduler: never;

    IsCurrentlyOnMainThread(): boolean;
    IsRunning(): boolean;
    RunOnMainThreadAsync(asyncAction: Func_1<Task>): Task;
    StartMessageLoop(): void;
    Stop(): void;
}


export const MacMainThreadScheduler: {
    Instance(): MacMainThreadScheduler;
};


export type MacMainThreadScheduler = MacMainThreadScheduler$instance;
