// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.SqlClient.Diagnostics
// Assembly: Microsoft.Data.SqlClient

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { SqlCommand, SqlConnection } from "../../Microsoft.Data.SqlClient/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IEnumerable_1, IEnumerator_1, IReadOnlyCollection_1, IReadOnlyList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IDictionary, IEnumerable } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IsolationLevel } from "@tsonic/dotnet/System.Data/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Exception, Guid, Int32, Int64, Nullable_1, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export interface SqlClientCommandAfter$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Command: SqlCommand;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Statistics: IDictionary;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientCommandAfter: {
    new(): SqlClientCommandAfter;
    readonly Name: string;
};


export type SqlClientCommandAfter = SqlClientCommandAfter$instance;

export interface SqlClientCommandBefore$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Command: SqlCommand;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientCommandBefore: {
    new(): SqlClientCommandBefore;
    readonly Name: string;
};


export type SqlClientCommandBefore = SqlClientCommandBefore$instance;

export interface SqlClientCommandError$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Command: SqlCommand;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly Exception: Exception;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientCommandError: {
    new(): SqlClientCommandError;
    readonly Name: string;
};


export type SqlClientCommandError = SqlClientCommandError$instance;

export interface SqlClientConnectionCloseAfter$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Statistics: IDictionary;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionCloseAfter: {
    new(): SqlClientConnectionCloseAfter;
    readonly Name: string;
};


export type SqlClientConnectionCloseAfter = SqlClientConnectionCloseAfter$instance;

export interface SqlClientConnectionCloseBefore$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Statistics: IDictionary;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionCloseBefore: {
    new(): SqlClientConnectionCloseBefore;
    readonly Name: string;
};


export type SqlClientConnectionCloseBefore = SqlClientConnectionCloseBefore$instance;

export interface SqlClientConnectionCloseError$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly ConnectionId: Nullable_1<Guid>;
    readonly Count: int;
    readonly Exception: Exception;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Statistics: IDictionary;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionCloseError: {
    new(): SqlClientConnectionCloseError;
    readonly Name: string;
};


export type SqlClientConnectionCloseError = SqlClientConnectionCloseError$instance;

export interface SqlClientConnectionOpenAfter$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly ClientVersion: string;
    readonly Connection: SqlConnection;
    readonly ConnectionId: Guid;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Statistics: IDictionary;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionOpenAfter: {
    new(): SqlClientConnectionOpenAfter;
    readonly Name: string;
};


export type SqlClientConnectionOpenAfter = SqlClientConnectionOpenAfter$instance;

export interface SqlClientConnectionOpenBefore$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly ClientVersion: string;
    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionOpenBefore: {
    new(): SqlClientConnectionOpenBefore;
    readonly Name: string;
};


export type SqlClientConnectionOpenBefore = SqlClientConnectionOpenBefore$instance;

export interface SqlClientConnectionOpenError$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly ClientVersion: string;
    readonly Connection: SqlConnection;
    readonly ConnectionId: Guid;
    readonly Count: int;
    readonly Exception: Exception;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientConnectionOpenError: {
    new(): SqlClientConnectionOpenError;
    readonly Name: string;
};


export type SqlClientConnectionOpenError = SqlClientConnectionOpenError$instance;

export interface SqlClientTransactionCommitAfter$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionCommitAfter: {
    new(): SqlClientTransactionCommitAfter;
    readonly Name: string;
};


export type SqlClientTransactionCommitAfter = SqlClientTransactionCommitAfter$instance;

export interface SqlClientTransactionCommitBefore$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionCommitBefore: {
    new(): SqlClientTransactionCommitBefore;
    readonly Name: string;
};


export type SqlClientTransactionCommitBefore = SqlClientTransactionCommitBefore$instance;

export interface SqlClientTransactionCommitError$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly Exception: Exception;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionCommitError: {
    new(): SqlClientTransactionCommitError;
    readonly Name: string;
};


export type SqlClientTransactionCommitError = SqlClientTransactionCommitError$instance;

export interface SqlClientTransactionRollbackAfter$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    readonly TransactionName: string;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionRollbackAfter: {
    new(): SqlClientTransactionRollbackAfter;
    readonly Name: string;
};


export type SqlClientTransactionRollbackAfter = SqlClientTransactionRollbackAfter$instance;

export interface SqlClientTransactionRollbackBefore$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    readonly TransactionName: string;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionRollbackBefore: {
    new(): SqlClientTransactionRollbackBefore;
    readonly Name: string;
};


export type SqlClientTransactionRollbackBefore = SqlClientTransactionRollbackBefore$instance;

export interface SqlClientTransactionRollbackError$instance {
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Connection: SqlConnection;
    readonly Count: int;
    readonly Exception: Exception;
    readonly IsolationLevel: IsolationLevel;
    readonly [index: number]: KeyValuePair_2<System_Internal.String, unknown>;
    readonly Operation: string;
    readonly OperationId: Guid;
    readonly Timestamp: long;
    readonly TransactionId: Nullable_1<System_Internal.Int64>;
    readonly TransactionName: string;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
}


export const SqlClientTransactionRollbackError: {
    new(): SqlClientTransactionRollbackError;
    readonly Name: string;
};


export type SqlClientTransactionRollbackError = SqlClientTransactionRollbackError$instance;

