// Generated by dotnet-bindgen - Architecture
// Namespace: Azure.Core.GeoJson
// Assembly: Azure.Core

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import * as Azure_Internal from "../../Azure/internal/index.js";
import type { ResponseError } from "../../Azure/internal/index.js";
import * as System_ClientModel_Primitives_Internal from "../../System.ClientModel.Primitives/internal/index.js";
import type { IJsonModel_1, IPersistableModel_1, ModelReaderWriterOptions } from "../../System.ClientModel.Primitives/internal/index.js";
import type { BinaryData } from "../../System/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IEnumerable_1, IEnumerator_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerable, IEnumerator } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { Utf8JsonReader, Utf8JsonWriter } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import * as System_Lib_tsonic_dotnet from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Double, Enum, IComparable, IConvertible, IDisposable, IEquatable_1, IFormattable, Int32, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export type GeoObjectType = number & { readonly __tsonic_type_Azure_Core_GeoJson_GeoObjectType: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const GeoObjectType: {
    readonly Point: GeoObjectType;
    readonly MultiPoint: GeoObjectType;
    readonly Polygon: GeoObjectType;
    readonly MultiPolygon: GeoObjectType;
    readonly LineString: GeoObjectType;
    readonly MultiLineString: GeoObjectType;
    readonly GeometryCollection: GeoObjectType;
};


export interface GeoArray_1$instance<T extends unknown> {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoArray_1: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    GetEnumerator(): GeoArray_1_Enumerator<T>;
}


export const GeoArray_1: {
    new<T extends unknown>(): GeoArray_1<T>;
};


export type GeoArray_1<T extends unknown> = GeoArray_1$instance<T> & { readonly [index: number]: T; };

export interface GeoArray_1_Enumerator$instance<T extends unknown> {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoArray_1_Enumerator: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Current: T;
    Dispose(): void;
    MoveNext(): boolean;
    Reset(): void;
}


export const GeoArray_1_Enumerator: {
    new<T extends unknown>(): GeoArray_1_Enumerator<T>;
};


export type GeoArray_1_Enumerator<T extends unknown> = GeoArray_1_Enumerator$instance<T>;

export interface GeoPosition$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoPosition: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Altitude: Nullable_1<System_Internal.Double>;
    readonly Count: int;
    readonly Latitude: double;
    readonly Longitude: double;
    Equals(obj: unknown | null): boolean;
    Equals(other: GeoPosition): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const GeoPosition: {
    new(longitude: double, latitude: double): GeoPosition;
    new(longitude: double, latitude: double, altitude: Nullable_1<System_Internal.Double>): GeoPosition;
};


export type GeoPosition = GeoPosition$instance & { readonly [index: number]: double; };

export interface GeoBoundingBox$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoBoundingBox: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly East: double;
    readonly MaxAltitude: Nullable_1<System_Internal.Double>;
    readonly MinAltitude: Nullable_1<System_Internal.Double>;
    readonly North: double;
    readonly South: double;
    readonly West: double;
    Equals(obj: unknown | null): boolean;
    Equals(other: GeoBoundingBox | null): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const GeoBoundingBox: {
    new(west: double, south: double, east: double, north: double): GeoBoundingBox;
    new(west: double, south: double, east: double, north: double, minAltitude: Nullable_1<System_Internal.Double>, maxAltitude: Nullable_1<System_Internal.Double>): GeoBoundingBox;
};


export type GeoBoundingBox = GeoBoundingBox$instance & { readonly [index: number]: double; };

export interface GeoCollection$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoCollection: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    GetEnumerator(): IEnumerator_1<GeoObject>;
}


export const GeoCollection: {
    new(geometries: IEnumerable_1<GeoObject>): GeoCollection;
    new(geometries: IEnumerable_1<GeoObject>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoCollection;
};


export type GeoCollection = GeoCollection$instance & { readonly [index: number]: GeoObject; };

export interface GeoLinearRing$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoLinearRing: never;

    readonly Coordinates: GeoArray_1<GeoPosition>;
}


export const GeoLinearRing: {
    new(coordinates: IEnumerable_1<GeoPosition>): GeoLinearRing;
};


export type GeoLinearRing = GeoLinearRing$instance;

export interface GeoLineString$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoLineString: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;

    readonly Coordinates: GeoArray_1<GeoPosition>;
}


export const GeoLineString: {
    new(coordinates: IEnumerable_1<GeoPosition>): GeoLineString;
    new(coordinates: IEnumerable_1<GeoPosition>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoLineString;
};


export type GeoLineString = GeoLineString$instance;

export interface GeoLineStringCollection$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoLineStringCollection: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Coordinates: GeoArray_1<GeoArray_1<GeoPosition>>;
    readonly Count: int;
    GetEnumerator(): IEnumerator_1<GeoLineString>;
}


export const GeoLineStringCollection: {
    new(lines: IEnumerable_1<GeoLineString>): GeoLineStringCollection;
    new(lines: IEnumerable_1<GeoLineString>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoLineStringCollection;
};


export type GeoLineStringCollection = GeoLineStringCollection$instance & { readonly [index: number]: GeoLineString; };

export interface GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;

    readonly BoundingBox: GeoBoundingBox | null;
    readonly Type: GeoObjectType;
    ToString(): string;
    TryGetCustomProperty(name: string, value: unknown | null): boolean;
}


export const GeoObject: {
    Parse(json: string): GeoObject;
};


export type GeoObject = GeoObject$instance;

export interface GeoPoint$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoPoint: never;

    readonly __tsonic_iface_System_ClientModel_Primitives_IJsonModel_1: never;
    readonly __tsonic_iface_System_ClientModel_Primitives_IPersistableModel_1: never;

    readonly Coordinates: GeoPosition;
}


export const GeoPoint: {
    new(): GeoPoint;
    new(longitude: double, latitude: double): GeoPoint;
    new(longitude: double, latitude: double, altitude: Nullable_1<System_Internal.Double>): GeoPoint;
    new(position: GeoPosition): GeoPoint;
    new(position: GeoPosition, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoPoint;
};


export interface __GeoPoint$views {
    As_IJsonModel_1(): System_ClientModel_Primitives_Internal.IJsonModel_1$instance<GeoPoint>;
    As_IPersistableModel_1(): System_ClientModel_Primitives_Internal.IPersistableModel_1$instance<GeoPoint>;
}

export type GeoPoint = GeoPoint$instance & __GeoPoint$views;


export interface GeoPointCollection$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoPointCollection: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Coordinates: GeoArray_1<GeoPosition>;
    readonly Count: int;
    GetEnumerator(): IEnumerator_1<GeoPoint>;
}


export const GeoPointCollection: {
    new(points: IEnumerable_1<GeoPoint>): GeoPointCollection;
    new(points: IEnumerable_1<GeoPoint>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoPointCollection;
};


export type GeoPointCollection = GeoPointCollection$instance & { readonly [index: number]: GeoPoint; };

export interface GeoPolygon$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoPolygon: never;

    readonly Coordinates: GeoArray_1<GeoArray_1<GeoPosition>>;
    readonly OuterRing: GeoLinearRing;
    readonly Rings: IReadOnlyList_1<GeoLinearRing>;
}


export const GeoPolygon: {
    new(positions: IEnumerable_1<GeoPosition>): GeoPolygon;
    new(rings: IEnumerable_1<GeoLinearRing>): GeoPolygon;
    new(rings: IEnumerable_1<GeoLinearRing>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoPolygon;
};


export type GeoPolygon = GeoPolygon$instance;

export interface GeoPolygonCollection$instance extends GeoObject$instance {
    readonly __tsonic_type_Azure_Core_GeoJson_GeoObject: never;
    readonly __tsonic_type_Azure_Core_GeoJson_GeoPolygonCollection: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Coordinates: GeoArray_1<GeoArray_1<GeoArray_1<GeoPosition>>>;
    readonly Count: int;
    GetEnumerator(): IEnumerator_1<GeoPolygon>;
}


export const GeoPolygonCollection: {
    new(polygons: IEnumerable_1<GeoPolygon>): GeoPolygonCollection;
    new(polygons: IEnumerable_1<GeoPolygon>, boundingBox: GeoBoundingBox | null, customProperties: IReadOnlyDictionary_2<System_Internal.String, unknown | null>): GeoPolygonCollection;
};


export type GeoPolygonCollection = GeoPolygonCollection$instance & { readonly [index: number]: GeoPolygon; };
