// Generated by tsbindgen - Architecture
// Namespace: Azure.Core.GeoJson
// Assembly: Azure.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_ClientModel_Primitives_Internal from "../../System.ClientModel.Primitives/internal/index.js";
import type { IJsonModel_1, IPersistableModel_1, ModelReaderWriterOptions } from "../../System.ClientModel.Primitives/internal/index.js";
import type { BinaryData } from "../../System/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator as IEnumerator__System_Collections_Generic, IReadOnlyCollection, IReadOnlyDictionary, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable, IEnumerator } from "@tsonic/dotnet/System.Collections.js";
import * as System_Lib from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Double, Enum, IComparable, IConvertible, IDisposable, IEquatable, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System.js";
import type { Utf8JsonReader, Utf8JsonWriter } from "@tsonic/dotnet/System.Text.Json.js";

export enum GeoObjectType {
    point = 0,
    multiPoint = 1,
    polygon = 2,
    multiPolygon = 3,
    lineString = 4,
    multiLineString = 5,
    geometryCollection = 6
}


export interface GeoArray_1$instance<T> {
    readonly count: int;
    readonly item: T;
    getEnumerator(): GeoArray_1_Enumerator<T>;
}


export const GeoArray_1: {
    new<T>(): GeoArray_1<T>;
};


export type GeoArray_1<T> = GeoArray_1$instance<T>;

export interface GeoArray_1_Enumerator$instance<T> {
    readonly current: T;
    dispose(): void;
    moveNext(): boolean;
    reset(): void;
}


export const GeoArray_1_Enumerator: {
    new<T>(): GeoArray_1_Enumerator<T>;
};


export type GeoArray_1_Enumerator<T> = GeoArray_1_Enumerator$instance<T>;

export interface GeoPosition$instance {
    readonly altitude: Nullable<System_Internal.Double>;
    readonly count: int;
    readonly item: double;
    readonly latitude: double;
    readonly longitude: double;
    equals(other: GeoPosition): boolean;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    toString(): string;
}


export const GeoPosition: {
    new(longitude: double, latitude: double): GeoPosition;
    new(longitude: double, latitude: double, altitude: Nullable<System_Internal.Double>): GeoPosition;
};


export type GeoPosition = GeoPosition$instance;

export interface GeoBoundingBox$instance {
    readonly east: double;
    readonly item: double;
    readonly maxAltitude: Nullable<System_Internal.Double>;
    readonly minAltitude: Nullable<System_Internal.Double>;
    readonly north: double;
    readonly south: double;
    readonly west: double;
    equals(other: GeoBoundingBox): boolean;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    toString(): string;
}


export const GeoBoundingBox: {
    new(west: double, south: double, east: double, north: double): GeoBoundingBox;
    new(west: double, south: double, east: double, north: double, minAltitude: Nullable<System_Internal.Double>, maxAltitude: Nullable<System_Internal.Double>): GeoBoundingBox;
};


export type GeoBoundingBox = GeoBoundingBox$instance;

export interface GeoCollection$instance extends GeoObject {
    readonly count: int;
    readonly item: GeoObject;
    readonly type_: GeoObjectType;
    getEnumerator(): IEnumerator__System_Collections_Generic<GeoObject>;
}


export const GeoCollection: {
    new(geometries: IEnumerable__System_Collections_Generic<GeoObject>): GeoCollection;
    new(geometries: IEnumerable__System_Collections_Generic<GeoObject>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoCollection;
};


export type GeoCollection = GeoCollection$instance;

export interface GeoLinearRing$instance {
    readonly coordinates: GeoArray_1<GeoPosition>;
}


export const GeoLinearRing: {
    new(coordinates: IEnumerable__System_Collections_Generic<GeoPosition>): GeoLinearRing;
};


export type GeoLinearRing = GeoLinearRing$instance;

export interface GeoLineString$instance extends GeoObject {
    readonly coordinates: GeoArray_1<GeoPosition>;
    readonly type_: GeoObjectType;
}


export const GeoLineString: {
    new(coordinates: IEnumerable__System_Collections_Generic<GeoPosition>): GeoLineString;
    new(coordinates: IEnumerable__System_Collections_Generic<GeoPosition>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoLineString;
};


export type GeoLineString = GeoLineString$instance;

export interface GeoLineStringCollection$instance extends GeoObject {
    readonly coordinates: GeoArray_1<GeoArray_1<GeoPosition>>;
    readonly count: int;
    readonly item: GeoLineString;
    readonly type_: GeoObjectType;
    getEnumerator(): IEnumerator__System_Collections_Generic<GeoLineString>;
}


export const GeoLineStringCollection: {
    new(lines: IEnumerable__System_Collections_Generic<GeoLineString>): GeoLineStringCollection;
    new(lines: IEnumerable__System_Collections_Generic<GeoLineString>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoLineStringCollection;
};


export type GeoLineStringCollection = GeoLineStringCollection$instance;

export interface GeoObject$instance {
    readonly boundingBox: GeoBoundingBox | undefined;
    readonly type_: GeoObjectType;
    toString(): string;
    tryGetCustomProperty(name: string, value: unknown): boolean;
}


export const GeoObject: {
    parse(json: string): GeoObject;
};


export type GeoObject = GeoObject$instance;

export interface GeoPoint$instance extends GeoObject {
    readonly coordinates: GeoPosition;
    readonly type_: GeoObjectType;
}


export const GeoPoint: {
    new(): GeoPoint;
    new(longitude: double, latitude: double): GeoPoint;
    new(longitude: double, latitude: double, altitude: Nullable<System_Internal.Double>): GeoPoint;
    new(position: GeoPosition): GeoPoint;
    new(position: GeoPosition, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoPoint;
};


export interface __GeoPoint$views {
    As_IJsonModel_1(): System_ClientModel_Primitives_Internal.IJsonModel_1$instance<GeoPoint>;
    As_IPersistableModel_1(): System_ClientModel_Primitives_Internal.IPersistableModel_1$instance<GeoPoint>;
}

export interface GeoPoint$instance extends System_ClientModel_Primitives_Internal.IJsonModel_1$instance<GeoPoint> {}

export type GeoPoint = GeoPoint$instance & __GeoPoint$views;


export interface GeoPointCollection$instance extends GeoObject {
    readonly coordinates: GeoArray_1<GeoPosition>;
    readonly count: int;
    readonly item: GeoPoint;
    readonly type_: GeoObjectType;
    getEnumerator(): IEnumerator__System_Collections_Generic<GeoPoint>;
}


export const GeoPointCollection: {
    new(points: IEnumerable__System_Collections_Generic<GeoPoint>): GeoPointCollection;
    new(points: IEnumerable__System_Collections_Generic<GeoPoint>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoPointCollection;
};


export type GeoPointCollection = GeoPointCollection$instance;

export interface GeoPolygon$instance extends GeoObject {
    readonly coordinates: GeoArray_1<GeoArray_1<GeoPosition>>;
    readonly outerRing: GeoLinearRing;
    readonly rings: IReadOnlyList<GeoLinearRing>;
    readonly type_: GeoObjectType;
}


export const GeoPolygon: {
    new(positions: IEnumerable__System_Collections_Generic<GeoPosition>): GeoPolygon;
    new(rings: IEnumerable__System_Collections_Generic<GeoLinearRing>): GeoPolygon;
    new(rings: IEnumerable__System_Collections_Generic<GeoLinearRing>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoPolygon;
};


export type GeoPolygon = GeoPolygon$instance;

export interface GeoPolygonCollection$instance extends GeoObject {
    readonly coordinates: GeoArray_1<GeoArray_1<GeoArray_1<GeoPosition>>>;
    readonly count: int;
    readonly item: GeoPolygon;
    readonly type_: GeoObjectType;
    getEnumerator(): IEnumerator__System_Collections_Generic<GeoPolygon>;
}


export const GeoPolygonCollection: {
    new(polygons: IEnumerable__System_Collections_Generic<GeoPolygon>): GeoPolygonCollection;
    new(polygons: IEnumerable__System_Collections_Generic<GeoPolygon>, boundingBox: GeoBoundingBox, customProperties: IReadOnlyDictionary<System_Internal.String, unknown>): GeoPolygonCollection;
};


export type GeoPolygonCollection = GeoPolygonCollection$instance;

