// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos
// Assembly: Microsoft.Identity.Client

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Object as ClrObject } from "@tsonic/dotnet/System/internal/index.js";

export interface Credential$instance {
    readonly __tsonic_type_Microsoft_Identity_Client_Platforms_Features_DesktopOs_Kerberos_Credential: never;

}


export const Credential: (abstract new() => Credential) & {
    Current(): Credential;
};


export type Credential = Credential$instance;

