// Generated by tsbindgen - Architecture
// Namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
// Assembly: Microsoft.IdentityModel.Protocols.OpenIdConnect

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_IdentityModel_Protocols_Internal from "../../Microsoft.IdentityModel.Protocols/internal/index.js";
import type { AuthenticationProtocolMessage, IConfigurationRetriever_1, IDocumentRetriever } from "../../Microsoft.IdentityModel.Protocols/internal/index.js";
import * as Microsoft_IdentityModel_Tokens_Internal from "../../Microsoft.IdentityModel.Tokens/internal/index.js";
import type { BaseConfiguration, CryptoProviderFactory, JsonWebKeySet, SecurityKey } from "../../Microsoft.IdentityModel.Tokens/internal/index.js";
import type { JwtSecurityToken } from "../../System.IdentityModel.Tokens.Jwt/internal/index.js";
import type { ICollection, IDictionary, IEnumerable, KeyValuePair } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { NameValueCollection } from "@tsonic/dotnet/System.Collections.Specialized.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { AsyncCallback, Boolean as ClrBoolean, Enum, Exception, IAsyncResult, ICloneable, IComparable, IConvertible, IFormattable, Int32, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, String as ClrString, TimeSpan, Void } from "@tsonic/dotnet/System.js";
import type { HttpClient } from "@tsonic/dotnet/System.Net.Http.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { HashAlgorithm } from "@tsonic/dotnet/System.Security.Cryptography.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export enum OpenIdConnectRequestType {
    Authentication = 0,
    Logout = 1,
    Token = 2
}


export type IdTokenValidator = (idToken: JwtSecurityToken, context: OpenIdConnectProtocolValidationContext) => void;


export interface OpenIdConnectConfiguration$instance extends BaseConfiguration {
    readonly AcrValuesSupported: ICollection<System_Internal.String>;
    ActiveTokenEndpoint: string;
    readonly AdditionalData: IDictionary<System_Internal.String, unknown>;
    AuthorizationEndpoint: string;
    AuthorizationResponseIssParameterSupported: boolean;
    BackchannelAuthenticationEndpoint: string;
    readonly BackchannelAuthenticationRequestSigningAlgValuesSupported: ICollection<System_Internal.String>;
    readonly BackchannelTokenDeliveryModesSupported: ICollection<System_Internal.String>;
    BackchannelUserCodeParameterSupported: boolean;
    CheckSessionIframe: string;
    readonly ClaimsLocalesSupported: ICollection<System_Internal.String>;
    ClaimsParameterSupported: boolean;
    readonly ClaimsSupported: ICollection<System_Internal.String>;
    readonly ClaimTypesSupported: ICollection<System_Internal.String>;
    readonly DisplayValuesSupported: ICollection<System_Internal.String>;
    readonly DPoPSigningAlgValuesSupported: ICollection<System_Internal.String>;
    EndSessionEndpoint: string;
    FrontchannelLogoutSessionSupported: string;
    FrontchannelLogoutSupported: string;
    readonly GrantTypesSupported: ICollection<System_Internal.String>;
    HttpLogoutSupported: boolean;
    readonly IdTokenEncryptionAlgValuesSupported: ICollection<System_Internal.String>;
    readonly IdTokenEncryptionEncValuesSupported: ICollection<System_Internal.String>;
    readonly IdTokenSigningAlgValuesSupported: ICollection<System_Internal.String>;
    IntrospectionEndpoint: string;
    readonly IntrospectionEndpointAuthMethodsSupported: ICollection<System_Internal.String>;
    readonly IntrospectionEndpointAuthSigningAlgValuesSupported: ICollection<System_Internal.String>;
    Issuer: string;
    JsonWebKeySet: JsonWebKeySet;
    JwksUri: string;
    LogoutSessionSupported: boolean;
    OpPolicyUri: string;
    OpTosUri: string;
    readonly PromptValuesSupported: ICollection<System_Internal.String>;
    PushedAuthorizationRequestEndpoint: string;
    RegistrationEndpoint: string;
    readonly RequestObjectEncryptionAlgValuesSupported: ICollection<System_Internal.String>;
    readonly RequestObjectEncryptionEncValuesSupported: ICollection<System_Internal.String>;
    readonly RequestObjectSigningAlgValuesSupported: ICollection<System_Internal.String>;
    RequestParameterSupported: boolean;
    RequestUriParameterSupported: boolean;
    RequirePushedAuthorizationRequests: boolean;
    RequireRequestUriRegistration: boolean;
    readonly ResponseModesSupported: ICollection<System_Internal.String>;
    readonly ResponseTypesSupported: ICollection<System_Internal.String>;
    readonly ScopesSupported: ICollection<System_Internal.String>;
    ServiceDocumentation: string;
    readonly SigningKeys: ICollection<SecurityKey>;
    readonly SubjectTypesSupported: ICollection<System_Internal.String>;
    TokenEndpoint: string;
    readonly TokenEndpointAuthMethodsSupported: ICollection<System_Internal.String>;
    readonly TokenEndpointAuthSigningAlgValuesSupported: ICollection<System_Internal.String>;
    readonly UILocalesSupported: ICollection<System_Internal.String>;
    UserInfoEndpoint: string;
    readonly UserInfoEndpointEncryptionAlgValuesSupported: ICollection<System_Internal.String>;
    readonly UserInfoEndpointEncryptionEncValuesSupported: ICollection<System_Internal.String>;
    readonly UserInfoEndpointSigningAlgValuesSupported: ICollection<System_Internal.String>;
    ShouldSerializeAcrValuesSupported(): boolean;
    ShouldSerializeBackchannelAuthenticationRequestSigningAlgValuesSupported(): boolean;
    ShouldSerializeBackchannelTokenDeliveryModesSupported(): boolean;
    ShouldSerializeClaimsLocalesSupported(): boolean;
    ShouldSerializeClaimsSupported(): boolean;
    ShouldSerializeClaimTypesSupported(): boolean;
    ShouldSerializeDisplayValuesSupported(): boolean;
    ShouldSerializeDPoPSigningAlgValuesSupported(): boolean;
    ShouldSerializeGrantTypesSupported(): boolean;
    ShouldSerializeIdTokenEncryptionAlgValuesSupported(): boolean;
    ShouldSerializeIdTokenEncryptionEncValuesSupported(): boolean;
    ShouldSerializeIdTokenSigningAlgValuesSupported(): boolean;
    ShouldSerializeIntrospectionEndpointAuthMethodsSupported(): boolean;
    ShouldSerializeIntrospectionEndpointAuthSigningAlgValuesSupported(): boolean;
    ShouldSerializePromptValuesSupported(): boolean;
    ShouldSerializeRequestObjectEncryptionAlgValuesSupported(): boolean;
    ShouldSerializeRequestObjectEncryptionEncValuesSupported(): boolean;
    ShouldSerializeRequestObjectSigningAlgValuesSupported(): boolean;
    ShouldSerializeResponseModesSupported(): boolean;
    ShouldSerializeResponseTypesSupported(): boolean;
    ShouldSerializeScopesSupported(): boolean;
    ShouldSerializeSigningKeys(): boolean;
    ShouldSerializeSubjectTypesSupported(): boolean;
    ShouldSerializeTokenEndpointAuthMethodsSupported(): boolean;
    ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported(): boolean;
    ShouldSerializeUILocalesSupported(): boolean;
    ShouldSerializeUserInfoEndpointEncryptionAlgValuesSupported(): boolean;
    ShouldSerializeUserInfoEndpointEncryptionEncValuesSupported(): boolean;
    ShouldSerializeUserInfoEndpointSigningAlgValuesSupported(): boolean;
}


export const OpenIdConnectConfiguration: {
    new(): OpenIdConnectConfiguration;
    new(json: string): OpenIdConnectConfiguration;
    Create(json: string): OpenIdConnectConfiguration;
    Write(configuration: OpenIdConnectConfiguration): string;
};


export type OpenIdConnectConfiguration = OpenIdConnectConfiguration$instance;

export interface OpenIdConnectConfigurationRetriever$instance {
}


export const OpenIdConnectConfigurationRetriever: {
    new(): OpenIdConnectConfigurationRetriever;
    GetAsync(address: string, retriever: IDocumentRetriever, cancel: CancellationToken): Task<OpenIdConnectConfiguration>;
    GetAsync(address: string, httpClient: HttpClient, cancel: CancellationToken): Task<OpenIdConnectConfiguration>;
    GetAsync(address: string, cancel: CancellationToken): Task<OpenIdConnectConfiguration>;
};


export interface __OpenIdConnectConfigurationRetriever$views {
    As_IConfigurationRetriever_1(): Microsoft_IdentityModel_Protocols_Internal.IConfigurationRetriever_1$instance<OpenIdConnectConfiguration>;
}

export interface OpenIdConnectConfigurationRetriever$instance extends Microsoft_IdentityModel_Protocols_Internal.IConfigurationRetriever_1$instance<OpenIdConnectConfiguration> {}

export type OpenIdConnectConfigurationRetriever = OpenIdConnectConfigurationRetriever$instance & __OpenIdConnectConfigurationRetriever$views;


export interface OpenIdConnectMessage$instance extends AuthenticationProtocolMessage {
    AccessToken: string;
    AcrValues: string;
    AuthorizationEndpoint: string;
    ClaimsLocales: string;
    ClientAssertion: string;
    ClientAssertionType: string;
    ClientId: string;
    ClientSecret: string;
    get Code(): string | undefined;
    set Code(value: string);
    Display: string;
    DomainHint: string;
    EnableTelemetryParameters: boolean;
    Error: string;
    ErrorDescription: string;
    ErrorUri: string;
    ExpiresIn: string;
    GrantType: string;
    IdentityProvider: string;
    IdToken: string;
    IdTokenHint: string;
    Iss: string;
    LoginHint: string;
    MaxAge: string;
    Nonce: string;
    Password: string;
    PostLogoutRedirectUri: string;
    Prompt: string;
    RedirectUri: string;
    RefreshToken: string;
    RequestType: OpenIdConnectRequestType;
    RequestUri: string;
    Resource: string;
    ResponseMode: string;
    ResponseType: string;
    Scope: string;
    SessionState: string;
    Sid: string;
    SkuTelemetryValue: string;
    State: string;
    TargetLinkUri: string;
    TokenEndpoint: string;
    TokenType: string;
    UiLocales: string;
    UserId: string;
    Username: string;
    Clone(): OpenIdConnectMessage;
    CreateAuthenticationRequestUrl(): string;
    CreateLogoutRequestUrl(): string;
}


export const OpenIdConnectMessage: {
    new(): OpenIdConnectMessage;
    new(json: string): OpenIdConnectMessage;
    new(other: OpenIdConnectMessage): OpenIdConnectMessage;
    new(nameValueCollection: NameValueCollection): OpenIdConnectMessage;
    new(parameters: IEnumerable<KeyValuePair<System_Internal.String, string[]>>): OpenIdConnectMessage;
    EnableTelemetryParametersByDefault: boolean;
};


export type OpenIdConnectMessage = OpenIdConnectMessage$instance;

export interface OpenIdConnectProtocolException$instance extends Exception {
}


export const OpenIdConnectProtocolException: {
    new(): OpenIdConnectProtocolException;
    new(message: string): OpenIdConnectProtocolException;
    new(message: string, innerException: Exception): OpenIdConnectProtocolException;
    new(info: SerializationInfo, context: StreamingContext): OpenIdConnectProtocolException;
};


export type OpenIdConnectProtocolException = OpenIdConnectProtocolException$instance;

export interface OpenIdConnectProtocolInvalidAtHashException$instance extends OpenIdConnectProtocolException {
}


export const OpenIdConnectProtocolInvalidAtHashException: {
    new(): OpenIdConnectProtocolInvalidAtHashException;
    new(message: string): OpenIdConnectProtocolInvalidAtHashException;
    new(message: string, innerException: Exception): OpenIdConnectProtocolInvalidAtHashException;
    new(info: SerializationInfo, context: StreamingContext): OpenIdConnectProtocolInvalidAtHashException;
};


export type OpenIdConnectProtocolInvalidAtHashException = OpenIdConnectProtocolInvalidAtHashException$instance;

export interface OpenIdConnectProtocolInvalidCHashException$instance extends OpenIdConnectProtocolException {
}


export const OpenIdConnectProtocolInvalidCHashException: {
    new(): OpenIdConnectProtocolInvalidCHashException;
    new(message: string): OpenIdConnectProtocolInvalidCHashException;
    new(message: string, innerException: Exception): OpenIdConnectProtocolInvalidCHashException;
    new(info: SerializationInfo, context: StreamingContext): OpenIdConnectProtocolInvalidCHashException;
};


export type OpenIdConnectProtocolInvalidCHashException = OpenIdConnectProtocolInvalidCHashException$instance;

export interface OpenIdConnectProtocolInvalidNonceException$instance extends OpenIdConnectProtocolException {
}


export const OpenIdConnectProtocolInvalidNonceException: {
    new(): OpenIdConnectProtocolInvalidNonceException;
    new(message: string): OpenIdConnectProtocolInvalidNonceException;
    new(message: string, innerException: Exception): OpenIdConnectProtocolInvalidNonceException;
    new(info: SerializationInfo, context: StreamingContext): OpenIdConnectProtocolInvalidNonceException;
};


export type OpenIdConnectProtocolInvalidNonceException = OpenIdConnectProtocolInvalidNonceException$instance;

export interface OpenIdConnectProtocolInvalidStateException$instance extends OpenIdConnectProtocolException {
}


export const OpenIdConnectProtocolInvalidStateException: {
    new(): OpenIdConnectProtocolInvalidStateException;
    new(message: string): OpenIdConnectProtocolInvalidStateException;
    new(message: string, innerException: Exception): OpenIdConnectProtocolInvalidStateException;
    new(info: SerializationInfo, context: StreamingContext): OpenIdConnectProtocolInvalidStateException;
};


export type OpenIdConnectProtocolInvalidStateException = OpenIdConnectProtocolInvalidStateException$instance;

export interface OpenIdConnectProtocolValidationContext$instance {
    ClientId: string;
    Nonce: string;
    ProtocolMessage: OpenIdConnectMessage;
    State: string;
    UserInfoEndpointResponse: string;
    ValidatedIdToken: JwtSecurityToken;
}


export const OpenIdConnectProtocolValidationContext: {
    new(): OpenIdConnectProtocolValidationContext;
};


export type OpenIdConnectProtocolValidationContext = OpenIdConnectProtocolValidationContext$instance;

export abstract class OpenIdConnectProtocolValidator$protected {
    protected ValidateAtHash(validationContext: OpenIdConnectProtocolValidationContext): void;
    protected ValidateCHash(validationContext: OpenIdConnectProtocolValidationContext): void;
    protected ValidateIdToken(validationContext: OpenIdConnectProtocolValidationContext): void;
    protected ValidateNonce(validationContext: OpenIdConnectProtocolValidationContext): void;
    protected ValidateState(validationContext: OpenIdConnectProtocolValidationContext): void;
}


export interface OpenIdConnectProtocolValidator$instance extends OpenIdConnectProtocolValidator$protected {
    CryptoProviderFactory: CryptoProviderFactory;
    readonly HashAlgorithmMap: IDictionary<System_Internal.String, System_Internal.String>;
    IdTokenValidator: IdTokenValidator;
    NonceLifetime: TimeSpan;
    RequireAcr: boolean;
    RequireAmr: boolean;
    RequireAuthTime: boolean;
    RequireAzp: boolean;
    RequireNonce: boolean;
    RequireState: boolean;
    RequireStateValidation: boolean;
    RequireSub: boolean;
    RequireTimeStampInNonce: boolean;
    GenerateNonce(): string;
    GetHashAlgorithm(algorithm: string): HashAlgorithm;
    ValidateAuthenticationResponse(validationContext: OpenIdConnectProtocolValidationContext): void;
    ValidateTokenResponse(validationContext: OpenIdConnectProtocolValidationContext): void;
    ValidateUserInfoResponse(validationContext: OpenIdConnectProtocolValidationContext): void;
}


export const OpenIdConnectProtocolValidator: {
    new(): OpenIdConnectProtocolValidator;
    readonly DefaultNonceLifetime: TimeSpan;
    RequireSubByDefault: boolean;
};


export type OpenIdConnectProtocolValidator = OpenIdConnectProtocolValidator$instance;

export abstract class ActiveDirectoryOpenIdConnectEndpoints$instance {
    static readonly Authorize: string;
    static readonly Logout: string;
    static readonly Token: string;
}


export type ActiveDirectoryOpenIdConnectEndpoints = ActiveDirectoryOpenIdConnectEndpoints$instance;

export abstract class OpenIdConnectGrantTypes$instance {
    static readonly AuthorizationCode: string;
    static readonly RefreshToken: string;
    static readonly Password: string;
    static readonly ClientCredentials: string;
}


export type OpenIdConnectGrantTypes = OpenIdConnectGrantTypes$instance;

export abstract class OpenIdConnectParameterNames$instance {
    static readonly AccessToken: string;
    static readonly AcrValues: string;
    static readonly ClaimsLocales: string;
    static readonly ClientAssertion: string;
    static readonly ClientAssertionType: string;
    static readonly ClientId: string;
    static readonly ClientSecret: string;
    static readonly Code: string;
    static readonly Display: string;
    static readonly DomainHint: string;
    static readonly Error: string;
    static readonly ErrorDescription: string;
    static readonly ErrorUri: string;
    static readonly ExpiresIn: string;
    static readonly GrantType: string;
    static readonly Iss: string;
    static readonly IdToken: string;
    static readonly IdTokenHint: string;
    static readonly IdentityProvider: string;
    static readonly LoginHint: string;
    static readonly MaxAge: string;
    static readonly Nonce: string;
    static readonly Password: string;
    static readonly PostLogoutRedirectUri: string;
    static readonly Prompt: string;
    static readonly RedirectUri: string;
    static readonly RefreshToken: string;
    static readonly RequestUri: string;
    static readonly Resource: string;
    static readonly ResponseMode: string;
    static readonly ResponseType: string;
    static readonly Scope: string;
    static readonly SkuTelemetry: string;
    static readonly SessionState: string;
    static readonly Sid: string;
    static readonly State: string;
    static readonly TargetLinkUri: string;
    static readonly TokenType: string;
    static readonly UiLocales: string;
    static readonly UserId: string;
    static readonly Username: string;
    static readonly VersionTelemetry: string;
}


export type OpenIdConnectParameterNames = OpenIdConnectParameterNames$instance;

export abstract class OpenIdConnectPrompt$instance {
    static readonly None: string;
    static readonly Login: string;
    static readonly Consent: string;
    static readonly SelectAccount: string;
}


export type OpenIdConnectPrompt = OpenIdConnectPrompt$instance;

export abstract class OpenIdConnectResponseMode$instance {
    static readonly Query: string;
    static readonly FormPost: string;
    static readonly Fragment: string;
}


export type OpenIdConnectResponseMode = OpenIdConnectResponseMode$instance;

export abstract class OpenIdConnectResponseType$instance {
    static readonly Code: string;
    static readonly CodeIdToken: string;
    static readonly CodeIdTokenToken: string;
    static readonly CodeToken: string;
    static readonly IdToken: string;
    static readonly IdTokenToken: string;
    static readonly None: string;
    static readonly Token: string;
}


export type OpenIdConnectResponseType = OpenIdConnectResponseType$instance;

export abstract class OpenIdConnectScope$instance {
    static readonly Address: string;
    static readonly Email: string;
    static readonly OfflineAccess: string;
    static readonly OpenId: string;
    static readonly OpenIdProfile: string;
    static readonly Phone: string;
    static readonly UserImpersonation: string;
}


export type OpenIdConnectScope = OpenIdConnectScope$instance;

export abstract class OpenIdConnectSessionProperties$instance {
    static readonly CheckSessionIFrame: string;
    static readonly RedirectUri: string;
    static readonly SessionState: string;
}


export type OpenIdConnectSessionProperties = OpenIdConnectSessionProperties$instance;

export abstract class OpenIdProviderMetadataNames$instance {
    static readonly AcrValuesSupported: string;
    static readonly AuthorizationEndpoint: string;
    static readonly AuthorizationResponseIssParameterSupported: string;
    static readonly BackchannelAuthenticationEndpoint: string;
    static readonly BackchannelAuthenticationRequestSigningAlgValuesSupported: string;
    static readonly BackchannelTokenDeliveryModesSupported: string;
    static readonly BackchannelUserCodeParameterSupported: string;
    static readonly CheckSessionIframe: string;
    static readonly ClaimsLocalesSupported: string;
    static readonly ClaimsParameterSupported: string;
    static readonly ClaimsSupported: string;
    static readonly ClaimTypesSupported: string;
    static readonly Discovery: string;
    static readonly DisplayValuesSupported: string;
    static readonly DPoPSigningAlgValuesSupported: string;
    static readonly EndSessionEndpoint: string;
    static readonly FrontchannelLogoutSessionSupported: string;
    static readonly FrontchannelLogoutSupported: string;
    static readonly HttpLogoutSupported: string;
    static readonly GrantTypesSupported: string;
    static readonly IdTokenEncryptionAlgValuesSupported: string;
    static readonly IdTokenEncryptionEncValuesSupported: string;
    static readonly IdTokenSigningAlgValuesSupported: string;
    static readonly IntrospectionEndpoint: string;
    static readonly IntrospectionEndpointAuthMethodsSupported: string;
    static readonly IntrospectionEndpointAuthSigningAlgValuesSupported: string;
    static readonly JwksUri: string;
    static readonly Issuer: string;
    static readonly LogoutSessionSupported: string;
    static readonly MicrosoftMultiRefreshToken: string;
    static readonly OpPolicyUri: string;
    static readonly OpTosUri: string;
    static readonly PromptValuesSupported: string;
    static readonly PushedAuthorizationRequestEndpoint: string;
    static readonly RegistrationEndpoint: string;
    static readonly RequestObjectEncryptionAlgValuesSupported: string;
    static readonly RequestObjectEncryptionEncValuesSupported: string;
    static readonly RequestObjectSigningAlgValuesSupported: string;
    static readonly RequestParameterSupported: string;
    static readonly RequestUriParameterSupported: string;
    static readonly RequirePushedAuthorizationRequests: string;
    static readonly RequireRequestUriRegistration: string;
    static readonly ResponseModesSupported: string;
    static readonly ResponseTypesSupported: string;
    static readonly ServiceDocumentation: string;
    static readonly ScopesSupported: string;
    static readonly SubjectTypesSupported: string;
    static readonly TokenEndpoint: string;
    static readonly TokenEndpointAuthMethodsSupported: string;
    static readonly TokenEndpointAuthSigningAlgValuesSupported: string;
    static readonly UILocalesSupported: string;
    static readonly UserInfoEndpoint: string;
    static readonly UserInfoEncryptionAlgValuesSupported: string;
    static readonly UserInfoEncryptionEncValuesSupported: string;
    static readonly UserInfoSigningAlgValuesSupported: string;
}


export type OpenIdProviderMetadataNames = OpenIdProviderMetadataNames$instance;

