// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal
// Assembly: Microsoft.EntityFrameworkCore.SqlServer

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, Void } from "@tsonic/dotnet/System.js";
import type { IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbContextOptionsExtensionInfo, IDbContextOptions, IDbContextOptionsExtension, IModelValidator, ISingletonOptions, ModelValidatorDependencies, RelationalModelValidator, RelationalModelValidatorDependencies, RelationalOptionsExtension } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbLoggerCategory$Model$Validation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { IModel } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js";

export enum SqlServerEngineType {
    unknown = 0,
    sqlServer = 1,
    azureSql = 2,
    azureSynapse = 3
}


export interface ISqlServerSingletonOptions$instance extends ISingletonOptions {
    readonly engineType: SqlServerEngineType;
    readonly sqlServerCompatibilityLevel: int;
    readonly azureSqlCompatibilityLevel: int;
    readonly azureSynapseCompatibilityLevel: int;
    readonly supportsJsonFunctions: boolean;
    readonly supportsJsonObjectArray: boolean;
    readonly supportsJsonType: boolean;
}


export type ISqlServerSingletonOptions = ISqlServerSingletonOptions$instance;

export interface SqlServerModelValidator$instance extends RelationalModelValidator {
    validate(model: IModel, logger: IDiagnosticsLogger<DbLoggerCategory$Model$Validation>): void;
}


export const SqlServerModelValidator: {
    new(dependencies: ModelValidatorDependencies, relationalDependencies: RelationalModelValidatorDependencies): SqlServerModelValidator;
};


export type SqlServerModelValidator = SqlServerModelValidator$instance;

export interface SqlServerOptionsExtension$instance extends RelationalOptionsExtension {
    readonly azureSqlCompatibilityLevel: int;
    readonly azureSynapseCompatibilityLevel: int;
    readonly engineType: SqlServerEngineType;
    readonly info: DbContextOptionsExtensionInfo;
    readonly sqlServerCompatibilityLevel: int;
    readonly useRetryingStrategyByDefault: boolean;
    applyDefaults(options: IDbContextOptions): IDbContextOptionsExtension;
    applyServices(services: IServiceCollection): void;
    validate(options: IDbContextOptions): void;
    withAzureSqlCompatibilityLevel(azureSqlCompatibilityLevel: Nullable<System_Internal.Int32>): SqlServerOptionsExtension;
    withAzureSynapseCompatibilityLevel(azureSynapseCompatibilityLevel: Nullable<System_Internal.Int32>): SqlServerOptionsExtension;
    withEngineType(engineType: SqlServerEngineType): SqlServerOptionsExtension;
    withLegacyAzureSql(enable: boolean): SqlServerOptionsExtension;
    withSqlServerCompatibilityLevel(sqlServerCompatibilityLevel: Nullable<System_Internal.Int32>): SqlServerOptionsExtension;
    withUseRetryingStrategyByDefault(enable: boolean): SqlServerOptionsExtension;
}


export const SqlServerOptionsExtension: {
    new(): SqlServerOptionsExtension;
    readonly sqlServerDefaultCompatibilityLevel: int;
    readonly azureSqlDefaultCompatibilityLevel: int;
    readonly azureSynapseDefaultCompatibilityLevel: int;
};


export type SqlServerOptionsExtension = SqlServerOptionsExtension$instance;

export interface SqlServerSingletonOptions$instance {
    readonly azureSqlCompatibilityLevel: int;
    readonly azureSynapseCompatibilityLevel: int;
    readonly engineType: SqlServerEngineType;
    readonly sqlServerCompatibilityLevel: int;
    readonly supportsJsonFunctions: boolean;
    readonly supportsJsonObjectArray: boolean;
    readonly supportsJsonType: boolean;
    initialize(options: IDbContextOptions): void;
    validate(options: IDbContextOptions): void;
}


export const SqlServerSingletonOptions: {
    new(): SqlServerSingletonOptions;
};


export interface __SqlServerSingletonOptions$views {
    As_ISqlServerSingletonOptions(): ISqlServerSingletonOptions$instance;
}

export interface SqlServerSingletonOptions$instance extends ISqlServerSingletonOptions$instance {}

export type SqlServerSingletonOptions = SqlServerSingletonOptions$instance & __SqlServerSingletonOptions$views;


